const { execSync } = require('child_process');
const fs = require('fs');

console.log("I cannot run direct Firebase node queries without service account credentials.");
console.log("But I can test the string parsing logic of checkContactExists.");

const phone = '08374331432';

const rawDigits = phone.replace(/\D/g, '');
const last10 = rawDigits.slice(-10);
const plus91 = `+91${last10}`;
const spaced1 = `+91 ${last10}`;
const spaced2 = `+91 ${last10.slice(0,5)} ${last10.slice(5)}`;
const format91 = `91${last10}`;
const intFormat = parseInt(last10, 10);
const intFormat91 = parseInt(format91, 10);

const formats = [last10, plus91, format91, phone, spaced1, spaced2, intFormat, intFormat91];
const possibleFormats = formats.filter(v => v !== undefined && v !== null && !Number.isNaN(v));

console.log("Input phone:", phone);
console.log("Possible Formats generated by checkContactExists:");
console.log(possibleFormats);

const rawPhone = '08374331432';
const digitsOnly = rawPhone.replace(/\D/g, '');
const last10_new = digitsOnly.slice(-10);
const cleanedPhone = `+91${last10_new}`;

console.log("\nWhat InviteMembersModal saves as phone:", cleanedPhone);
