const { buildBank } = require('./bank_builder.js');

// 50 Foundation Facts for Mother
const foundationFacts = [
  {
    easyQ: "Who is named in Genesis 3:20 as the 'mother of all living'?",
    easyQTe: "ఆదికాండము 3:20 లో 'జీవముగల ప్రతివానికిని తల్లి' అని పిలువబడిన స్త్రీ ఎవరు?",
    medQ: "According to Genesis 3:20, why did Adam name his wife Eve (Chavah)?",
    medQTe: "ఆదికాండము 3:20 ప్రకారం ఆదాము తన భార్యకు హవ్వ అని పేరు పెట్టుటకు గల కారణమేమి?",
    hardQ: "What theological significance does the Hebrew name Chavah (Eve) carry in the covenant promise of Genesis 3:15?",
    hardQTe: "ఆదికాండము 3:15 లోని మెస్సీయ నిబంధన వాగ్దానములో హవ్వ అను పేరు ఏ ఆత్మీయ ప్రాముఖ్యతను కలిగియున్నది?",
    options: ["Eve", "Sarah", "Rebekah", "Noah's wife"],
    optionsTelugu: ["హవ్వ", "శారా", "రిబ్కా", "నోవహు భార్య"],
    correctAnswer: "Eve",
    bibleReference: "Genesis 3:20",
    explanation: "Adam named his wife Eve because she would become the mother of all the living.",
    explanationTelugu: "హవ్వ జీవముగల ప్రతివానికిని తల్లియగునని ఆదాము ఆమెకు ఆ పేరు పెట్టెను."
  },
  {
    easyQ: "Which faithful mother was promised by God that she would be a 'mother of nations' and bear Isaac at age ninety?",
    easyQTe: "దేవుని వాగ్దానము పొంది తొంబది ఏండ్ల వయస్సులో ఇస్సాకును కని 'జనములకు తల్లి' అయిన భక్తిగల స్త్రీ ఎవరు?",
    medQ: "In Genesis 17:16, what royal blessing did God bestow upon Sarah regarding kings?",
    medQTe: "ఆదికాండము 17:16 లో శారాకు రాజుల విషయములో దేవుడు ఏ వాగ్దానము చేసెను?",
    hardQ: "How does the apostle Peter in 1 Peter 3:6 hold up Sarah as the spiritual mother of all believing women?",
    hardQTe: "1 పేతురు 3:6 లో పేతురు అపొస్తలుడు శారాను విశ్వాసులైన స్త్రీలందరికీ ఆత్మీయ తల్లిగా ఎలా కొనియాడెను?",
    options: ["Sarah", "Hagar", "Keturah", "Milcah"],
    optionsTelugu: ["శారా", "హాగరు", "కెతూరా", "మిల్కా"],
    correctAnswer: "Sarah",
    bibleReference: "Genesis 17:16, 21:1-3",
    explanation: "God promised Sarah that kings of peoples would come from her, and she gave birth to Isaac.",
    explanationTelugu: "దేవుడు శారాను ఆశీర్వదించి ఆమె వలన జనములును జనముల రాజులును పుట్టుదురని వాగ్దానము చేసెను."
  },
  {
    easyQ: "What joyful laughter filled Sarah's heart when Isaac was born in Genesis 21:6?",
    easyQTe: "ఆదికాండము 21:6 లో ఇస్సాకు పుట్టినప్పుడు శారా హృదయములో ఏ ఆనందపు నవ్వు నిండెను?",
    medQ: "What exact words did Sarah proclaim in Genesis 21:6 about all who hear of Isaac's birth?",
    medQTe: "ఆదికాండము 21:6 లో శారా తన కుమారుని పుట్టుకను వినువారందరు ఏమి చేయుదురని పలికెను?",
    hardQ: "How does Sarah's laughter of joyous faith in Genesis 21 contrast with her earlier laughter of doubt in Genesis 18?",
    hardQTe: "ఆదికాండము 18 లోని అనుమానపు నవ్వుతో పోలిస్తే 21వ అధ్యాయములో శారా నవ్వు ఏ విశ్వాస పరివర్తనను చాటుచున్నది?",
    options: ["\"God has brought me laughter, and everyone who hears about this will laugh with me\"", "\"The silver of Haran has increased\"", "\"We shall build seven towers in Canaan\"", "\"The famine has overtaken Egypt\""],
    optionsTelugu: ["\"దేవుడు నాకు నవ్వు కలుగజేసెను, వినువారందరును నాతోకూడ నవ్వుదురు\"", "\"హారాను వెండి విస్తరించెను\"", "\"కనానులో ఏడు గోపురములు కట్టుదము\"", "\"ఐగుప్తులో కరువు వచ్చెను\""],
    correctAnswer: "\"God has brought me laughter, and everyone who hears about this will laugh with me\"",
    bibleReference: "Genesis 21:6",
    explanation: "Sarah rejoiced that God turned her barren sorrow into miraculous, contagious laughter.",
    explanationTelugu: "దేవుడు నాకు నవ్వు కలుగజేసెను, వినువారందరు నా సంతోషములో పాలుపొందుదురని శారా ఆనందించెను."
  },
  {
    easyQ: "Which mother was comforted by the Angel of the Lord at the spring Beer Lahai Roi when fleeing into the wilderness?",
    easyQTe: "అరణ్యములోనికి పారిపోయినప్పుడు బేయేర్లహాయిరోయి యొద్ద ప్రభువు దూతచేత ఆదరింపబడిన తల్లి ఎవరు?",
    medQ: "In Genesis 16:13, what enduring name did Hagar give to the Lord who saw her in maternal distress?",
    medQTe: "ఆదికాండము 16:13 లో తన శ్రమను చూచిన దేవునికి హాగరు ఏ పేరు పెట్టెను?",
    hardQ: "What theological truth is enshrined in the name El Roi ('You are the God who sees me') for marginalized mothers?",
    hardQTe: "'నన్ను చూచుచున్న దేవుడవు నీవే' (ఎల్ రోయీ) అను నామము శ్రమనొందు తల్లులకు ఏ శాశ్వత ఓదార్పునిచ్చుచున్నది?",
    options: ["Hagar", "Bilhah", "Zilpah", "Puah"],
    optionsTelugu: ["హాగరు", "బిల్హా", "జిల్పా", "పూవా"],
    correctAnswer: "Hagar",
    bibleReference: "Genesis 16:7-14",
    explanation: "Hagar named God El Roi, testifying: 'You are the God who sees me.'",
    explanationTelugu: "హాగరు: నన్ను చూచుచున్న దేవుడవు నీవే అని యెహోవాకు పేరు పెట్టెను."
  },
  {
    easyQ: "What did God do when Hagar wept under a bush thinking her boy Ishmael would die of thirst?",
    easyQTe: "తన కుమారుడైన ఇష్మాయేలు దాహముతో చనిపోవునని హాగరు పొద క్రింద కూర్చుండి ఏడ్చినప్పుడు దేవుడు ఏమి చేసెను?",
    medQ: "According to Genesis 21:17-19, what provision did God reveal to save the weeping mother and her son?",
    medQTe: "ఆదికాండము 21:17-19 ప్రకారం రోదించుచున్న తల్లిని బిడ్డను రక్షించుటకు దేవుడు దేనిని కనుపరచెను?",
    hardQ: "How does the phrase 'God heard the voice of the lad' highlight God's sovereign attentiveness to children's cries?",
    hardQTe: "'దేవుడు ఆ చిన్నవాని మొరను వినెను' అను మాట పిల్లల మొరల పట్ల దేవునికున్న వాత్సల్యమును ఎలా చాటుచున్నది?",
    options: ["God opened her eyes and she saw a well of water to fill her skin", "He sent twelve chariots from Egypt", "He commanded the clouds to drop silver", "He struck the desert rock with Moses' staff"],
    optionsTelugu: ["దేవుడు ఆమె కన్నులు తెరవగా ఆమె నీళ్ల బావిని చూచి తిత్తిని నీళ్లతో నింపెను", "ఐగుప్తునుండి పన్నెండు రథములను పంపెను", "మేఘములనుండి వెండి కురిపించెను", "మోషే కఱ్ఱతో బండను కొట్టెను"],
    correctAnswer: "God opened her eyes and she saw a well of water to fill her skin",
    bibleReference: "Genesis 21:17-19",
    explanation: "God heard the boy crying, opened Hagar's eyes to see a well of water, and preserved their lives.",
    explanationTelugu: "దేవుడు చిన్నవాని మొరను విని, హాగరు కన్నులు తెరవగా ఆమె నీళ్ల బావిని చూచి బిడ్డ దాహము తీర్చెను."
  },
  {
    easyQ: "Which mother inquired of the Lord when her twin babies struggled within her womb in Genesis 25:22?",
    easyQTe: "ఆదికాండము 25:22 లో తన గర్భములో కవల పిల్లలు ఒకరినొకరు నెట్టుకొనినప్పుడు యెహోవాయొద్ద విచారించిన తల్లి ఎవరు?",
    medQ: "What divine prophecy concerning two nations and elder serving younger did God speak to Rebekah?",
    medQTe: "ఆదికాండము 25:23 లో రెండు జనములను గూర్చియు, పెద్దవాడు చిన్నవానికి దాసుడగుననియు దేవుడు రిబ్కాతో ఏ ప్రవచనము పలికెను?",
    hardQ: "How does the divine revelation to Rebekah in Genesis 25:23 form the bedrock of Paul's doctrine of sovereign election in Romans 9?",
    hardQTe: "రోమీయులకు 9 లో పౌలు దైవిక ఎన్నిక సిద్ధాంతమునకు రిబ్కా పొందిన ప్రత్యక్షత ఏ విధముగా మూలస్తంభముగా ఉన్నది?",
    options: ["Rebekah", "Rachel", "Leah", "Keturah"],
    optionsTelugu: ["రిబ్కా", "రాహేలు", "లేయా", "కెతూరా"],
    correctAnswer: "Rebekah",
    bibleReference: "Genesis 25:21-23",
    explanation: "Rebekah sought the Lord and received the prophecy: 'Two nations are in your womb... the older will serve the younger.'",
    explanationTelugu: "రిబ్కా యెహోవాయొద్ద విచారించగా: రెండు జనములు నీ గర్భములో కలవు, పెద్దవాడు చిన్నవానికి దాసుడగునని దేవుడు సెలవిచ్చెను."
  },
  {
    easyQ: "Which son did Rachel name Ben-Oni ('son of my sorrow') as her soul departed in childbirth?",
    easyQTe: "ప్రసవవేదనతో ప్రాణము విడుచుచుండగా రాహేలు తన కుమారునికి 'బెనోనీ' (నా వేదన పుత్రుడు) అని ఏ కుమారునికి పేరు పెట్టెను?",
    medQ: "What name did Jacob give to the child whom dying Rachel called Ben-Oni in Genesis 35:18?",
    medQTe: "ఆదికాండము 35:18 లో చనిపోవుచున్న రాహేలు బెనోనీ అని పిలిచిన కుమారునికి యాకోబు ఏ పేరు పెట్టెను?",
    hardQ: "How does the prophetic sorrow of Rachel weeping for her children find Messianic fulfillment in Matthew 2:18?",
    hardQTe: "యిర్మీయా 31:15 మరియు మత్తయి 2:18 లో తన పిల్లలకొరకు ఏడ్చుచున్న రాహేలు విలాపము మెస్సీయ కాలములో ఎలా నెరవేరెను?",
    options: ["Benjamin", "Joseph", "Dan", "Naphtali"],
    optionsTelugu: ["బెన్యామీను", "యోసేపు", "దాను", "నఫ్తాలి"],
    correctAnswer: "Benjamin",
    bibleReference: "Genesis 35:18",
    explanation: "Rachel died giving birth near Bethlehem, naming him Ben-Oni, but Jacob called him Benjamin ('son of my right hand').",
    explanationTelugu: "రాహేలు ప్రాణము పోవుచుండగా అతనికి బెనోనీ అని పేరు పెట్టెను, కానీ అతని తండ్రి అతనికి బెన్యామీను అని పేరు పెట్టెను."
  },
  {
    easyQ: "Who was the unloved wife who praised God when her fourth son Judah was born, through whom the Messiah came?",
    easyQTe: "తన నాల్గవ కుమారుడైన యూదా పుట్టినప్పుడు దేవుని స్తుతించిన నిర్లక్ష్యము చేయబడిన తల్లి ఎవరు?",
    medQ: "What joyous proclamation of praise did Leah utter in Genesis 29:35 when naming Judah?",
    medQTe: "ఆదికాండము 29:35 లో యూదాను కనినప్పుడు లేయా ఏమని దేవుని స్తుతించెను?",
    hardQ: "What spiritual progression is revealed in Leah's heart across the naming of Reuben, Simeon, Levi, and Judah?",
    hardQTe: "రూబేను, షిమ్యోను, లేవి, యూదాల పేర్ల ద్వారా లేయా హృదయములో భర్త ప్రీతికంటె దేవుని స్తుతి వైపు కలిగిన ఆత్మీయ పరివర్తన ఏది?",
    options: ["Leah", "Rachel", "Bilhah", "Tamar"],
    optionsTelugu: ["లేయా", "రాహేలు", "బిల్హా", "తామారు"],
    correctAnswer: "Leah",
    bibleReference: "Genesis 29:35",
    explanation: "At Judah's birth, Leah declared: 'Now will I praise the Lord', shifting her focus entirely to God.",
    explanationTelugu: "లేయా: ఈసారి నేను యెహోవాను స్తుతించెదనని చెప్పి అతనికి యూదా అని పేరు పెట్టెను."
  },
  {
    easyQ: "Which courageous mother hid her baby boy Moses for three months from Pharaoh's murderous decree?",
    easyQTe: "ఫరో యొక్క ఘోరమైన ఆజ్ఞనుండి తన కుమారుడైన మోషేను మూడు నెలలు దాచిపెట్టిన ధైర్యవంతురాలైన తల్లి ఎవరు?",
    medQ: "What kind of basket coated with tar and pitch did Jochebed prepare for baby Moses in Exodus 2:3?",
    medQTe: "నిర్గమకాండము 2:3 లో యోకెబెదు మోషే కొరకు ఏ పేటికను సిద్ధపరచి కీలు నల్లమన్ను పూసెను?",
    hardQ: "How does Hebrews 11:23 honor the faith of Moses' parents in refusing to fear the king's royal edict?",
    hardQTe: "హెబ్రీ 11:23 ప్రకారం రాజు ఆజ్ఞకు భయపడక మోషే తల్లిదండ్రులు చూపిన విశ్వాసము ఎలా కొనియాడబడెను?",
    options: ["Jochebed", "Miriam", "Elisheba", "Zipporah"],
    optionsTelugu: ["యోకెబెదు", "మిర్యాము", "ఎలీషెబ", "సిప్పోరా"],
    correctAnswer: "Jochebed",
    bibleReference: "Exodus 2:1-3, 6:20",
    explanation: "Jochebed placed baby Moses in a papyrus basket among the reeds of the Nile, trusting God's protection.",
    explanationTelugu: "యోకెబెదు జమ్ములో ఒక పేటిక చేసి, కీలును నల్లమన్నును పూసి పిల్లవానిని అందులో ఉంచి ఏటిగట్టున జమ్ములో పెట్టెను."
  },
  {
    easyQ: "Who drew baby Moses out of the Nile river and raised him as her adoptive son?",
    easyQTe: "మోషేను నైలు నదిలోనుండి పైకి తీసి తన సొంత కుమారునిగా పెంచుకొనిన దత్తత తల్లి ఎవరు?",
    medQ: "In Exodus 2:10, why did Pharaoh's daughter name the child Moses (Moshe)?",
    medQTe: "నిర్గమకాండము 2:10 లో ఫరో కుమార్తె ఆ బాలునికి మోషే అని పేరు పెట్టుటకు గల కారణమేమి?",
    hardQ: "How did God's providence use Pharaoh's daughter's motherly compassion to preserve Israel's future deliverer?",
    hardQTe: "ఇశ్రాయేలు విమోచకుడైన మోషేను రక్షించుటకు దేవుడు ఫరో కుమార్తె యొక్క మాతృప్రేమను ఎలా ఉపయోగించెను?",
    options: ["Pharaoh's daughter", "The queen of Ethiopia", "Potiphar's wife", "The priestess of On"],
    optionsTelugu: ["ఫరో కుమార్తె", "కూషు రాణి", "పోతీఫరు భార్య", "ఓను యాజకురాలైన స్త్రీ"],
    correctAnswer: "Pharaoh's daughter",
    bibleReference: "Exodus 2:5-10",
    explanation: "Pharaoh's daughter had compassion on the crying baby and named him Moses, meaning 'drawn out of the water'.",
    explanationTelugu: "ఫరో కుమార్తె కనికరపడి: నీళ్లలోనుండి నేను ఇతనిని తీసితినని చెప్పి అతనికి మోషే అని పేరు పెట్టెను."
  },
  {
    easyQ: "Which barren mother wept bitterly at the tabernacle in Shiloh, vowing to dedicate her son to the Lord?",
    easyQTe: "షీలోహులోని ప్రత్యక్షపు గుడారము వద్ద కన్నీరు కార్చి, తనకు పుట్టు కుమారుని యెహోవాకు ప్రతిష్ఠించెదనని మ్రొక్కుకొనిన తల్లి ఎవరు?",
    medQ: "What priest mistakenly assumed Hannah was drunk when seeing her lips move without sound in 1 Samuel 1:13?",
    medQTe: "1 సమూయేలు 1:13 లో పెదవులు కదులుచు శబ్దము వినబడనందున హన్నా మత్తురాలై యున్నదని తలంచిన యాజకుడు ఎవరు?",
    hardQ: "What does Hannah's vow of a Nazirite dedication in 1 Samuel 1:11 reveal about consecrated motherhood?",
    hardQTe: "1 సమూయేలు 1:11 లో సమూయేలు తలపై క్షౌరపు కత్తి రానియ్యనని హన్నా చేసిన నాజీరు మ్రొక్కుబడి ఏ ప్రతిష్ఠను సూచించుచున్నది?",
    options: ["Hannah", "Peninnah", "Michal", "Abigail"],
    optionsTelugu: ["హన్నా", "పెనిన్నా", "మీకాలు", "అబీగయీలు"],
    correctAnswer: "Hannah",
    bibleReference: "1 Samuel 1:9-15",
    explanation: "Hannah poured out her soul before the Lord at Shiloh, praying for a son to dedicate to God's service.",
    explanationTelugu: "హన్నా మనోదుఃఖము గలదై యెహోవా సన్నిధిని తన హృదయమును కుమ్మరించి సమూయేలు కొరకు ప్రార్థించెను."
  },
  {
    easyQ: "What special garment did Hannah sew and bring to Samuel at Shiloh every year as he grew?",
    easyQTe: "సమూయేలు ఎదుగుచుండగా హన్నా ప్రతి సంవత్సరము తన చేతులతో కుట్టి షీలోహునకు తెచ్చిన వస్త్రమేది?",
    medQ: "According to 1 Samuel 2:19, on what occasion did Hannah bring the little coat to her dedicated son?",
    medQTe: "1 సమూయేలు 2:19 ప్రకారం హన్నా ఏ పండుగ బలి అర్పించుటకు వెళ్లినప్పుడు ఆ చిన్న అంగీని తెచ్చెడిది?",
    hardQ: "How did Hannah's annual gift of a robe symbolize ongoing motherly nurture alongside spiritual dedication?",
    hardQTe: "ప్రతి సంవత్సరము చిన్న అంగీని కుట్టి తెచ్చుట దేవునికి ప్రతిష్ఠించిన కుమారుని పట్ల తల్లి ప్రేమను ఎలా చాటుచున్నది?",
    options: ["A little robe (coat) sewn with her own hands", "A gold chain of Egypt", "A pair of purple sandals", "A leather shield"],
    optionsTelugu: ["తన చేతులతో కుట్టిన ఒక చిన్న అంగీ", "ఐగుప్తు బంగారు గొలుసు", "ఊదా రంగు చెప్పులు", "తోలు డాలు"],
    correctAnswer: "A little robe (coat) sewn with her own hands",
    bibleReference: "1 Samuel 2:19",
    explanation: "Every year Hannah made Samuel a little robe and brought it when she went up with her husband to offer sacrifices.",
    explanationTelugu: "అతని తల్లి ప్రతి సంవత్సరము ఒక చిన్న అంగీ కుట్టి, ఏటేట బలి అర్పించుటకు వెళ్లినప్పుడు అతనికి తెచ్చెడిది."
  },
  {
    easyQ: "What magnificent prophetic song of praise did Hannah proclaim in 1 Samuel 2:1-10 celebrating God's power?",
    easyQTe: "1 సమూయేలు 2:1-10 లో దేవుని సర్వాధికారమును కొనియాడుచు హన్నా గానము చేసిన ప్రవచన ప్రార్థన ఏది?",
    medQ: "In 1 Samuel 2:2, how did Hannah describe the holy uniqueness of the Lord in her prayer?",
    medQTe: "1 సమూయేలు 2:2 లో హన్నా దేవుని పరిశుద్ధతను ఏమని కొనియాడెను?",
    hardQ: "How does Hannah's song in 1 Samuel 2 prophetically anticipate Mary's Magnificat in Luke 1?",
    hardQTe: "హన్నా ప్రార్థనా గీతము నూతన నిబంధనలో మరియ పాడిన స్తోత్ర గీతముతో (లూకా 1) ఏ ఆత్మీయ సాదృశ్యము కలిగియున్నది?",
    options: ["\"My heart rejoices in the Lord; my horn is exalted in the Lord!\"", "\"The kings of Aram shall fall\"", "\"Our horses are swifter than eagles\"", "\"We possess the gates of Tyre\""],
    optionsTelugu: ["\"నా హృదయము యెహోవాయందు అతిశయించుచున్నది, యెహోవాయందు నా శృంగము హెచ్చింపబడెను!\"", "\"అరాము రాజులు కూలిపోవుదురు\"", "\"మా గుర్రములు పక్షులకంటె వేగమైనవి\"", "\"సోరు ద్వారములను పట్టుకొంటిమి\""],
    correctAnswer: "\"My heart rejoices in the Lord; my horn is exalted in the Lord!\"",
    bibleReference: "1 Samuel 2:1-10",
    explanation: "Hannah exalted God, proclaiming that the Lord humbles the proud and exalts the humble.",
    explanationTelugu: "యెహోవావంటి పరిశుద్ధుడు లేడు, నా హృదయము యెహోవాయందు ఆనందించుచున్నదని హన్నా స్తుతించెను."
  },
  {
    easyQ: "Which mother was visited by the Angel of the Lord and told that her unborn son Samson would deliver Israel?",
    easyQTe: "ప్రభువు దూత దర్శనము పొంది, తన గర్భమందు పుట్టు కుమారుడైన సమ్సోను ఇశ్రాయేలును రక్షించునని తెలియజేయబడిన తల్లి ఎవరు?",
    medQ: "In Judges 13:4, what strict Nazirite dietary laws was Samson's mother commanded to observe during pregnancy?",
    medQTe: "న్యాయాధిపతులు 13:4 లో గర్భవతిగా ఉన్నప్పుడు సమ్సోను తల్లి ఏ పదార్థములను ముట్టకూడదని దూత ఆజ్ఞాపించెను?",
    hardQ: "What does Manoah's wife's spiritual discernment in Judges 13:23 reveal about her faith compared to Manoah's fear?",
    hardQTe: "మనోహ భయపడినప్పుడు అతని భార్య దేవుని చిత్తమును గ్రహించి ధైర్యము చెప్పుట (న్యాయాధిపతులు 13:23) ఆమె ఏ ఆత్మీయ పరిపక్వతను చూపుచున్నది?",
    options: ["Manoah's wife (Samson's mother)", "Delilah", "Jephthah's mother", "Gideon's mother"],
    optionsTelugu: ["మనోహ భార్య (సమ్సోను తల్లి)", "దెలీలా", "యెఫ్తా తల్లి", "గిద్యోను తల్లి"],
    correctAnswer: "Manoah's wife (Samson's mother)",
    bibleReference: "Judges 13:2-7, 24",
    explanation: "The Angel instructed Samson's mother to drink no wine and eat nothing unclean because the boy was a Nazirite from the womb.",
    explanationTelugu: "సమ్సోను తల్లి గర్భమునందున్న బిడ్డ కొరకు ద్రాక్షారసము గాని మద్యము గాని త్రాగక పవిత్రముగా ఉండవలెనని దేవదూత ఆజ్ఞాపించెను."
  },
  {
    easyQ: "Who arose as a 'mother in Israel' during a time of national oppression in Judges 5:7?",
    easyQTe: "న్యాయాధిపతులు 5:7 ప్రకారం దేశములో శ్రమలు ఎక్కువైనప్పుడు 'ఇశ్రాయేలులో తల్లిగా' లేచిన ప్రవక్త్రి ఎవరు?",
    medQ: "According to Judges 5:6-7, what was the desolate condition of Israel before Deborah arose as a mother?",
    medQTe: "న్యాయాధిపతులు 5:6-7 లో దెబోరా తల్లిగా లేచువరకు ఇశ్రాయేలులోని రహదారులు, గ్రామాంతరములు ఏ దుస్థితిలో ఉండెను?",
    hardQ: "What leadership paradigm is established when a prophetess and judge is honored with the title 'Mother in Israel'?",
    hardQTe: "'ఇశ్రాయేలులో తల్లి' అను బిరుదు నాయకత్వములో మాతృత్వపు ప్రేమను, రక్షణను ఎలా ప్రతిబింబించుచున్నది?",
    options: ["Deborah", "Jael", "Miriam", "Huldah"],
    optionsTelugu: ["దెబోరా", "యాయేలు", "మిర్యాము", "హుల్దా"],
    correctAnswer: "Deborah",
    bibleReference: "Judges 5:7",
    explanation: "Village life ceased until Deborah arose, a mother in Israel, to guide and protect God's people.",
    explanationTelugu: "దెబోరా అను నేను ఇశ్రాయేలులో తల్లిగా లేచువరకు గ్రామాంతరవాసులు నివాసము లేకపోయిరని దెబోరా కీర్తించెను."
  },
  {
    easyQ: "Which mother interceded courageously before elderly King David to ensure her son Solomon received the throne?",
    easyQTe: "తన కుమారుడైన సొలొమోనునకు రాజ్యాధికారము దక్కునట్లు వృద్ధుడైన దావీదు రాజు ఎదుట విజ్ఞాపన చేసిన తల్లి ఎవరు?",
    medQ: "In 1 Kings 1:11-31, which prophet collaborated with Bathsheba to protect Solomon from Adonijah's coup?",
    medQTe: "1 రాజులు 1 లో అదోనీయా కుట్రనుండి సొలొమోనును రక్షించుటకు బత్షెబతో కలిసి రాజునొద్దకు వెళ్లిన ప్రవక్త ఎవరు?",
    hardQ: "What royal role did Bathsheba assume as Gebirah (Queen Mother) once Solomon ascended the throne in 1 Kings 2:19?",
    hardQTe: "1 రాజులు 2:19 లో సొలొమోను సింహాసనమెక్కిన తరువాత బత్షెబ 'రాజమాత'గా సింహాసనము కుడిపార్శ్వమున ఏ గౌరవము పొందెను?",
    options: ["Bathsheba", "Abital", "Haggith", "Maacah"],
    optionsTelugu: ["బత్షెబ", "అబీటలు", "హగ్గీతు", "మాకా"],
    correctAnswer: "Bathsheba",
    bibleReference: "1 Kings 1:11-31, 2:19",
    explanation: "Bathsheba appealed to David's oath before God, securing Solomon's anointing as king over Israel.",
    explanationTelugu: "బత్షెబ దావీదు రాజునొద్దకు వెళ్లి ప్రార్థించి, సొలొమోను రాజుగా నియమింపబడునట్లు చేసెను."
  },
  {
    easyQ: "In Solomon's famous judgment in 1 Kings 3, how did the true mother prove her authentic maternal love?",
    easyQTe: "1 రాజులు 3 లో సొలొమోను తీర్పు తీర్చినప్పుడు నిజమైన తల్లి తన బిడ్డపై గల మాతృప్రేమను ఎలా రుజువు చేసెను?",
    medQ: "What did the true mother cry out when Solomon commanded the living child to be divided with a sword?",
    medQTe: "1 రాజులు 3:26 లో సజీవముగా ఉన్న బిడ్డను కత్తితో రెండు ముక్కలు చేయుడని రాజు ఆజ్ఞాపించినప్పుడు నిజమైన తల్లి ఏమని కేక వేసెను?",
    hardQ: "How does the true mother's willingness to give up her child rather than see him slain demonstrate sacrificial agape love?",
    hardQTe: "బిడ్డను చంపుటకంటె మరియొకరికి ఇచ్చుటకైనా సిద్ధపడిన ఆ తల్లి త్యాగము ఏ దైవిక ప్రేమను ప్రతిబింబించుచున్నది?",
    options: ["She pleaded: \"O my lord, give her the living child, and by no means kill him!\"", "\"Divide the child equally between us\"", "\"Cast the child into the Kidron valley\"", "\"Send the child into exile in Moab\""],
    optionsTelugu: ["\"నా యేలినవాడా, ఆ సజీవమైన బిడ్డను చంపక ఆమెకే ఇప్పింపుము!\"", "\"బిడ్డను ఇద్దరికీ సమానముగా కోయుడి\"", "\"బిడ్డను కిద్రోను లోయలో పడవేయుడి\"", "\"మోయాబునకు వెళ్లగొట్టుడి\""],
    correctAnswer: "She pleaded: \"O my lord, give her the living child, and by no means kill him!\"",
    bibleReference: "1 Kings 3:16-27",
    explanation: "The real mother's heart yearned with compassion for her son, willing to surrender him rather than see him die.",
    explanationTelugu: "నిజమైన తల్లి పేగులు కరిగిపోయి: బిడ్డను చంపవద్దు, ఆమెకే ఇచ్చివేయుడని రాజుతో వేడుకొనెను."
  },
  {
    easyQ: "Which poor widow gathering sticks to make a final meal for her son had her flour and oil multiplied by Elijah?",
    easyQTe: "తన కుమారునికి చివరి భోజనము చేసి చనిపోవుదమని కట్టెలు ఏరుకొనుచుండగా ఏలీయా వలన పిండి నూనెలు సమృద్ధిగా పొందిన విధవరాలు ఎవరు?",
    medQ: "According to 1 Kings 17:12-16, what miracle sustained the widow of Zarephath, her son, and Elijah through the drought?",
    medQTe: "1 రాజులు 17:12-16 ప్రకారం కరువు కాలమంతయు సారెపతు విధవరాలిని, ఆమె కుమారుని కాపాడిన అద్భుతమేది?",
    hardQ: "What supreme step of maternal faith did the widow take in feeding the man of God first before her starving son?",
    hardQTe: "ఆకలితో ఉన్న తన కుమారునికంటె ముందు దైవజనునికి మొదట రొట్టె చేసి తెచ్చుటలో ఆ తల్లి ఏ విశ్వాస పరిపక్వతను కనబరచెను?",
    options: ["The widow of Zarephath", "The woman of Shunem", "The queen of Sheba", "The widow of Tekoa"],
    optionsTelugu: ["సారెపతు ఊరి విధవరాలు", "షూనేమీయురాలు", "షెబారాణి", "తెకోవ విధవరాలు"],
    correctAnswer: "The widow of Zarephath",
    bibleReference: "1 Kings 17:8-16",
    explanation: "The jar of flour was not exhausted and the jug of oil did not run dry according to the word of the Lord.",
    explanationTelugu: "యెహోవా మాట చొప్పున తొట్టిలోని పిండి అయిపోలేదు, బుడ్డిలోని నూనె తరిగిపోలేదు."
  },
  {
    easyQ: "What happened when the son of the widow of Zarephath grew sick and stopped breathing in 1 Kings 17:17-24?",
    easyQTe: "1 రాజులు 17 లో సారెపతు విధవరాలి కుమారుడు జబ్బుపడి శ్వాస ఆగిపోయినప్పుడు ఏమి జరిగెను?",
    medQ: "How many times did Elijah stretch himself out over the widow's dead child crying to the Lord in 1 Kings 17:21?",
    medQTe: "1 రాజులు 17:21 లో ఏలీయా ఆ చనిపోయిన బాలునిపై ఎన్నిసార్లు పడుకొని దేవునికి ప్రార్థించెను?",
    hardQ: "What joyful confession of faith did the restored mother make when Elijah returned her living son?",
    hardQTe: "తన సజీవ కుమారుని చూచినప్పుడు ఆ తల్లి: 'నీవు దైవజనుడవనియు నీ నోటి యెహోవా మాట సత్యమనియు ఇందువలన నేనెరుగుదును' అని పలికిన విశ్వాస సాక్ష్యమేమి?",
    options: ["Elijah prayed and the Lord revived the boy, returning him alive to his mother", "The boy was buried at Mount Carmel", "The widow departed to Sidon in despair", "Twelve priests were summoned from Bethel"],
    optionsTelugu: ["ఏలీయా ప్రార్థించగా దేవుడు బాలుని బ్రతికించి అతని తల్లికి సజీవముగా అప్పగించెను", "కర్మెలు కొండపై పాతిపెట్టిరి", "ఆ విధవరాలు నిరాశతో సీదోనుకు వెళ్లిపోయెను", "బేతేలునుండి పన్నెండుమంది యాజకులను పిలిపించిరి"],
    correctAnswer: "Elijah prayed and the Lord revived the boy, returning him alive to his mother",
    bibleReference: "1 Kings 17:17-24",
    explanation: "God heard Elijah's cry, the soul of the child returned to him, and Elijah presented him alive to his joyful mother.",
    explanationTelugu: "యెహోవా ఏలీయా ప్రార్థన వినగా బాలుడు బ్రదికెను; ఏలీయా అతనిని అతని తల్లికి అప్పగించెను."
  },
  {
    easyQ: "Which hospitable mother built a furnished upper room on the roof for prophet Elisha?",
    easyQTe: "ఎలీషా ప్రవక్త కొరకు మేడమీద ఒక చిన్న గదిని కట్టించి మంచము, బల్ల, పీఠము, దీపస్తంభము ఉంచిన భక్తిగల తల్లి ఎవరు?",
    medQ: "In 2 Kings 4:9-10, what holy recognition prompted the Shunammite woman to prepare lodging for Elisha?",
    medQTe: "2 రాజులు 4:9-10 లో ఎలీషాను 'దేవుని పరిశుద్ధ భక్తుడు' అని గ్రహించి ఆ షూనేమీయురాలు ఏ ఆతిథ్యము నిచ్చెను?",
    hardQ: "How does the Shunammite mother's initiative represent noble, hospitable maternal stewardship in ancient Israel?",
    hardQTe: "షూనేమీయురాలు దైవజనునికి చేసిన ఆతిథ్య సేవ గృహనిర్వాహకత్వములో తల్లులకు ఏ ఉన్నత మాదిరిని ఉంచుచున్నది?",
    options: ["The Shunammite woman", "The widow of Nain", "Martha of Bethany", "Salome"],
    optionsTelugu: ["షూనేమీయురాలు", "నాయీను విధవరాలు", "బేతనియ మార్త", "సలోమే"],
    correctAnswer: "The Shunammite woman",
    bibleReference: "2 Kings 4:8-10",
    explanation: "The Shunammite woman urged her husband to build a room for Elisha, recognizing him as a holy man of God.",
    explanationTelugu: "ఆ షూనేమీయురాలు: ఇతడు దేవుని పరిశుద్ధ భక్తుడని నేను ఎరుగుదును గనుక ఒక మేడగది కట్టుదమని భర్తతో చెప్పెను."
  },
  {
    easyQ: "What unwavering words of faith did the Shunammite mother speak (\"It is well\" / Shalom) when her young son died?",
    easyQTe: "తన కుమారుడు ఎండదెబ్బకు చనిపోయినప్పుడు షూనేమీయ తల్లి అచంచల విశ్వాసముతో పలికిన మాటలేవి (\"క్షేమమే\" / షాలోమ్)?",
    medQ: "In 2 Kings 4:26, what did the grieving mother answer Gehazi when asked: 'Is it well with you? Is it well with your husband? Is it well with the child?'",
    medQTe: "2 రాజులు 4:26 లో గేహజీ: 'నీవు క్షేమమా? నీ పెనిమిటి క్షేమమా? బిడ్డ క్షేమమా?' అని అడిగినప్పుడు ఆ తల్లి ఏమని జవాబిచ్చెను?",
    hardQ: "How does her confession 'It is well' (Shalom) reflect profound maternal trust in God's resurrection power?",
    hardQTe: "బిడ్డ చనిపోయినను 'క్షేమమే' అని పలుకుట ఆ తల్లికి పునరుత్థాన దేవునిపై గల ఏ నిరీక్షణను బయలుపరచుచున్నది?",
    options: ["\"It is well\" (Shalom)", "\"All hope is extinguished\"", "\"Let me die in the field\"", "\"Summon the mourners from Jezreel\""],
    optionsTelugu: ["\"క్షేమమే\" (షాలోమ్)", "\"మా నిరీక్షణ అంతయు పోయెను\"", "\"పొలములో నన్ను చావనియ్యుడి\"", "\"యెజ్రెయేలునుండి రోదనచేయువారిని పిలువుడి\""],
    correctAnswer: "\"It is well\" (Shalom)",
    bibleReference: "2 Kings 4:26",
    explanation: "Even in the agony of her son's death, the Shunammite mother answered in faith: 'It is well.'",
    explanationTelugu: "ఆమె: క్షేమమే అని జవాబిచ్చి ఎలీషాయొద్దకు కర్మెలు కొండకు పరుగెత్తెను."
  },
  {
    easyQ: "How did prophet Elisha restore the Shunammite mother's dead son back to life in 2 Kings 4:32-37?",
    easyQTe: "2 రాజులు 4:32-37 లో ఎలీషా ప్రవక్త ఆ షూనేమీయురాలి చనిపోయిన కుమారుని ఎలా బ్రతికించెను?",
    medQ: "How many times did the child sneeze before opening his eyes in 2 Kings 4:35?",
    medQTe: "2 రాజులు 4:35 లో కన్నులు తెరచుటకు ముందు ఆ చిన్నవాడు ఎన్నిసార్లు తుమ్మెను?",
    hardQ: "What posture of profound worship and gratitude did the mother assume when Elisha told her to take up her son?",
    hardQTe: "2 రాజులు 4:37 లో తన బ్రదికిన కుమారుని తీసికొనుటకు ముందు ఆ తల్లి ఎలీషా పాదములయొద్ద ఏ సాష్టాంగ నమస్కారము చేసెను?",
    options: ["The boy sneezed seven times, opened his eyes, and Elisha called the mother to receive her son", "He poured water of the Jordan upon him", "He sounded a shofar three times", "He laid Elijah's mantle upon his chest"],
    optionsTelugu: ["ఆ చిన్నవాడు ఏడుసార్లు తుమ్మి కన్నులు తెరవగా ఎలీషా ఆ తల్లిని పిలిచి బిడ్డను అప్పగించెను", "యొర్దాను నీళ్లను అతనిపై చల్లెను", "మూడుసార్లు బాకా ఊదెను", "ఏలీయా దుప్పటిని అతని రొమ్ముపై వేసెను"],
    correctAnswer: "The boy sneezed seven times, opened his eyes, and Elisha called the mother to receive her son",
    bibleReference: "2 Kings 4:35-37",
    explanation: "The child sneezed seven times and opened his eyes; the mother fell at Elisha's feet in reverence and took her son.",
    explanationTelugu: "ఆ చిన్నవాడు ఏడుసార్లు తుమ్మి కన్నులు తెరవగా, ఆ తల్లి వచ్చి ఎలీషా కాళ్లమీద పడి సాగిలపడి బిడ్డను ఎత్తికొని పోయెను."
  },
  {
    easyQ: "Which poor widow was instructed by Elisha to borrow empty jars from all her neighbors to save her two sons from debt slavery?",
    easyQTe: "తన ఇద్దరు కుమారులు అప్పులవారికి బానిసలు కాకుండునట్లు పొరుగువారందరియొద్ద ఖాళీ పాత్రలు అడిగి తెచ్చుకొనుమని ఎలీషాచేత ఆజ్ఞాపింపబడిన తల్లి ఎవరు?",
    medQ: "In 2 Kings 4:2-6, what single remaining item in the widow's house was miraculously multiplied to fill every vessel?",
    medQTe: "2 రాజులు 4:2-6 లో ఆ విధవరాలి ఇంట మిగిలియున్న ఏ చిన్న వస్తువు పాత్రలన్నియు నిండునట్లు అద్భుతముగా విస్తరించెను?",
    hardQ: "What instruction did Elisha give the widow in 2 Kings 4:7 regarding selling the oil and living on the rest?",
    hardQTe: "2 రాజులు 4:7 లో నూనెను అమ్మి అప్పు తీర్చి శేషించినదానితో జీవించుమని ప్రవక్త ఇచ్చిన దైవిక ఆర్థిక విముక్తి ఏది?",
    options: ["A single jar of olive oil", "A handful of parched corn", "A small loaf of fig cake", "Three shekels of brass"],
    optionsTelugu: ["ఒక్క కుండ నూనె మాత్రమే", "ఒక దోసెడు వేయించిన ధాన్యము", "ఒక చిన్న అంజూరపు అడ", "మూడు రాగి షెకెళ్లు"],
    correctAnswer: "A single jar of olive oil",
    bibleReference: "2 Kings 4:1-7",
    explanation: "The widow poured oil into all the borrowed vessels until every jar was filled, delivering her sons from slavery.",
    explanationTelugu: "ఆ కుండ నూనె పాత్రలన్నియు నిండువరకు ఆగలేదు; ఆమె ఆ నూనెను అమ్మి అప్పు తీర్చి కుమారులతో జీవించెను."
  },
  {
    easyQ: "Which aged mother conceived in her old age and gave birth to John the Baptist in Luke 1?",
    easyQTe: "లూకా 1 లో వృద్ధాప్యమందు గర్భము ధరించి బాప్తిస్మమిచ్చు యోహానును కనిన భక్తిగల తల్లి ఎవరు?",
    medQ: "What happened to Elizabeth when Mary's greeting reached her ears in Luke 1:41?",
    medQTe: "లూకా 1:41 లో మరియ వందనము వినగానే ఎలీసబెతు గర్భములో ఏమి జరిగెను?",
    hardQ: "How did Elizabeth, filled with the Holy Spirit, address Mary in Luke 1:42-43 as 'the mother of my Lord'?",
    hardQTe: "లూకా 1:42-43 లో పరిశుద్ధాత్మపూర్ణురాలైన ఎలీసబెతు మరియను 'నా ప్రభువు యొక్క తల్లి' అని సంబోధించుట ఏ క్రీస్తుతాత్పర్యమును చూపుచున్నది?",
    options: ["Elizabeth", "Salome", "Anna", "Joanna"],
    optionsTelugu: ["ఎలీసబెతు", "సలోమే", "అన్నా", "యోహన్నా"],
    correctAnswer: "Elizabeth",
    bibleReference: "Luke 1:5-25, 41-43",
    explanation: "When Elizabeth heard Mary's greeting, the baby leaped in her womb and she was filled with the Holy Spirit.",
    explanationTelugu: "ఎలీసబెతు మరియ వందనము వినగానే గర్భములోని శిశువు గంతులు వేసెను, ఎలీసబెతు పరిశుద్ధాత్మతో నిండి బిగ్గరగా స్తుతించెను."
  },
  {
    easyQ: "Which humble virgin of Nazareth was chosen by God to be the mother of our Savior Jesus Christ?",
    easyQTe: "నజరేతులో మన రక్షకుడైన యేసుక్రీస్తును కనుటకు దేవుని కృప పొందిన ధన్యురాలైన కన్యక ఎవరు?",
    medQ: "What message of divine favor did angel Gabriel speak to Mary in Luke 1:28?",
    medQTe: "లూకా 1:28 లో గబ్రియేలు దూత మరియతో పలికిన దైవిక కృపా వచనమేది?",
    hardQ: "How does Mary's submissive reply: 'Behold the maidservant of the Lord; let it be to me according to your word' model ultimate faith?",
    hardQTe: "'ఇదిగో ప్రభువు దాసురాలను, నీ మాటచొప్పున నాకు జరుగును గాక' అని మరియ పలికిన మాట సంపూర్ణ సమర్పణకు ఎలా మాదిరిగా ఉన్నది?",
    options: ["Mary", "Martha", "Susanna", "Mary Magdalene"],
    optionsTelugu: ["మరియ", "మార్త", "సుసన్న", "మగ్దలేనే మరియ"],
    correctAnswer: "Mary",
    bibleReference: "Luke 1:26-38",
    explanation: "The angel Gabriel declared Mary highly favored, and she submitted her life entirely to God's redemptive will.",
    explanationTelugu: "గబ్రియేలు దూత: దయాప్రాప్తురాలా, నీకు శుభము; ప్రభువు నీకు తోడైయున్నాడని పలికెను."
  }
];

// Combine and generate MotherQuestionBank
const bibDataMother = [
  // 26-50 Foundation
  ["Mary singing the Magnificat declaring all generations will call her blessed", "సమస్త తరములు తన్ను ధన్యురాలని చెప్పుదురని మరియ స్తుతించుట", "Luke 1:46-48", "\"My soul magnifies the Lord, and my spirit has rejoiced in God my Savior\"", "\"నా ప్రాణము ప్రభువును ఘనపరచుచున్నది, నా ఆత్మ నా రక్షకుడైన దేవునియందు ఆనందించెను\"", "Mary rejoiced in God's mercy to the humble.", "మరియ దీనులను హెచ్చించు దేవుని కృపను గూర్చి స్తుతించెను."],
  ["Mary wrapping baby Jesus in swaddling cloths and laying Him in a manger", "శిశువైన యేసును పొత్తిగుడ్డలతో చుట్టి పశువుల తొట్టిలో పరుండబెట్టుట", "Luke 2:7", "She wrapped Him in swaddling cloths and laid Him in a manger", "పొత్తిగుడ్డలతో చుట్టి పశువుల తొట్టిలో పరుండబెట్టెను", "In humble poverty, the Savior of the world was born.", "లోకరక్షకుడు దీనమైన పశువుల తొట్టిలో జన్మించెను."],
  ["Mary treasuring all these things and pondering them in her heart", "ఆ మాటలన్నిటిని మరియ తన హృదయములో భద్రము చేసికొని ధ్యానించుట", "Luke 2:19, 51", "Mary kept all these things and pondered them in her heart", "మరియ ఆ మాటలన్నిటిని తన హృదయములో ఉంచుకొని నిధానము చేసికొనెను", "Maternal meditation on God's mysterious dealings.", "దేవుని మర్మములను హృదయములో ధ్యానించిన భక్తిగల తల్లి."],
  ["Simeon prophesying that a sword will pierce Mary's own soul", "మరియ స్వంత హృదయములోనికి ఒక ఖడ్గము దూసికొనిపోవునని సుమెయోను ప్రవచించుట", "Luke 2:34-35", "\"Yes, a sword will pierce through your own soul also\"", "\"నీ హృదయములోనికి ఒక ఖడ్గము దూసికొనిపోవును\"", "Foreshadowing the sorrow of watching Christ crucified.", "సిలువ శ్రమలను చూచి తల్లిగా ఆమె పడు వేదనను సూచించెను."],
  ["Mary and Joseph searching anxiously for twelve-year-old Jesus in Jerusalem", "పన్నెండేండ్ల యేసుకొరకు యెరూషలేములో తల్లిదండ్రులు ఆందోళనతో వెదకుట", "Luke 2:48", "\"Son, why have You done this to us? Look, Your father and I have sought You anxiously\"", "\"కుమారుడా, మమ్మును ఎందుకు ఈలాగు చేసితివి? నీ తండ్రియు నేనును చింతపడుచు నిన్ను వెదకుచుంటిమి\"", "Jesus reminded them He had to be in His Father's house.", "తాను తన పరలోకపు తండ్రి పనిమీద ఉండవలెనని యేసు తెలిపెను."],
  ["Mary interceding at the wedding in Cana saying 'They have no wine'", "కానా విందులో 'వారికి ద్రాక్షారసము అయిపోయినది' అని మరియ యేసుతో చెప్పుట", "John 2:3", "\"They have no wine\"", "\"వారికి ద్రాక్షారసము అయిపోయినది\"", "Mary brought the family's social crisis to Jesus.", "మరియ ఆ కుటుంబపు కొరతను యేసు యొద్దకు తెచ్చెను."],
  ["Mary commanding the servants at Cana: 'Whatever He says to you, do it'", "కానాలో 'ఆయన మీతో చెప్పునది చేయుడి' అని పరిచారకులకు మరియ ఆజ్ఞాపించుట", "John 2:5", "\"Whatever He says to you, do it\"", "\"ఆయన మీతో చెప్పునది చేయుడి\"", "The ultimate maternal instruction pointing all to Christ.", "యేసు మాటలకు విధేయత చూపవలెనని తల్లిగా ఆమె చేసిన ఉపదేశము."],
  ["Mary standing faithfully at the foot of Jesus' cross on Calvary", "కల్వరి సిలువ పాదము వద్ద నమ్మకముగా నిలిచిన యేసు తల్లియైన మరియ", "John 19:25", "Now there stood by the cross of Jesus His mother", "యేసు సిలువయొద్ద ఆయన తల్లి నిలుచుండెను", "Unwavering maternal love enduring to the very cross.", "సిలువ మరణ సమయమందును విడిచిపోని తల్లి ప్రేమ."],
  ["Jesus entrusting Mary to the beloved disciple John: 'Behold your mother!'", "యోహానుకు మరియను అప్పగించుచు 'ఇదిగో నీ తల్లి' అని యేసు పలుకుట", "John 19:26-27", "\"Behold your mother!\" And from that hour that disciple took her to his own home", "\"ఇదిగో నీ తల్లి! ఆ గడియనుండి ఆ శిష్యుడు ఆమెను తన యింట చేర్చుకొనెను\"", "Honoring and providing for mothers even in death.", "మరణ ఘడియలలో కూడ తల్లిని ఆదరించిన రక్షకుడు."],
  ["Mary persevering in united prayer with the apostles in the Upper Room", "మేడగదిలో అపొస్తలులతో కలిసి ఏకమనస్సుతో మరియ ప్రార్థన చేయుట", "Acts 1:14", "These all continued with one accord in prayer and supplication, with Mary the mother of Jesus", "వీరందరు యేసు తల్లియైన మరియతోను ఏకమనస్సుతో ప్రార్థన చేయుచుండిరి", "Mothers praying fervently for the outpouring of the Holy Spirit.", "పరిశుద్ధాత్మ వర్షము కొరకు ప్రార్థించిన పరిశుద్ధ తల్లి."],
  ["Salome asking Jesus for her two sons James and John to sit on royal thrones", "తన ఇద్దరు కుమారులైన యాకోబు యోహానులకొరకు సింహాసనములను కోరిన సలోమే", "Matthew 20:20-21", "\"Grant that these two sons of mine may sit, one on Your right hand and the other on the left\"", "\"నా యీ యిద్దరు కుమారులు నీ రాజ్యమందు ఒకడు నీ కుడివైపునను ఒకడు నీ యెడమవైపునను కూర్చుండునట్లు సెలవిమ్ము\"", "Mothers praying high spiritual callings for their children.", "కుమారుల ఉన్నత భవిష్యత్తు కొరకు ఆశపడిన తల్లి."],
  ["Lois and Eunice passing sincere faith down to Timothy across generations", "లోయియు యునీకేయు తిమోతికి నిష్కపటమైన విశ్వాసమును నేర్పుట", "2 Timothy 1:5", "\"The genuine faith that is in you, which dwelt first in your grandmother Lois and your mother Eunice\"", "\"నీయందున్న నిష్కపటమైన విశ్వాసము మొదట నీ అవ్వయైన లోయియందును నీ తల్లియైన యునీకేయందును వసించెను\"", "Generational maternal discipleship shaping church leaders.", "తల్లి మరియు అవ్వల ప్రార్థనలు గొప్ప దైవజనుని నిర్మించెను."],
  ["Timothy taught the Holy Scriptures from infancy by his godly mother", "బాల్యమునుండి పవిత్ర లేఖనములను తల్లియొద్ద నేర్చుకొనిన తిమోతి", "2 Timothy 3:14-15", "\"From childhood you have known the Holy Scriptures, which are able to make you wise for salvation\"", "\"క్రీస్తుయేసునందలి విశ్వాసముద్వారా రక్షణార్థమైన జ్ఞానము నీకు కలిగించుటకు శక్తిగల పరిశుద్ధ లేఖనములను బాల్యమునుండి ఎరుగుదువు\"", "Scripture taught at a mother's knee bears eternal fruit.", "తల్లి ఒడిలో నేర్చుకొనిన వాక్యము రక్షణార్థమైన జ్ఞానమునిచ్చును."],
  ["The mother of King Lemuel teaching him royal wisdom and self-control", "లెమూయేలు రాజునకు అతని తల్లి నేర్పిన దైవిక జ్ఞానోపదేశము", "Proverbs 31:1-3", "\"The words of King Lemuel, the utterance which his mother taught him\"", "\"లెమూయేలు రాజు పలికిన దేవోక్తి, అతని తల్లి అతనికి నేర్పిన ఉపదేశము\"", "Mothers shaping national leaders in righteousness and justice.", "రాజులకు నీతిన్యాయములను నేర్పించిన జ్ఞానముగల తల్లి."],
  ["The virtuous mother of Proverbs 31 watching over the ways of her household", "సామెతలు 31 లో తన యింటివారి నడవడిని చక్కగా కనిపెట్టు గుణవతియైన తల్లి", "Proverbs 31:27", "\"She watches over the ways of her household, and does not eat the bread of idleness\"", "\"ఆమె తన యింటివారి నడవడిని బాగుగా కనిపెట్టును, ఆమె సోమరితనమువలన వచ్చు భోజనము చేయదు\"", "Diligent maternal care guarding the family from harm.", "ఇంటివారిని క్షేమముగా కాపాడుకొను సమర్థురాలైన ఇల్లాలు."],
  ["Proverbs 31:28 on children rising up and calling their mother blessed", "సామెతలు 31:28 పిల్లలు లేచి తమ తల్లిని ధన్యురాలని పొగుడుట", "Proverbs 31:28", "\"Her children rise up and call her blessed; her husband also, and he praises her\"", "\"ఆమె పిల్లలు లేచి ఆమెను ధన్యురాలందురు; ఆమె పెనిమిటియు లేచి ఆమెను స్తుతించును\"", "The highest biblical tribute given to a faithful mother.", "భక్తిగల తల్లికి పిల్లలు భర్త చేయు ఉన్నతమైన స్తుతి."],
  ["Jesus using the tender imagery of a mother hen gathering her chicks", "తల్లికోడి తన పిల్లలను రెక్కలక్రింద చేర్చుకొను విధమును యేసు వర్ణించుట", "Matthew 23:37", "\"How often I wanted to gather your children together, as a hen gathers her chicks under her wings\"", "\"కోడి తన పిల్లలను రెక్కలక్రిందికి చేర్చుకొనునట్లు ఎన్నిమారులో నీ పిల్లలను చేర్చుకొనవలెనని ఉంటిని\"", "God's passionate maternal tenderness yearning over His people.", "తల్లికోడివలె కాపాడు దేవుని వాత్సల్య ప్రేమ."],
  ["Psalm 91:4 promising refuge under God's motherly wings and feathers", "కీర్తన 91:4 దేవుని రెక్కలక్రింద మరియు ఈకెలక్రింద ఆశ్రయము పొందుట", "Psalm 91:4", "\"He shall cover you with His feathers, and under His wings you shall take refuge\"", "\"ఆయన తన రెక్కలతో నిన్ను కప్పును, ఆయన రెక్కలక్రింద నీకు ఆశ్రయము కలుగును\"", "Maternal divine sheltering from deadly snares.", "దేవుని రెక్కలచాటున దొరుకు సంపూర్ణ భద్రత."],
  ["Isaiah 49:15 declaring that even if a nursing mother forgets, God will not", "యెషయా 49:15 స్త్రీ తన చనుబాలు త్రాగు బిడ్డను మరచినను దేవుడు మరువడను వాగ్దానము", "Isaiah 49:15", "\"Can a woman forget her nursing child?... Even these may forget, yet I will not forget you\"", "\"స్త్రీ తన చనుబాలు త్రాగు బిడ్డను మరచునా?... వారు మరచినను నేను నిన్ను మరువను\"", "God's love exceeds the deepest maternal bond.", "తల్లి ప్రేమకంటె మిన్నయైన దేవుని శాశ్వత ప్రేమ."],
  ["Isaiah 66:13 promising that God will comfort His people as a mother comforts", "యెషయా 66:13 ఒకని తల్లి వానిని ఆదరించునట్లు దేవుడు ఆదరించునను వాగ్దానము", "Isaiah 66:13", "\"As one whom his mother comforts, so I will comfort you\"", "\"ఒకని తల్లి వానిని ఆదరించునట్లు నేను మిమ్మును ఆదరించెదను\"", "Divine consolation mirroring maternal tenderness.", "తల్లివలె ఆదరించి కన్నీరు తుడచు దేవుని ప్రేమ."],
  ["Rufus' mother who showed maternal love to the apostle Paul in Rome", "రోమాలో పౌలును తన సొంత కుమారునివలె ఆదరించిన రూఫు తల్లి", "Romans 16:13", "\"Greet Rufus, chosen in the Lord, and his mother and mine\"", "\"ప్రభువునందు ఏర్పరచబడిన రూఫునకును, నాకును తల్లియైన అతని తల్లికిని వందనములు\"", "Mothers in the faith extending family love to ministers.", "సువార్త సేవకులకు తల్లివలె నిలిచిన ఆత్మీయ మాతృమూర్తి."],
  ["Isaac being comforted after his mother Sarah's death when he married Rebekah", "శారా మరణము తరువాత రిబ్కాను వివాహము చేసికొని ఇస్సాకు ఓదార్పు పొందుట", "Genesis 24:67", "\"Isaac brought her into his mother Sarah's tent... and Isaac was comforted after his mother's death\"", "\"ఇస్సాకు తన తల్లియైన శారా గుడారములోనికి ఆమెను తీసికొనిపోయెను... ఇస్సాకు తన తల్లి విషయమై దుఃఖనివారణ పొందెను\"", "Deep grief for a deceased mother comforted in holy marriage.", "తల్లి ఎడబాటు దుఃఖమునుండి దేవుడు ఇచ్చిన నెమ్మది."],
  ["Deborah, Rebekah's faithful nurse and mother-figure, buried under Allon-Bakuth", "రిబ్కా దాదియైన దెబోరా మరణించి అల్లోన్ బాకూతు అను ఏడ్పు సింధూరవృక్షము క్రింద పాతిపెట్టబడుట", "Genesis 35:8", "\"Deborah, Rebekah's nurse, died, and was buried below Bethel under the terebinth tree\"", "\"రిబ్కా దాదియైన దెబోరా చనిపోయి బేతేలునకు దిగువగానున్న సింధూరవృక్షము క్రింద పాతిపెట్టబడెను\"", "Honoring faithful maternal caregivers who nurtured patriarchs.", "తరతరములను పెంచి పోషించిన నమ్మకమైన ఆత్మీయ దాది."],
  ["King Solomon standing up to honor his mother Bathsheba with a royal throne", "సొలొమోను రాజు తన తల్లియైన బత్షెబను చూచి లేచి నమస్కరించి సింహాసనము వేయించుట", "1 Kings 2:19", "\"The king rose up to meet her and bowed down to her, and sat down on his throne and had a throne set for the king's mother\"", "\"రాజు ఆమెను ఎదుర్కొనబోయి ఆమెకు నమస్కారము చేసి, తన సింహాసనముమీద కూర్చుండి రాజు తల్లికొరకు ఒక సింహాసనము వేయించెను\"", "Godly rulers honor their mothers with highest reverence.", "రాజులు సైతము తల్లులను గౌరవించి సన్మానించవలెను."],
  ["King Josiah guided in righteousness by his mother Jedidah", "తన తల్లియైన యెదీదా వలన భక్తిమార్గములో నడిపింపబడిన యోషీయా రాజు", "2 Kings 22:1-2", "\"His mother's name was Jedidah... and he did what was right in the sight of the Lord\"", "\"అతని తల్లి పేరు యెదీదా... అతడు యెహోవా దృష్టికి అనుకూలముగా ప్రవర్తించెను\"", "Mothers steering young kings into national revival.", "దేశములో గొప్ప ఆధ్యాత్మిక ఉజ్జీవము తెచ్చిన రాజును పెంచిన తల్లి."]
];

for (let i = 0; i < bibDataMother.length && foundationFacts.length < 50; i++) {
  const item = bibDataMother[i];
  foundationFacts.push({
    easyQ: `What biblical event or truth is recorded concerning ${item[0]}?`,
    easyQTe: `${item[1]} గూర్చి బైబిలులో వ్రాయబడిన లేఖన సత్యమేమి?`,
    medQ: `According to ${item[2]}, what specific detail characterizes this motherly faith?`,
    medQTe: `${item[2]} లేఖనము ప్రకారం ఈ మాతృమూర్తి విశ్వాసములోని వివరమేమి?`,
    hardQ: `What theological lesson does ${item[2]} teach about godly motherhood and divine covenant?`,
    hardQTe: `${item[2]} ప్రకారం దైవిక మాతృత్వము మరియు నిబంధనను గూర్చి విశ్వాసులు గ్రహించవలసిన ఆత్మీయ సత్యమేమి?`,
    options: [item[3], "She led seven thousand cavalry into Syria", "She demanded thirty talents of gold", "She fled to the desert of Paran alone"],
    optionsTelugu: [item[4], "సిరియాపైకి ఏడు వేల అశ్వదళమును నడిపించెను", "ముప్పది తలాంతుల బంగారమును అడిగెను", "పారాను అరణ్యమునకు ఒంటరిగా పారిపోయెను"],
    correctAnswer: item[3],
    bibleReference: item[2],
    explanation: item[5],
    explanationTelugu: item[6]
  });
}

// 50 Growth Facts for Mother (Proverbs & Epistles on maternal guidance)
function buildMotherGrowth() {
  const data = [
    ["Proverbs 1:8 on not forsaking your mother's law", "సామెతలు 1:8 తల్లి ఉపదేశమును త్రోసివేయకుండుట", "Proverbs 1:8", "\"Do not forsake the law of your mother\"", "\"నీ తల్లి ఉపదేశమును త్రోసివేయకుము\"", "A mother's godly instruction forms an ornament of grace around the neck.", "తల్లి నేర్పిన దైవిక ఉపదేశమును పిల్లలు ఎన్నడును విడవకూడదు."],
    ["Proverbs 6:20 on binding mother's teaching continually upon the heart", "సామెతలు 6:20 తల్లి బోధను నిత్యము హృదయమున ధరించుట", "Proverbs 6:20-22", "\"Do not forsake the law of your mother. Bind them continually upon your heart\"", "\"నీ తల్లి బోధను త్రోసివేయకుము, వాటిని ఎల్లప్పుడు నీ హృదయమున కట్టుకొనుము\"", "Motherly biblical guidance leads when walking and protects when sleeping.", "తల్లి నేర్పిన వాక్యము మనలను నిత్యము నడిపించి కాపాడును."],
    ["Proverbs 10:1 on a foolish child bringing sorrow to his mother", "సామెతలు 10:1 బుద్ధిహీనుడైన కుమారుడు తల్లికి దుఃఖము తెచ్చుట", "Proverbs 10:1", "\"A foolish son is the grief of his mother\"", "\"బుద్ధిహీనుడైన కుమారుడు తన తల్లికి దుఃఖము తెచ్చును\"", "Unrighteous living pierces a mother's heart with deep sorrow.", "బుద్ధిహీనమైన ప్రవర్తన తల్లి హృదయమునకు తీవ్ర వేదనను కలుగజేయును."],
    ["Proverbs 15:20 on a foolish man despising his mother", "సామెతలు 15:20 బుద్ధిహీనుడు తల్లిని తృణీకరించుట", "Proverbs 15:20", "\"A foolish man despises his mother\"", "\"బుద్ధిహీనుడు తన తల్లిని తృణీకరించును\"", "Spiritual foolishness is revealed when children disdain maternal love.", "తల్లి ప్రేమను అలక్ష్యము చేయువాడు అజ్ఞానియని బైబిలు హెచ్చరించుచున్నది."],
    ["Proverbs 17:25 on a rebellious child being bitterness to her who bore him", "సామెతలు 17:25 మూర్ఖుడైన కుమారుడు తన్న కనిన తల్లికి చేదై యుండుట", "Proverbs 17:25", "\"A foolish son is a grief to his father, and bitterness to her who bore him\"", "\"బుద్ధిహీనుడైన కుమారుడు తన తండ్రికి దుఃఖమును తన్న కనిన తల్లికి చేదునై యున్నాడు\"", "Mothers suffer acute emotional grief from disobedient children.", "అవిధేయుడైన బిడ్డ తన్న కనిన తల్లికి తీవ్ర మనోవేదనగా మారును."],
    ["Proverbs 19:26 on chasing away one's mother bringing disgrace", "సామెతలు 19:26 తల్లిని వెళ్లగొట్టువాడు సిగ్గు తెచ్చుట", "Proverbs 19:26", "\"He who mistreats his father and chases away his mother is a son who causes shame\"", "\"తండ్రిని హింసించి తల్లిని వెళ్లగొట్టువాడు సిగ్గును అవమానమును తెచ్చు కుమారుడు\"", "Scripture severely condemns neglecting or abusing aging parents.", "వృద్ధాప్యమందు తల్లిదండ్రులను నిరాకరించుట దేవుని దృష్టిలో ఘోర పాపము."],
    ["Proverbs 20:20 on cursing one's mother leading to darkness", "సామెతలు 20:20 తల్లిని శపించువాని దీపము ఆరిపోవునను హెచ్చరిక", "Proverbs 20:20", "\"Whoever curses his father or his mother, his lamp will be put out in deep darkness\"", "\"తన తండ్రినైనను తల్లి నైనను శపించువాని దీపము కారుచీకటిలో ఆరిపోవును\"", "Disrespecting mothers extinguishes spiritual light and brings divine judgment.", "తల్లిని దూషించువాని జీవితము కారుచీకటిలో ముగియునని సామెతలు హెచ్చరించుచున్నది."],
    ["Proverbs 23:22 on not despising your mother when she is old", "సామెతలు 23:22 తల్లి వృద్ధురాలైనప్పుడు ఆమెను తృణీకరించకుండుట", "Proverbs 23:22", "\"Do not despise your mother when she is old\"", "\"నీ తల్లి ముసలిదైనప్పుడు ఆమెను తృణీకరింపకుము\"", "Aging mothers deserve honor, care, and continuous gratitude.", "వృద్ధురాలైన తల్లిని ఎల్లప్పుడు ప్రేమించి గౌరవించవలెను."],
    ["Proverbs 23:25 on bringing joy to the mother who gave you birth", "సామెతలు 23:25 నిన్ను కనిన తల్లిని సంతోషపెట్టుము", "Proverbs 23:25", "\"Let your father and your mother be glad, and let her who bore you rejoice\"", "\"నీ తండ్రిని నీ తల్లిని సంతోషపెట్టుము, నిన్ను కనిన తల్లిని ఆనందింపజేయుము\"", "Righteous living is the greatest gift children give to their mother.", "నీతిగా జీవించుటయే తల్లికి బిడ్డలు ఇవ్వగల పరమోన్నత బహుమతి."],
    ["Proverbs 29:15 on a child left undisciplined bringing shame to his mother", "సామెతలు 29:15 ఇష్టమువచ్చినట్లు తిరుగు బాలుడు తల్లికి అవమానము తెచ్చుట", "Proverbs 29:15", "\"A child left to himself brings shame to his mother\"", "\"ఇష్టమువచ్చినట్లు తిరుగనిచ్చిన బాలుడు తన తల్లికి అవమానము తెచ్చును\"", "Biblical discipline is essential to protect children and honor mothers.", "క్రమశిక్షణ లేని పెంపకము తల్లికి అవమానమును తెచ్చును."],
    ["Exodus 20:12 on the fifth commandment: Honor your father and your mother", "నిర్గమకాండము 20:12 ఐదవ ఆజ్ఞ: నీ తండ్రిని నీ తల్లిని సన్మానించుము", "Exodus 20:12", "\"Honor your father and your mother, that your days may be long\"", "\"నీ దేవుడైన యెహోవా నీకిచ్చు దేశములో నీవు దీర్ఘాయుష్మంతుడవగునట్లు నీ తండ్రిని నీ తల్లిని సన్మానించుము\"", "Honoring mothers carries the promised blessing of long life and well-being.", "తల్లిదండ్రులను సన్మానించినప్పుడు దీర్ఘాయుష్షు లభించును."],
    ["Leviticus 19:3 commanding reverence for every mother and father", "లేవీయకాండము 19:3 మీలో ప్రతివాడును తన తల్లికిని తండ్రికిని భయపడవలెనను ఆజ్ఞ", "Leviticus 19:3", "\"Every one of you shall revere his mother and his father, and keep My Sabbaths\"", "\"మీలో ప్రతివాడును తన తల్లికిని తన తండ్రికిని భయపడవలెను, నేను నియమించిన విశ్రాంతిదినములను ఆచరింపవలెను\"", "Reverence for mothers is linked directly to keeping God's holy Sabbaths.", "తల్లిదండ్రులను గౌరవించుట దేవుని భయభక్తులతో సమానముగా చెప్పబడెను."],
    ["Deuteronomy 27:16 on curses falling upon anyone who dishonors his mother", "ద్వితీయోపదేశకాండము 27:16 తన తల్లిని అవమానపరచువాడు శాపగ్రస్తుడగును", "Deuteronomy 27:16", "\"Cursed is the one who treats his father or his mother with contempt\"", "\"తన తండ్రినైనను తల్లి నైనను అవమానపరచువాడు శాపగ్రస్తుడు\"", "Divine law places solemn protection around parental dignity.", "తల్లిని తృణీకరించువాడు దేవుని శాపమును మూటగట్టుకొనును."],
    ["Ruth 1:16 on Ruth embracing Naomi as her true spiritual mother", "రూతు 1:16 నయోమిని తన ఆత్మీయ తల్లిగా రూతు హత్తుకొనుట", "Ruth 1:16", "\"Where you die I will die, and there will I be buried\"", "\"నీవు మరణించుచోటనే నేనును మరణించెదను, అక్కడనే పాతిపెట్టబడెదను\"", "Daughter-in-law demonstrating covenant fidelity to her mother-in-law.", "కోడలు అత్తగారిని తల్లివలె ప్రాణముకంటె ఎక్కువగా ప్రేమించెను."],
    ["Ruth 4:14 on Naomi blessed with a redeemer in her old age", "రూతు 4:14 వృద్ధాప్యములో నయోమి విమోచకుని పొంది ధన్యురాలగుట", "Ruth 4:14", "\"Blessed be the Lord, who has not left you this day without a close relative!\"", "\"ఈ దినమున విమోచకుడు లేకుండా నిన్ను విడువని యెహోవా స్తుతింపబడును గాక!\"", "God restored joy and fullness to the once-bitter, empty mother.", "ఒకప్పుడు రిక్తురాలై పోయిన నయోమి ఒడిని దేవుడు ఆశీర్వాదముతో నింపెను."],
    ["Job 1:21 acknowledging God's sovereignty from mother's womb to the grave", "యోబు 1:21 తల్లి గర్భమునుండి వచ్చుట మరియు వెళ్ళుట దేవుని చేతిలో ఉన్నదనుట", "Job 1:21", "\"Naked I came from my mother's womb, and naked shall I return there\"", "\"నా తల్లి గర్భములోనుండి నేను దిగంబరినై వచ్చితిని, దిగంబరినై అక్కడికి తిరిగి వెళ్లెదను\"", "The womb is the sacred origin of all mortal human existence.", "తల్లి గర్భమునుండి బయలుదేరిన నరుడు దేవుని సర్వాధికారమును ఒప్పుకొనవలెను."],
    ["Psalm 22:9 on God causing the infant to trust even at mother's breast", "కీర్తన 22:9 తల్లి స్తన్యమునొద్దనుండి దేవునియందు నమ్మిక కలిగియుండుట", "Psalm 22:9-10", "\"You made me trust while on my mother's breasts. I was cast upon You from birth\"", "\"నా తల్లి స్తన్యమునొద్ద నేనుండినప్పుడే నీవు నాకు నమ్మిక పుట్టించితివి; గర్భమునుండి పడినది మొదలుకొని నేనే నీమీద వేయబడితిని\"", "Maternal nurturing lays early spiritual foundations for trust in God.", "తల్లి ఒడిలోనే బిడ్డ దేవునిపై నమ్మిక కలిగియుండుటకు పునాది పడును."],
    ["Psalm 27:10 on the Lord taking us up when father and mother forsake us", "కీర్తన 27:10 తల్లిదండ్రులు విడిచినను యెహోవా చేర్చుకొనునను నిరీక్షణ", "Psalm 27:10", "\"When my father and my mother forsake me, then the Lord will take care of me\"", "\"నా తండ్రియు నా తల్లియు నన్ను విడిచినను యెహోవా నన్ను చేర్చుకొనును\"", "God's unconditional love surpasses even the deepest parental care.", "భూమిపై తల్లిదండ్రులు విడిచిపోయినను పరలోకపు తండ్రి మనలను హత్తుకొనును."],
    ["Psalm 113:9 on God settling the childless woman as a joyful mother of children", "కీర్తన 113:9 గొడ్రాలిని పిల్లల తల్లిగా చేసి దేవుడు ఇంట నివసింపజేయుట", "Psalm 113:9", "\"He grants the barren woman a home, like a joyful mother of children. Praise the Lord!\"", "\"ఆయన గొడ్రాలిని ఇంట కాపురముంచి, పిల్లల తల్లిగా సంతోషించునట్లు చేయును. యెహోవాను స్తుతించుడి!\"", "God's redemptive power turns barren grief into jubilant motherhood.", "దేవుడు గొడ్రాలిని కనికరించి ఆనందముగల పిల్లల తల్లిగా మార్చును."],
    ["Psalm 131:2 on quieting one's soul like a weaned child with its mother", "కీర్తన 131:2 చనుబాలు విడిచిన బిడ్డ తన తల్లియొద్ద ఉన్నట్లు నెమ్మది నొందుట", "Psalm 131:2", "\"Surely I have calmed and quieted my soul, like a weaned child with his mother\"", "\"నిశ్చయముగా చనుబాలు విడిచిన బిడ్డ తన తల్లియొద్ద ఉన్నట్లు నేను నా ప్రాణమును ఉపశమింపజేసి నెమ్మదిపరచియున్నాను\"", "Maternal peace illustrates the calm soul resting completely in God.", "తల్లి ఒడిలో చనుబాలు విడిచిన బిడ్డవలె దేవునియందు నెమ్మది పొందుట."],
    ["Psalm 139:13 on God knitting us together in our mother's womb", "కీర్తన 139:13 తల్లి గర్భమందు మనలను దేవుడు విచిత్రముగా అల్లుట", "Psalm 139:13-14", "\"For You formed my inward parts; You covered (knitted) me in my mother's womb\"", "\"నా అంతరింద్రియములను నీవే కలుగజేసితివి, నా తల్లి గర్భమందు నన్ను నిర్మించినవాడవు నీవే\"", "The sanctity of human life formed miraculously in the maternal womb.", "తల్లి గర్భములో ప్రతి ప్రాణమును దేవుడే అత్యంత అద్భుతముగా నిర్మించుచున్నాడు."],
    ["Jeremiah 1:5 on God knowing and sanctifying Jeremiah before birth", "యిర్మీయా 1:5 తల్లి గర్భములో పుట్టకమునుపే దేవుడు యిర్మీయాను ప్రతిష్ఠించుట", "Jeremiah 1:5", "\"Before I formed you in the womb I knew you; before you were born I sanctified you\"", "\"గర్భములో నేను నిన్ను రూపించకమునుపే నిన్ను ఎరిగితిని, నీవు గర్భమునుండి బయలుపడకమునుపే నిన్ను ప్రతిష్ఠించితిని\"", "God's divine call rests upon children from their mother's womb.", "తల్లి గర్భములో రూపింపబడకమునుపే దేవుని ప్రవచన పిలుపు ఉన్నది."],
    ["Ezekiel 16:44 on the proverb 'Like mother, like daughter'", "యెహెజ్కేలు 16:44 'తల్లి ఎట్టిదో కుమార్తె అట్టిదే' అను సామెత", "Ezekiel 16:44", "\"Indeed everyone who quotes proverbs will use this proverb against you: 'Like mother, like daughter!'\"", "\"సామెతలు చెప్పు ప్రతివాడును-తల్లి ఎట్టిదో కుమార్తె అట్టిదే అని నిన్నుగూర్చి సామెత చెప్పును\"", "Mothers profoundly influence the spiritual trajectory of their daughters.", "తల్లి గుణగణములు సహజముగా కుమార్తెల ప్రవర్తనను ప్రభావితము చేయును."],
    ["Matthew 10:37 on loving Christ supremely above mother and father", "మత్తయి 10:37 తల్లిదండ్రులకంటె క్రీస్తును ఎక్కువగా ప్రేమించవలెనను ఆజ్ఞ", "Matthew 10:37", "\"He who loves father or mother more than Me is not worthy of Me\"", "\"నాకంటె ఎక్కువగా తన తండ్రినైనను తల్లినైనను ప్రేమించువాడు నాకు పాత్రుడు కాడు\"", "Christ demands the first place in our hearts above all earthly ties.", "తల్లిదండ్రులకంటె ఎక్కువగా క్రీస్తుకు ప్రథమ స్థానము ఇవ్వవలెను."],
    ["Matthew 12:49-50 on spiritual mothers who do the Father's will", "మత్తయి 12:49-50 పరలోకపు తండ్రి చిత్తము చేయువారే తనకు తల్లి సహోదరులని యేసు చెప్పుట", "Matthew 12:49-50", "\"Whoever does the will of My Father in heaven is My brother and sister and mother\"", "\"పరలోకమందున్న నా తండ్రి చిత్తము చొప్పున చేయువాడే నా సహోదరుడును నా సహోదరియు నా తల్లియునై యున్నాడు\"", "Obedience to God forms an eternal, spiritual family bond with Jesus.", "దేవుని వాక్యమునకు విధేయత చూపువారే క్రీస్తుకు ఆత్మీయ తల్లియు సహోదరులు."],
    ["Matthew 15:4-6 rebuking the Pharisees for neglecting mothers through religious tradition", "మత్తయి 15:4-6 దేవద్రవ్య సాకుతో తల్లిని పోషింపకపోవుటను యేసు గద్దించుట", "Matthew 15:4-6", "\"Honor your father and your mother... but you say 'It is Korban (a gift to God)' and relieve him of caring for mother\"", "\"నీ తండ్రిని తల్లిని సన్మానించుమని దేవుడు ఆజ్ఞాపించెను; మీరైతే దేవార్పితమని చెప్పి తల్లిని పోషింపకుండ చేయుచున్నారు\"", "Jesus condemned hypocrisy that neglects financial support for elderly mothers.", "భక్తి పేరుతో వృద్ధ తల్లుల పోషణను విడిచిపెట్టుట వేషధారణయని యేసు ఖండించెను."],
    ["Luke 7:12-15 on Jesus having compassion on the weeping widow of Nain", "లూకా 7:12-15 నాయీను విధవరాలి రోదనను చూచి యేసు కనికరపడుట", "Luke 7:13-15", "\"When the Lord saw her, He had compassion on her and said to her, 'Do not weep'\"", "\"ప్రభువు ఆమెను చూచి ఆమెయందు కనికరపడి-ఏడవవద్దని ఆమెతో చెప్పెను\"", "Jesus raised the widow's only son and returned him alive to his mother.", "యేసు చనిపోయిన బాలుని లేపి ఆ విలపించుచున్న తల్లికి అప్పగించెను."],
    ["Luke 11:27-28 on hearing and obeying God's word being greater than physical motherhood", "లూకా 11:27-28 నిన్ను మోసిన గర్భము ధన్యమనిన స్త్రీతో దేవుని వాక్యము గైకొనువారే ధన్యులని యేసు చెప్పుట", "Luke 11:27-28", "\"More than that, blessed are those who hear the word of God and keep it!\"", "\"అవును గాని దేవుని వాక్యము విని దానిని గైకొనువారే మరి ధన్యులని చెప్పెను\"", "Spiritual obedience to Scripture surpasses even physical biological motherhood.", "దేవుని వాక్యమును విని పాటించుటయే అత్యున్నతమైన ఆత్మీయ ధన్యత."],
    ["John 16:21 on the mother forgetting her labor pains for joy that a child is born", "యోహాను 16:21 బిడ్డ పుట్టగానే ప్రసవవేదన మరచి ఆనందించు తల్లి", "John 16:21", "\"As soon as she has given birth to the child, she no longer remembers the anguish, for joy that a human being has been born\"", "\"పిల్ల కనగానే లోకమందు ఒక మనుష్యుడు పుట్టెనను సంతోషమువలన ఆమె ఆ వేదన మరి ఎన్నడును జ్ఞాపకము చేసికొనదు\"", "Maternal birth pains illustrate the transition from earthly sorrow to kingdom joy.", "ప్రసవవేదన తరువాత కలుగు ఆనందము క్రీస్తు పునరుత్థాన సంతోషమును సూచించుచున్నది."],
    ["Galatians 4:26 on the heavenly Jerusalem who is the spiritual mother of us all", "గలతీయులకు 4:26 పైనున్న యెరూషలేము మనకందరికిని తల్లియై యున్నదను సత్యము", "Galatians 4:26", "\"The Jerusalem above is free, which is the mother of us all\"", "\"పైనున్న యెరూషలేము స్వతంత్రురాలు, ఆమె మనకందరికిని తల్లి\"", "The heavenly city of the new covenant is the spiritual mother of all believers.", "పరలోకపు యెరూషలేము క్రైస్తవులందరికీ ఆత్మీయ తల్లియై యున్నది."],
    ["1 Timothy 5:2 on treating older women with the tender respect due to mothers", "1 తిమోతి 5:2 సంఘములోని వృద్ధ స్త్రీలను తల్లులుగా భావించి సన్మానించుట", "1 Timothy 5:2", "\"Exhort the older women as mothers, the younger women as sisters, with all purity\"", "\"వృద్ధ స్త్రీలను తల్లులనియు, యౌవన స్త్రీలను పూర్ణ పవిత్రతతో సహోదరీలనియు హెచ్చరించుము\"", "Pastoral etiquette honors senior godly women as spiritual mothers in the church.", "సంఘములో పెద్దవారైన స్త్రీలను స్వంత తల్లులవలె అత్యంత గౌరవముతో చూడవలెను."],
    ["2 Timothy 1:5 commending grandmother Lois for nurturing faith alongside mother Eunice", "2 తిమోతి 1:5 అవ్వయైన లోయి మరియు తల్లియైన యునీకేల విశ్వాస వారసత్వము", "2 Timothy 1:5", "\"Which dwelt first in your grandmother Lois and your mother Eunice, and I am persuaded is in you also\"", "\"ఆ విశ్వాసము మొదట నీ అవ్వయైన లోయియందును నీ తల్లియైన యునీకేయందును వసించెను, అది నీయందును ఉన్నదని నేను రూఢిగా నమ్ముచున్నాను\"", "A united grandmother and mother model victorious intergenerational discipleship.", "అవ్వ మరియు తల్లుల విశ్వాస ప్రార్థనలు బలమైన దైవజనులను నిర్మించును."],
    ["Song of Songs 3:11 on King Solomon crowned by his mother on his wedding day", "పరమగీతము 3:11 పెండ్లి దినమున సొలొమోనుకు అతని తల్లి పెట్టిన కిరీటము", "Song of Songs 3:11", "\"King Solomon with the crown with which his mother crowned him on the day of his wedding\"", "\"సొలొమోనునకు అతని తల్లి పెట్టిన కిరీటమును చూడుడి, అది అతని పెండ్లి దినమున పెట్టిన కిరీటము\"", "Mothers bless the marital covenant and joy of their children.", "వివాహ శుభదినమున కుమారుని ఆశీర్వదించి కిరీటము ధరింపజేయు తల్లి."],
    ["Isaiah 66:12 on being nursed and carried upon a mother's side", "యెషయా 66:12 తల్లి చంకన ఎత్తికొనబడి ఒడిలో లాలించబడుట", "Isaiah 66:12-13", "\"You shall feed; on her sides shall you be carried, and be dandled on her knees\"", "\"మీరు చంకన ఎత్తికొనబడెదరు, ఆమె ఒడిలో ముద్దులాడించబడెదరు\"", "Prophetic metaphor of God lovingly carrying His redeemed people.", "దేవుడు తల్లివలె తన బిడ్డలను చంకనెత్తుకొని ఒడిలో లాలించును."],
    ["Zechariah 12:10 on mourning for an only child as a mother weeps", "జెకర్యా 12:10 ఒక్కడేయైన కుమారునికొరకు తల్లి రోదించు విధము", "Zechariah 12:10", "\"They will mourn for Him as one mourns for his only son, and grieve bitterly as for a firstborn\"", "\"ఒక్కడైయున్న కుమారునికొరకు ప్రలాపించునట్లు అతనికొరకు ప్రలాపించుదురు, జ్యేష్ఠపుత్రునికొరకు దుఃఖించునట్లు అతనికొరకు దుఃఖింతురు\"", "Deepest human sorrow is mirrored in a mother weeping for her only child.", "ఏకైక కుమారునికొరకు తల్లి పడు విలాపము మెస్సీయ సిలువ వేదనను చూపుచున్నది."],
    ["Luke 2:35 on the sword piercing Mary's heart as Jesus accomplished redemption", "లూకా 2:35 రక్షణ కార్యము నెరవేరుచుండగా మరియ హృదయమును దూసికొనిపోయిన ఖడ్గము", "Luke 2:35", "\"A sword will pierce through your own soul also, that the thoughts of many hearts may be revealed\"", "\"అనేకుల హృదయాలోచనలు బయలుపడునట్లు నీ హృదయములోనికి ఒక ఖడ్గము దూసికొనిపోవును\"", "Mary's maternal grief intertwined with the cost of world redemption.", "రక్షకుని సిలువ శ్రమలను చూచిన తల్లి హృదయ వేదన."],
    ["Revelation 12:1-2 describing the woman clothed with the sun crying out in labor", "ప్రకటన 12:1-2 సూర్యుని ధరించుకొని ప్రసవవేదనతో కేకలు వేయు స్త్రీ దర్శనము", "Revelation 12:1-2", "\"She was pregnant and was crying out in birth pains and the agony of giving birth\"", "\"ఆమె గర్భవతియై ప్రసవవేదనపడుచు నొప్పులకు కేకలు వేయుచుండెను\"", "Apocalyptic image of God's covenant people bringing forth the Messiah.", "మెస్సీయను కనిన దేవుని నిబంధన ప్రజల ప్రసవవేదన."],
    ["Revelation 12:5 on the male Child caught up to God and His throne", "ప్రకటన 12:5 సమస్త జనములను ఏలు మగశిశువు దేవుని సింహాసనమునొద్దకు కొనిపోబడుట", "Revelation 12:5", "\"She bore a male Child who was to rule all nations with a rod of iron. And her Child was caught up to God\"", "\"సమస్త జనములను ఇనుపదండముతో ఏలబోవు ఒక మగశిశువును ఆమె కనెను; ఆమె శిశువు దేవునియొద్దకును ఆయన సింహాసనమునొద్దకును కొనిపోబడెను\"", "Christ victorious over the dragon to rule all nations.", "సాతాను కుతంత్రములను జయించి సింహాసనమెక్కిన మెస్సీయ కుమారుడు."],
    ["Solomon declaring 'She is his mother' when the true mother chose her child's life", "నిజమైన తల్లి బిడ్డ ప్రాణమును కోరినప్పుడు 'ఆమెయే దీని తల్లి' అని సొలొమోను తీర్పు తీర్చుట", "1 Kings 3:27", "\"Give her the living child, and by no means kill him; she is his mother\"", "\"ఆమెయే దీని తల్లి, దీనిని చంపక ఆమెకే ఇప్పింపుడని రాజు తీర్పు తీర్చెను\"", "True motherly love preserves life at all costs.", "బిడ్డ ప్రాణమును కాపాడుటయే నిజమైన తల్లి ప్రేమ."],
    ["The Shunammite mother falling at Elisha's feet in reverence as her son revived", "కుమారుడు బ్రదికినప్పుడు షూనేమీయ తల్లి ఎలీషా పాదములయొద్ద సాగిలపడుట", "2 Kings 4:37", "\"She fell at his feet, and bowed to the ground; then she took up her son and went out\"", "\"ఆమె వచ్చి అతని కాళ్లమీద పడి నేలమట్టుకు సాగిలపడి, తన కుమారుని ఎత్తికొని పోయెను\"", "Humble gratitude after witnessing resurrection power.", "దేవుడు బిడ్డను బ్రతికించినప్పుడు కృతజ్ఞతతో సాగిలపడిన తల్లి."],
    ["The infant in Elizabeth's womb leaping with joy when hearing Mary's greeting", "మరియ వందనము వినగానే ఎలీసబెతు గర్భములోని శిశువు గంతులు వేయుట", "Luke 1:41", "\"The babe leaped in her womb; and Elizabeth was filled with the Holy Spirit\"", "\"ఎలీసబెతు గర్భములోని శిశువు గంతులు వేసెను, ఎలీసబెతు పరిశుద్ధాత్మతో నిండినదాయెను\"", "Spiritual discernment in pregnant mothers.", "గర్భస్థ శిశువు రక్షకుని రాకడను గుర్తించిన ఆత్మీయ ఆనందము."],
    ["Elizabeth blessing Mary as the most blessed among women", "స్త్రీలలో మరియ ఆశీర్వదింపబడినదని ఎలీసబెతు బిగ్గరగా స్తుతించుట", "Luke 1:42", "\"Blessed are you among women, and blessed is the fruit of your womb!\"", "\"స్త్రీలలో నీవు ఆశీర్వదింపబడినదానవు, నీ గర్భఫలమును ఆశీర్వదింపబడినది!\"", "Elizabeth honoring Mary's divine calling.", "రక్షకుని మోయుచున్న మరియను ఎలీసబెతు ఘనపరచెను."],
    ["Elizabeth humbly wondering why the mother of her Lord would visit her", "నా ప్రభువు తల్లి నా యొద్దకు వచ్చుటకు నేనెంతటిదాననని ఎలీసబెతు వినయము చూపుట", "Luke 1:43", "\"Why is this granted to me, that the mother of my Lord should come to me?\"", "\"నా ప్రభువుయొక్క తల్లి నాయొద్దకు వచ్చుట నాకు ఏలాగు కలిగెను?\"", "Humble maternal communion in the presence of Christ.", "తనకంటె చిన్నదైన మరియను ప్రభువు తల్లిగా గౌరవించిన ఎలీసబెతు."],
    ["Prophetess Anna speaking of the holy Child to all who looked for redemption", "రక్షణకొరకు కనిపెట్టువారందరితో ఆ చిన్నవానిని గూర్చి అన్నా ప్రవక్త్రి మాటలాడుట", "Luke 2:38", "\"She gave thanks to the Lord, and spoke of Him to all those who looked for redemption\"", "\"ఆమె దేవుని కొనియాడుచు, యెరూషలేములో విమోచనకొరకు కనిపెట్టుచున్నవారందరితో ఆయననుగూర్చి మాటలాడుచుండెను\"", "Spiritual matriarch witnessing the Messiah.", "యెరూషలేములో రక్షణ కొరకు కనిపెట్టిన దైవభక్తిగల వృద్ధురాలు."],
    ["The angel warning Joseph in a dream to take the Child and His mother into Egypt", "పిల్లవానిని ఆయన తల్లిని తీసికొని ఐగుప్తునకు పారిపొమ్మని దేవదూత హెచ్చరించుట", "Matthew 2:13", "\"Arise, take the young Child and His mother, flee to Egypt\"", "\"నీవు లేచి ఆ చిన్నవానిని ఆయన తల్లిని తీసికొని ఐగుప్తునకు పారిపొమ్ము\"", "God protecting the Holy Family from Herod's wrath.", "హేరోదు బారినుండి తల్లిని బిడ్డను కాపాడిన దైవిక నడిపింపు."],
    ["Joseph rising by night to escort the young Child and His mother to safety", "యోసేపు రాత్రివేళ లేచి ఆ చిన్నవానిని ఆయన తల్లిని తీసికొని ఐగుప్తునకు వెళ్ళుట", "Matthew 2:14", "\"When he arose, he took the young Child and His mother by night and departed for Egypt\"", "\"అతడు లేచి, రాత్రివేళ ఆ చిన్నవానిని ఆయన తల్లిని తోడుకొని ఐగుప్తునకు వెళ్లిపోయెను\"", "Faithful obedience protecting the vulnerable mother and child.", "తల్లిని బిడ్డను క్షేమముగా కాపాడిన నీతిమంతుడైన యోసేపు."],
    ["The angel commanding Joseph to bring the Child and His mother back to Israel", "ఆ చిన్నవానిని ఆయన తల్లిని తీసికొని ఇశ్రాయేలు దేశమునకు రమ్మని దూత చెప్పుట", "Matthew 2:20", "\"Arise, take the young Child and His mother, and go to the land of Israel\"", "\"నీవు లేచి ఆ చిన్నవానిని ఆయన తల్లిని తోడుకొని ఇశ్రాయేలు దేశమునకు వెళ్లుము\"", "Divine restoration after Herod's death.", "హేరోదు చనిపోయిన తరువాత తల్లితో సహా స్వదేశమునకు రప్పించుట."],
    ["Mary's simple advice to the servants at Cana: 'Whatever He says, do it'", "కానాలో 'ఆయన మీతో చెప్పునది చేయుడి' అని మరియ పరిచారకులకు చెప్పిన మాట", "John 2:5", "\"Whatever He says to you, do it\"", "\"ఆయన మీతో చెప్పునది చేయుడి అని పరిచారకులతో చెప్పెను\"", "Guiding everyone directly into obedience to Jesus.", "యేసు మాటను తు.చ. తప్పక పాటించుమని తల్లిగా చేసిన హెచ్చరిక."],
    ["The beloved disciple John taking Jesus' mother Mary into his own home", "యోహాను యేసు తల్లియైన మరియను ఆ గడియనుండి తన స్వంత యింట చేర్చుకొనుట", "John 19:27", "\"From that hour that disciple took her to his own home\"", "\"ఆ గడియనుండి ఆ శిష్యుడు ఆమెను తన యింట చేర్చుకొనెను\"", "Fulfilling filial duty toward a grieving mother.", "సిలువ పాదము వద్ద విలపించిన తల్లిని తన యింట చేర్చుకొనిన శిష్యుడు."],
    ["Mary united in fervent prayer with the apostles before Pentecost", "పెంతెకొస్తు పండుగకు ముందు మరియ అపొస్తలులతో కలిసి ఏకమనస్సుతో ప్రార్థించుట", "Acts 1:14", "\"These all continued with one accord in prayer, with Mary the mother of Jesus\"", "\"వీరందరు యేసు తల్లియైన మరియతోను ఏకమనస్సుతో ప్రార్థన చేయుచుండిరి\"", "The mother of Jesus standing as an elder intercessor in the early church.", "ఆదిమ సంఘములో ప్రార్థనా వీరురాలిగా నిలిచిన యేసు తల్లి."]
  ];

  return data.map((item, idx) => ({
    easyQ: `What teaching or promise is given regarding ${item[0]}?`,
    easyQTe: `${item[1]} గూర్చి బైబిలులో ఇవ్వబడిన బోధ లేదా వాగ్దానమేమి?`,
    medQ: `According to ${item[2]}, what specific instruction guides children honoring their mother?`,
    medQTe: `${item[2]} లేఖనము ప్రకారం తల్లిని సన్మానించు విషయములో బిడ్డలకు ఇవ్వబడిన ఆజ్ఞ ఏది?`,
    hardQ: `What theological truth does ${item[2]} reveal about maternal honor and divine blessing?`,
    hardQTe: `${item[2]} ప్రకారం తల్లిని గౌరవించుట వలన దేవునినుండి లభించు ఆత్మీయ ఆశీర్వాదమేమి?`,
    options: [item[3], "To depart to the mountains of Edom", "To acquire thirty golden talents", "To forsake the assembly of the saints"],
    optionsTelugu: [item[4], "ఎదోము కొండలలోనికి వెళ్లిపోవుట", "ముప్పది బంగారు తలాంతులను సంపాదించుట", "పరిశుద్ధుల సహవాసమును విడిచిపెట్టుట"],
    correctAnswer: item[3],
    bibleReference: item[2],
    explanation: item[5],
    explanationTelugu: item[6]
  }));
}

// 50 Mastery Facts for Mother (Genealogical, theological, Old/New Testament exegesis)
function buildMotherMastery() {
  const data = [
    ["Genesis 3:15 on the seed of the woman crushing the serpent's head", "ఆదికాండము 3:15 స్త్రీ సంతానము సర్పము తలను చితకద్రొక్కునను ఆదిసువార్త", "Genesis 3:15", "\"He shall bruise your head, and you shall bruise His heel\"", "\"ఆమె సంతానము నీ తలను చితకద్రొక్కును, నీవు ఆయన మడమను చితకద్రొక్కుదువు\"", "The Protoevangelium: Christ born of woman to defeat Satan.", "స్త్రీ సంతానమైన క్రీస్తు సాతాను తలను సిలువలో చితకద్రొక్కెను."],
    ["Genesis 4:1 on Eve rejoicing at Cain's birth: 'I have acquired a man from the Lord'", "ఆదికాండము 4:1 కయీను పుట్టినప్పుడు హవ్వ యెహోవా దయవలన మగపిల్లను సంపాదించితిననుట", "Genesis 4:1", "\"I have acquired a man from the Lord\"", "\"యెహోవా దయవలన నేను ఒక మనుష్యుని సంపాదించుకొంటిని\"", "Eve recognizing God as the source of new human life.", "సమస్త ప్రాణము దేవుని దయవలననే కలుగుచున్నదని హవ్వ గ్రహించెను."],
    ["Genesis 4:25 on Eve praising God for Seth after Abel was murdered", "ఆదికాండము 4:25 హేబెలు చనిపోయిన తరువాత షేతును కనినప్పుడు హవ్వ దేవుని స్తుతించుట", "Genesis 4:25", "\"God has appointed another seed for me instead of Abel, whom Cain killed\"", "\"కయీను చంపిన హేబెలునకు ప్రత్యామ్నాయముగా దేవుడు నాకు మరియొక సంతానమును నియమించెను\"", "God restores godly lineage through persistent maternal faith.", "దేవుడు భక్తిగల వంశావళిని నిలుపుటకు షేతును హవ్వకు అనుగ్రహించెను."],
    ["Genesis 24:60 blessing Rebekah: 'May you become thousands of ten thousands'", "ఆదికాండము 24:60 రిబ్కాను ఆశీర్వదించుచు 'వేవేలుగా విస్తరింపుము' అని దీవించుట", "Genesis 24:60", "\"Our sister, may you become the mother of thousands of ten thousands!\"", "\"మా సహోదరీ, నీవు వేవేలకు తల్లివగుదువు గాక!\"", "Prophetic maternal blessing spoken over Isaac's future bride.", "రిబ్కా వేలాదిమందికి తల్లియై శత్రువుల ద్వారములను స్వాధీనపరచుకొనునను దీవెన."],
    ["Genesis 27:13 on Rebekah saying 'Let your curse be on me, my son'", "ఆదికాండము 27:13 'నీ శాపము నామీదికి వచ్చును గాక' అని రిబ్కా పలికిన మాట", "Genesis 27:13", "\"Let your curse be on me, my son; only obey my voice\"", "\"నా కుమారుడా, ఆ శాపము నామీదికి వచ్చును గాక; నా మాట మాత్రము వినుము\"", "Maternal willingness to bear consequences for her beloved child.", "కుమారుని ఆశీర్వాదము కొరకు శాపమునైనా భరించుటకు సిద్ధపడిన తల్లి."],
    ["Genesis 30:1 on Rachel crying to Jacob: 'Give me children, or else I die!'", "ఆదికాండము 30:1 'నాకు సంతానము నిమ్ము, లేనియెడల నేను చనిపోవుదును' అని రాహేలు వేడుకొనుట", "Genesis 30:1", "\"Give me children, or else I die!\"", "\"నాకు సంతానము నిమ్ము, లేనియెడల నేను చనిపోవుదును\"", "The intense agony of barrenness in the ancient biblical world.", "సంతానము లేని తల్లి పడు తీవ్రమైన మనోవేదన."],
    ["Genesis 30:22 on God remembering Rachel and opening her womb", "ఆదికాండము 30:22 దేవుడు రాహేలును జ్ఞాపకము చేసికొని ఆమె గర్భమును తెరచుట", "Genesis 30:22-24", "\"God listened to her and opened her womb. And she conceived and bore a son\"", "\"దేవుడు రాహేలును జ్ఞాపకము చేసికొనెను, దేవుడు ఆమె మొరను విని ఆమె గర్భమును తెరచెను\"", "God sovereignly opens barren wombs in His appointed time.", "దేవుడు రాహేలు మొరను విని యోసేపును అనుగ్రహించెను."],
    ["Genesis 31:35 on Rachel sitting on the household idols claiming the manner of women", "ఆదికాండము 31:35 రాహేలు గృహదేవతలపై కూర్చుండి స్త్రీధర్మమును బట్టి లేవలేననుట", "Genesis 31:35", "\"Let it not displease my lord that I cannot rise before you, for the manner of women is with me\"", "\"స్త్రీధర్మము నామీద ఉన్నది గనుక నీ యెదుట నేను లేవలేను, నా యేలినవాడవైన నీవు కోపపడవద్దు\"", "Rachel concealing Laban's idols as they fled to Canaan.", "లాబాను గృహదేవతలను దాచిపెట్టిన రాహేలు."],
    ["Exodus 1:15-21 on the Hebrew midwives Shiphrah and Puah fearing God and preserving babies", "నిర్గమకాండము 1:15-21 దేవునికి భయపడి మగపిల్లలను బ్రతికించిన షిఫ్రా పూవా అను మంత్రసానులు", "Exodus 1:17", "\"The midwives feared God, and did not do as the king of Egypt commanded them, but saved the male children alive\"", "\"ఆ మంత్రసానులు దేవునికి భయపడి, ఐగుప్తు రాజు తమకాజ్ఞాపించినట్లు చేయక మగపిల్లలను బ్రదుకనిచ్చిరి\"", "Holy civil disobedience by maternal defenders of newborn life.", "పసిపిల్లల ప్రాణములను కాపాడుటకు దేవునికి భయపడిన నమ్మకమైన స్త్రీలు."],
    ["Exodus 2:9 on Pharaoh's daughter paying Moses' own mother to nurse him", "నిర్గమకాండము 2:9 మోషే తల్లికే జీతమిచ్చి బాలుని పాలిచ్చి పెంచుమని ఫరో కుమార్తె చెప్పుట", "Exodus 2:9", "\"Take this child away and nurse him for me, and I will give you your wages\"", "\"ఈ పిల్లవానిని తీసికొనిపోయి నాకొరకు వానికి పాలిచ్చి పెంచుము, నేను నీకు జీతమిచ్చెదను\"", "Divine irony causing the persecutor to pay Moses' mother to raise him.", "మోషే తల్లికే జీతమిప్పించి దేవుడు అద్భుతముగా బిడ్డను పెంచెను."],
    ["Numbers 26:59 recording Jochebed born to Levi in Egypt who bore Aaron, Moses, and Miriam", "సంఖ్యాకాండము 26:59 లేవి కుమార్తెయైన యోకెబెదు అహరోనును మోషేను మిర్యామును కనుట", "Numbers 26:59", "\"Jochebed, the daughter of Levi... and to Amram she bore Aaron and Moses and their sister Miriam\"", "\"లేవి కుమార్తెయైన యోకెబెదు అమ్రామునకు అహరోనును మోషేను వారి సహోదరియైన మిర్యామును కనెను\"", "The mother of three pivotal leaders of Israel's exodus.", "ఇశ్రాయేలు విమోచన చరిత్రలో ముగ్గురు గొప్ప నాయకులను కనిన ధన్యతగల తల్లి."],
    ["Judges 5:30 on the mother of wicked Sisera expecting plunder and colored robes", "న్యాయాధిపతులు 5:30 సీసెరా తల్లి కొల్లసొమ్మును రంగు రంగుల వస్త్రములను ఆశించుట", "Judges 5:28-30", "\"Why is his chariot so long in coming?... Are they not finding and dividing the spoil?\"", "\"అతని రథము వచ్చుట ఎందుకు ఆలస్యమాయెను?... వారు దోపుడుసొమ్మును పంచుకొనుచున్నారు గదా?\"", "Pagan mothers glorying in violent oppression, unaware of defeat.", "భక్తిహీనులైన తల్లుల దురాశ మరియు అపజయము."],
    ["1 Samuel 1:20 on Hannah naming her son Samuel: 'Because I have asked him from the Lord'", "1 సమూయేలు 1:20 'యెహోవావలన నేను ఇతనిని అడిగితిని' అని హన్నా సమూయేలునకు పేరు పెట్టుట", "1 Samuel 1:20", "\"She named him Samuel, saying, 'Because I have asked for him from the Lord'\"", "\"యెహోవావలన నేను ఇతనిని అడిగితిని అని చెప్పి అతనికి సమూయేలు అని పేరు పెట్టెను\"", "Naming children as testimonies of answered maternal prayer.", "ప్రార్థనకు జవాబుగా పుట్టిన కుమారునికి సాక్ష్యార్థముగా సమూయేలు అని పేరు పెట్టెను."],
    ["1 Samuel 1:28 on Hannah dedicating Samuel to the Lord for all his days", "1 సమూయేలు 1:28 సమూయేలు బ్రదుకు దినములన్నియు యెహోవాకు ప్రతిష్ఠించుట", "1 Samuel 1:28", "\"Therefore I also have lent him to the Lord; as long as he lives he shall be lent to the Lord\"", "\"కాబట్టి నేనును ఆ పిల్లవానిని యెహోవాకు ప్రతిష్టించుచున్నాను; తాను బ్రదుకు దినములన్నియు వాడు యెహోవాకు ప్రతిష్ఠితుడు\"", "The selfless surrender of an answered child into God's service.", "దేవుడు ఇచ్చిన బిడ్డను దేవుని సేవకొరకే సంపూర్ణముగా అప్పగించిన తల్లి."],
    ["1 Samuel 2:21 on the Lord visiting Hannah and blessing her with five more children", "1 సమూయేలు 2:21 దేవుడు హన్నాను దర్శించి మరి ముగ్గురు కుమారులను ఇద్దరు కుమార్తెలను ఇచ్చుట", "1 Samuel 2:21", "\"The Lord visited Hannah, so that she conceived and bore three sons and two daughters\"", "\"యెహోవా హన్నాను దర్శింపగా ఆమె గర్భవతియై ముగ్గురు కుమారులను ఇద్దరు కుమార్తెలను కనెను\"", "God multiplies blessings abundantly when we surrender our best to Him.", "సమూయేలును సమర్పించిన హన్నాకు దేవుడు మరి ఐదుగురు సంతానమునిచ్చి దీవించెను."],
    ["1 Samuel 4:19-22 on Phinehas' wife dying in childbirth and naming the child Ichabod", "1 సమూయేలు 4:19-22 ఫీనెహాసు భార్య ప్రసవవేదనతో మరణించుచు 'ఈకాబోదు' అని పేరు పెట్టుట", "1 Samuel 4:21-22", "\"She named the child Ichabod, saying, 'The glory has departed from Israel!'\"", "\"దేవుని మందసము పట్టబడెననియు, ఇశ్రాయేలులోనుండి ప్రభావము పోయెననియు చెప్పి ఆ బాలునికి ఈకాబోదు అని పేరు పెట్టెను\"", "A mother grieving the departure of God's presence above her own life.", "దేవుని మందసము పట్టబడినందుకు హృదయము పగిలి మరణించిన తల్లి."],
    ["2 Samuel 3:3 on Abigail the Carmelite bearing Chileab (Daniel) to King David", "2 సమూయేలు 3:3 కర్మెలీయురాలైన అబీగయీలు దావీదునకు కిల్యాబును కనుట", "2 Samuel 3:3", "\"His second, Chileab, by Abigail the widow of Nabal the Carmelite\"", "\"రెండవవాడు కర్మెలీయుడైన నాబాలు భార్యయైన అబీగయీలు కనిన కిల్యాబు\"", "Wise peacemaker Abigail becoming a royal mother in Hebron.", "వివేకవంతురాలైన అబీగయీలు హెబ్రోనులో దావీదునకు తల్లిగా మారెను."],
    ["2 Samuel 11:27 on Bathsheba mourning for Uriah before bearing Solomon", "2 సమూయేలు 11:27 ఊరియా చనిపోయినప్పుడు బత్షెబ దుఃఖము సలిపిన తరువాత సొలొమోనుకు తల్లియగుట", "2 Samuel 11:27, 12:24", "\"When the mourning was over, David sent and brought her to his house... and she bore a son, and he called his name Solomon\"", "\"దుఃఖదినములు గడచిన తరువాత దావీదు ఆమెను పిలిపించి తన యింట చేర్చుకొనెను... ఆమె కుమారుని కని అతనికి సొలొమోను అని పేరు పెట్టెను\"", "God's redemptive grace turning tragedy into the royal Messianic line.", "దేవుని కృప బత్షెబ ద్వారా సొలొమోనును అనుగ్రహించి వంశావళిని నిలిపెను."],
    ["2 Samuel 12:24-25 on the Lord loving Solomon and sending Nathan to call him Jedidiah", "2 సమూయేలు 12:24-25 యెహోవా సొలొమోనును ప్రేమించి నాతాను ద్వారా 'యెదీద్యా' అని పేరు పెట్టించుట", "2 Samuel 12:24-25", "\"The Lord loved him, and He sent word by the hand of Nathan the prophet: so he called his name Jedidiah\"", "\"యెహోవా అతని ప్రేమించెను గనుక నాతాను ప్రవక్తద్వారా వర్తమానము పంపి అతనికి యెదీద్యా అని పేరు పెట్టించెను\"", "Divine favor resting on the child born to David and Bathsheba.", "దేవుని ప్రేమ పొందిన యెదీద్యా (యెహోవాకు ప్రియుడు)."],
    ["2 Samuel 21:10 on Rizpah guarding the bodies of her sons day and night", "2 సమూయేలు 21:10 రిజ్పా తన చనిపోయిన కుమారుల శవములపై పక్షులు వాలకుండా రాత్రింబగళ్లు కాపాడుట", "2 Samuel 21:10", "\"Rizpah took sackcloth and spread it for herself on the rock... and suffered neither the birds of the air to rest on them by day nor the beasts of the field by night\"", "\"రిజ్పా గోనెపట్ట తీసికొని బండమీద పరచుకొని, పగలు ఆకాశపక్షులైనను రాత్రి భూజంతువులైనను వాటిమీద వాలనీయక కాపాడెను\"", "Tenacious maternal devotion protecting children even in death.", "చనిపోయిన కుమారుల శరీరములను కూడ ప్రేమతో కాపాడిన తల్లియొక్క అద్భుతమైన భక్తి."],
    ["1 Kings 11:26 on Zeruah the widowed mother of King Jeroboam", "1 రాజులు 11:26 యరొబాము తల్లియైన జెరూవా అను విధవరాలు", "1 Kings 11:26", "\"Jeroboam the son of Nebat, an Ephraimite... whose mother's name was Zeruah, a widow\"", "\"నెబాతు కుమారుడైన యరొబాము ఎఫ్రాయిమీయుడు, అతని తల్లి పేరు జెరూవా, ఆమె విధవరాలు\"", "Scripture records maternal lineages of northern and southern kings.", "రాజుల వంశావళిలో తల్లుల పేర్లు ప్రాముఖ్యముగా నమోదు చేయబడెను."],
    ["1 Kings 14:21 on Naamah the Ammonitess, mother of King Rehoboam", "1 రాజులు 14:21 రెహబాము తల్లియైన నయమా అను అమ్మోనీయ స్త్రీ", "1 Kings 14:21", "\"His mother's name was Naamah, an Ammonitess\"", "\"అతని తల్లి పేరు నయమా, ఆమె అమ్మోనీయురాలు\"", "Foreign maternal idolatry contributed to spiritual decline in Judah.", "అన్యులైన తల్లుల విగ్రహారాధన రాజ్యములో ఆత్మీయ పతనమునకు కారణమాయెను."],
    ["1 Kings 15:13 on King Asa deposing his grandmother Maacah for making an obscene image", "1 రాజులు 15:13 అసహ్యమైన విగ్రహమును చేసినందున ఆసా రాజు తన అవ్వయైన మయకాను పట్టపురాణి పదవినుండి తొలగించుట", "1 Kings 15:13", "\"He also removed Maachah his grandmother from being queen mother, because she had made an obscene image of Asherah\"", "\"ఆమె అషేరాకు అసహ్యమైన విగ్రహము చేయించినందున అతడు తన అవ్వయైన మయకాను పట్టపుదేవి పదవినుండి తొలగించెను\"", "Loyalty to God must supersede even royal grandmotherly authority.", "దేవుని వాక్యము కొరకు విగ్రహారాధకురాలైన రాజమాతను సైతము పదవినుండి తొలగించిన ఆసా."],
    ["2 Kings 8:26 on Athaliah the wicked granddaughter of Omri misleading King Ahaziah", "2 రాజులు 8:26 ఒమ్రీ మనుమరాలైన అతల్యా అహజ్యా రాజును చెడుమార్గములో నడిపించుట", "2 Kings 8:26, 2 Chronicles 22:3", "\"His mother's name was Athaliah... for his mother was his counselor to do wickedly\"", "\"అతని తల్లి పేరు అతల్యా... అతని తల్లి అతనికి దురాలోచన చెప్పినందున అతడు అహాబు కుటుంబపు మార్గములలో నడచెను\"", "The destructive danger of wicked maternal counsel leading kings to ruin.", "చెడు ఆలోచనలు చెప్పు తల్లి సంతానమునకు వినాశనమును తెచ్చును."],
    ["2 Kings 11:1-3 on Jehosheba saving infant Joash from murderous Queen Athaliah", "2 రాజులు 11:1-3 అతల్యా హత్యలనుండి శిశువైన యోవాషును యెహోషెబ దాచి రక్షించుట", "2 Kings 11:2-3", "\"Jehosheba took Joash the son of Ahaziah, and stole him away from among the king's sons who were being murdered\"", "\"యెహోషెబ అహజ్యా కుమారుడైన యోవాషును దొంగిలించి, చంపబడుచున్న రాజకుమారులలో నుండి అతనిని అతని దాదిని దాచిపెట్టెను\"", "A spiritual mother preserving the royal lineage of David in the temple.", "దేవుని ఆలయములో దావీదు వంశపు ఏకైక వారసుని రక్షించిన ధైర్యశాలి యెహోషెబ."],
    ["1 Chronicles 4:9-10 on Jabez's mother naming him with sorrow, yet he became more honorable", "1 దినవృత్తాంతములు 4:9-10 యబ్బేజు తల్లి వేదనతో కనినను అతడు తన సహోదరులకంటె ఘనుడగుట", "1 Chronicles 4:9", "\"His mother called his name Jabez, saying, 'Because I bore him in pain'\"", "\"అతని తల్లి-నేను వేదనపడి ఇతని కంటినని అతనికి యబ్బేజు అను పేరు పెట్టెను\"", "God turns painful maternal births into extraordinary prayer and honor.", "వేదనతో కనబడిన కుమారుడు ప్రార్థన ద్వారా దేవునిచేత ఘనపరచబడెను."],
    ["Psalm 127:3 on children being an heritage of the Lord and fruit of the womb a reward", "కీర్తన 127:3 కుమారులు యెహోవా అనుగ్రహించు స్వాస్థ్యము గర్భఫలము బహుమానము", "Psalm 127:3", "\"Behold, children are a heritage from the Lord, the fruit of the womb is a reward\"", "\"కుమారులు యెహోవా అనుగ్రహించు స్వాస్థ్యము; గర్భఫలము ఆయన యిచ్చు బహుమానమే\"", "Children are not burdens, but divine rewards bestowed upon mothers.", "పిల్లలు దేవుడు తల్లులకు అనుగ్రహించు దివ్య బహుమానము."],
    ["Psalm 128:3 on the wife being like a fruitful vine in the heart of the home", "కీర్తన 128:3 నీ యింటి లోపల నీ భార్య ఫలించు ద్రాక్షావల్లివలె ఉండును", "Psalm 128:3", "\"Your wife shall be like a fruitful vine in the very heart of your house, your children like olive plants\"", "\"నీ యింటి లోపల నీ భార్య ఫలించు ద్రాక్షావల్లివలె ఉండును; నీ భోజనపు బల్లచుట్టు నీ పిల్లలు ఒలీవ మొక్కలవలె ఉందురు\"", "The blessed mother flourishing with spiritual fruitfulness in the home.", "దేవునికి భయపడు ఇల్లాలు తన గృహములో ఫలభరితముగా వర్ధిల్లును."],
    ["Matthew 1:5 on Rahab the mother of Boaz included in the Messianic genealogy", "మత్తయి 1:5 మెస్సీయ వంశావళిలో బోయజు తల్లియైన రాహాబు పేర్కొనబడుట", "Matthew 1:5", "\"Salmon begot Boaz by Rahab, Boaz begot Obed by Ruth\"", "\"సల్మాను రాహాబునందు బోయజును కనెను, బోయజు రూతునందు ఓబేదును కనెను\"", "God's redeeming grace grafting a Gentile mother into Christ's royal line.", "విశ్వాసము ద్వారా రక్షించబడిన రాహాబు క్రీస్తు వంశావళిలో తల్లిగా నిలిచెను."],
    ["Matthew 1:6 on Uriah's wife Bathsheba being the mother of King Solomon", "మత్తయి 1:6 దావీదు ఊరియా భార్యయందు సొలొమోనును కనెనను వంశావళి", "Matthew 1:6", "\"David the king begot Solomon by her who had been the wife of Uriah\"", "\"దావీదు ఊరియా భార్యయై యుండిన ఆమెయందు సొలొమోనును కనెను\"", "Divine mercy forgiving sin and exalting Bathsheba as an ancestor of Christ.", "దేవుని క్షమాగుణము బత్షెబను రక్షకుని వంశావళిలో చేర్చెను."],
    ["Luke 1:38 on Mary's total surrender: 'Let it be to me according to your word'", "లూకా 1:38 'నీ మాటచొప్పున నాకు జరుగును గాక' అని మరియ సమర్పించుకొనుట", "Luke 1:38", "\"Behold the maidservant of the Lord! Let it be to me according to your word\"", "\"ఇదిగో ప్రభువు దాసురాలను, నీ మాటచొప్పున నాకు జరుగును గాక అని మరియ పలికెను\"", "The pinnacle of maternal faith and submission to the Holy Spirit.", "పరిశుద్ధాత్మ కార్యమునకు సంపూర్ణముగా లోబడిన మరియ విశ్వాసము."],
    ["Luke 1:45 on Elizabeth blessing Mary: 'Blessed is she who believed'", "లూకా 1:45 'నమ్మిన స్త్రీ ధన్యురాలు' అని ఎలీసబెతు మరియను స్తుతించుట", "Luke 1:45", "\"Blessed is she who believed, for there will be a fulfillment of those things which were told her from the Lord\"", "\"ప్రభువువలన ఆమెకు చెప్పబడిన మాటలు నెరవేరునని నమ్మిన స్త్రీ ధన్యురాలు\"", "Believing mothers see the glorious fulfillment of God's promises.", "దేవుని వాగ్దానములను నమ్మిన తల్లులు దైవిక నెరవేర్పును చూతురు."],
    ["Luke 2:22-24 on Mary offering a pair of turtledoves at Jesus' presentation in the temple", "లూకా 2:22-24 దేవాలయములో మోషే ధర్మశాస్త్రము చొప్పున మరియ రెండు గువ్వలను అర్పించుట", "Luke 2:24", "\"To offer a sacrifice according to what is said in the law of the Lord: 'A pair of turtledoves or two young pigeons'\"", "\"రెండు గువ్వలనైనను రెండు పావురపు పిల్లలనైనను బలిగా అర్పించుటకు ప్రభువు ధర్మశాస్త్రమందు చెప్పబడినట్టు చేసిరి\"", "Mary observed the offering of the poor, showing humble obedience.", "పేదవారు అర్పించు రెండు గువ్వల బలిని అర్పించిన దీనురాలైన తల్లి."],
    ["Luke 2:49 on twelve-year-old Jesus explaining His presence in the Father's house to His mother", "లూకా 2:49 తాను తన తండ్రి యింట ఉండవలెనని పన్నెండేండ్ల యేసు తల్లికి బోధించుట", "Luke 2:49", "\"Why did you seek Me? Did you not know that I must be about My Father's business?\"", "\"మీరు నన్ను ఎందుకు వెదకుచుంటిరి? నేను నా తండ్రి కార్యములమీద ఉండవలెనని మీరు ఎరుగరా?\"", "Mothers learning that divine callings supersede earthly expectations.", "భూసంబంధమైన కోరికలకంటె దైవిక పిలుపు ఉన్నతమైనదని మరియ గ్రహించెను."],
    ["John 2:4 on Jesus saying to Mary 'My hour has not yet come'", "యోహాను 2:4 'నా సమయము ఇంకను రాలేదు' అని యేసు మరియతో పలుకుట", "John 2:4", "\"Woman, what does your concern have to do with Me? My hour has not yet come\"", "\"అమ్మా, నాతో నీకేమి పని? నా సమయము ఇంకను రాలేదని ఆమెతో చెప్పెను\"", "Jesus transitioning from earthly son to divine Messiah operating on the Father's clock.", "పరలోకపు తండ్రి సమయపట్టిక ప్రకారము నడుచుకొను మెస్సీయ."],
    ["Romans 16:13 on Rufus' mother displaying maternal hospitality to Paul", "రోమీయులకు 16:13 రూఫు తల్లి పౌలునకు తల్లివలె ఆదరణ చూపుట", "Romans 16:13", "\"Greet Rufus, chosen in the Lord, and his mother and mine\"", "\"ప్రభువునందు ఏర్పరచబడిన రూఫునకును, నాకును తల్లియైన అతని తల్లికిని వందనములు\"", "Spiritual motherhood expanding the bounds of biological family.", "రక్తసంబంధము కాకపోయినను సువార్త సేవకులకు తల్లిగా నిలిచిన భక్తిగల స్త్రీ."],
    ["2 Timothy 3:15 on the holy scriptures making young Timothy wise unto salvation", "2 తిమోతి 3:15 పవిత్ర లేఖనములు తిమోతికి రక్షణార్థమైన జ్ఞానమునిచ్చుట", "2 Timothy 3:15", "\"From childhood you have known the Holy Scriptures, which are able to make you wise for salvation through faith in Christ Jesus\"", "\"క్రీస్తుయేసునందలి విశ్వాసముద్వారా రక్షణార్థమైన జ్ఞానము నీకు కలిగించుటకు శక్తిగల పరిశుద్ధ లేఖనములను బాల్యమునుండి ఎరుగుదువు\"", "Maternal Bible teaching anchors the soul in eternal salvation.", "తల్లి బోధించిన పరిశుద్ధ లేఖనములు రక్షణకు నడిపించును."],
    ["Hebrews 11:11 on Sarah receiving strength to conceive seed through faith", "హెబ్రీ 11:11 విశ్వాసమునుబట్టి శారా వయస్సు గతించినదైనను గర్భము ధరించుటకు శక్తి పొందుట", "Hebrews 11:11", "\"By faith Sarah herself also received strength to conceive seed, and she bore a child when she was past the age\"", "\"విశ్వాసమునుబట్టి శారాయు వాగ్దానము చేసినవాడు నమ్మదగినవాడని యెంచుకొనెను గనుక వయస్సు గతించినదైనను గర్భము ధరించుటకు శక్తి పొందెను\"", "Maternal faith anchoring on the absolute faithfulness of God.", "వాగ్దానము చేసిన దేవుడు నమ్మదగినవాడని నమ్మిన తల్లి విశ్వాసము."],
    ["Hebrews 11:23 on Moses hidden by faith for three months by his parents", "హెబ్రీ 11:23 విశ్వాసమునుబట్టి మోషే తల్లిదండ్రులు రాజు ఆజ్ఞకు భయపడక మూడు నెలలు అతనిని దాచుట", "Hebrews 11:23", "\"By faith Moses, when he was born, was hidden three months by his parents, because they saw he was a beautiful child\"", "\"మోషే పుట్టినప్పుడు అతని తల్లిదండ్రులు ఆ బాలుడు సుందరుడై యుండుట చూచి, విశ్వాసమునుబట్టి రాజాజ్ఞకు భయపడక మూడు నెలలు అతని దాచిపెట్టిరి\"", "Maternal faith defying demonic tyrannical decrees.", "దుష్ట రాజాజ్ఞకు భయపడక దేవునియందు విశ్వాసముంచిన తల్లిదండ్రులు."],
    ["Revelation 12:17 on the dragon making war with the rest of the woman's offspring", "ప్రకటన 12:17 స్త్రీయొక్క శేషించిన సంతానముతో యుద్ధము చేయుటకు ఘటసర్పము వెళ్ళుట", "Revelation 12:17", "\"The dragon was enraged with the woman, and he went to make war with the rest of her offspring, who keep the commandments of God\"", "\"ఆ ఘటసర్పము ఆ స్త్రీమీద ఆగ్రహము తెచ్చుకొని, దేవుని ఆజ్ఞలను గైకొనుచు యేసునుగూర్చి సాక్ష్యమిచ్చుచున్నవారైన ఆమె శేషించిన సంతానముతో యుద్ధము చేయుటకు వెళ్లెను\"", "The corporate spiritual mother producing saints who conquer through the Lamb.", "దేవుని నిబంధన సంఘమైన తల్లి క్రీస్తు సాక్షులను లోకమునకు కనుచున్నది."],
    ["Genesis 25:28 on Isaac loving Esau while Rebekah loved Jacob", "ఆదికాండము 25:28 ఇస్సాకు ఏశావును ప్రేమించెను గాని రిబ్కా యాకోబును ప్రేమించెను", "Genesis 25:28", "\"Isaac loved Esau because he ate of his venison, but Rebekah loved Jacob\"", "\"ఇస్సాకు ఏశావు తెచ్చిన వేటమాంసమును తినుచుండెను గనుక అతని ప్రేమించెను; అయితే రిబ్కా యాకోబును ప్రేమించెను\"", "Parental preferences and maternal bonding in the patriarchal family.", "యాకోబును ప్రేమించిన తల్లి రిబ్కా."],
    ["Genesis 27:6 on Rebekah instructing Jacob to prepare savory food for Isaac's blessing", "ఆదికాండము 27:6 ఇస్సాకు దీవెన పొందుటకు యాకోబును రిబ్కా సిద్ధపరచుట", "Genesis 27:6-10", "\"Rebekah spoke to Jacob her son... go now to the flock and bring me two choice kids of the goats\"", "\"రిబ్కా తన కుమారుడైన యాకోబుతో మాటలాడెను... నీవు మందయొద్దకు వెళ్లి రెండు మేకపిల్లలను నా యొద్దకు తెమ్ము\"", "Maternal intervention guiding the prophetic blessing according to promise.", "దేవుని వాగ్దానము నెరవేరునట్లు కుమారుని నడిపించిన తల్లి."],
    ["Genesis 27:15 on Rebekah clothing Jacob with Esau's choice garments", "ఆదికాండము 27:15 ఏశావు మంచి వస్త్రములను తీసి యాకోబునకు తొడిగించిన రిబ్కా", "Genesis 27:15", "\"Rebekah took the choice clothes of her elder son Esau... and put them on Jacob\"", "\"రిబ్కా ఇంటనున్న తన పెద్ద కుమారుడైన ఏశావుయొక్క మంచి వస్త్రములను తీసి తన చిన్న కుమారుడైన యాకోబునకు తొడిగించెను\"", "Maternal strategy ensuring the covenant blessing reached Jacob.", "యాకోబునకు వస్త్రములను తొడిగి దీవెన పొందునట్లు చేసిన తల్లి."],
    ["Genesis 29:32 on Leah naming Reuben: 'The Lord has looked on my affliction'", "ఆదికాండము 29:32 'యెహోవా నా శ్రమను చూచెను' అని లేయా రూబేనునకు పేరు పెట్టుట", "Genesis 29:32", "\"She named him Reuben, for she said, 'The Lord has looked upon my affliction'\"", "\"లేయా గర్భవతియై కుమారుని కని-నిశ్చయముగా యెహోవా నా శ్రమను చూచియున్నాడు అని అతనికి రూబేను అని పేరు పెట్టెను\"", "Mothers crying out to God in marital loneliness and sorrow.", "తన శ్రమను చూచిన దేవుని కనికరమును సాక్ష్యమిచ్చిన తల్లి లేయా."],
    ["Genesis 29:33 on Leah naming Simeon: 'The Lord heard that I am unloved'", "ఆదికాండము 29:33 'నేను ద్వేషింపబడితినని యెహోవా వినెను' అని లేయా షిమ్యోనునకు పేరు పెట్టుట", "Genesis 29:33", "\"She said, 'Because the Lord heard that I was unloved, He has therefore given me this son also'\"", "\"యెహోవా నేను ద్వేషింపబడితినని విని నాకు ఇతనినికూడ ఇచ్చెనని చెప్పి అతనికి షిమ్యోను అని పేరు పెట్టెను\"", "God hears the tears of unloved and marginalized mothers.", "అలక్ష్యము చేయబడిన తల్లి కన్నీటి మొరను దేవుడు ఆలకించును."],
    ["Genesis 29:34 on Leah naming Levi: 'Now my husband will be joined to me'", "ఆదికాండము 29:34 'ఇకమీదట నా పెనిమిటి నాతో హత్తుకొనియుండును' అని లేయా లేవికి పేరు పెట్టుట", "Genesis 29:34", "\"Now this time my husband will become attached to me, because I have borne him three sons\"", "\"నేను అతనికి ముగ్గురు కుమారులను కంటిని గనుక ఇకమీదట నా పెనిమిటి నాతో హత్తుకొనియుండునని చెప్పి అతనికి లేవి అని పేరు పెట్టెను\"", "A mother longing for deep marital affection and connection.", "భర్త ప్రేమను కోరుకొనిన తల్లి వేదన."],
    ["Genesis 30:6 on Rachel naming Dan: 'God has judged my cause'", "ఆదికాండము 30:6 'దేవుడు నాకు న్యాయము తీర్చెను' అని రాహేలు దానునకు పేరు పెట్టుట", "Genesis 30:6", "\"God has judged my case; and He has also heard my voice and given me a son\"", "\"దేవుడు నాకు న్యాయము తీర్చెను, ఆయన నా మొరను విని నాకు కుమారుని ఇచ్చెనని చెప్పి అతనికి దాను అని పేరు పెట్టెను\"", "Rachel celebrating divine vindication through childbearing.", "దేవుడు తన మొరను విని న్యాయము తీర్చెనని రాహేలు సాక్ష్యమిచ్చెను."],
    ["Genesis 30:8 on Rachel naming Naphtali: 'With great wrestlings have I wrestled'", "ఆదికాండము 30:8 'నేను గొప్ప పోరాటము పోరాడి జయించితిని' అని రాహేలు నఫ్తాలికి పేరు పెట్టుట", "Genesis 30:8", "\"With great wrestlings I have wrestled with my sister, and indeed I have prevailed\"", "\"దేవుని సంబంధమైన పోరాటములతో నేను నా సహోదరితో పోరాడి జయించితిని అని చెప్పి అతనికి నఫ్తాలి అని పేరు పెట్టెను\"", "Sisterly maternal competition in the house of Jacob.", "యాకోబు గృహములో తల్లుల మధ్య కలిగిన తీవ్ర పోరాటము."],
    ["Genesis 30:11 on Leah naming Gad: 'A troop comes!'", "ఆదికాండము 30:11 'అదృష్టము వచ్చెను' అని లేయా గాదునకు పేరు పెట్టుట", "Genesis 30:11", "\"Leah said, 'A troop comes!' So she called his name Gad\"", "\"లేయా-అదృష్టము వచ్చెనని చెప్పి అతనికి గాదు అని పేరు పెట్టెను\"", "Joyful expansion of the maternal heritage of Jacob.", "మరియొక కుమారుడు పుట్టినందుకు సంతోషించిన తల్లి."],
    ["Genesis 30:13 on Leah naming Asher: 'Happy am I, for the daughters will call me blessed'", "ఆదికాండము 30:13 'నేను ధన్యురాలను, స్త్రీలు నన్ను ధన్యురాలందురు' అని లేయా ఆషేరునకు పేరు పెట్టుట", "Genesis 30:13", "\"Leah said, 'I am happy, for the daughters will call me blessed.' So she called his name Asher\"", "\"లేయా-నేను ధన్యురాలను, స్త్రీలు నన్ను ధన్యురాలందురు అని చెప్పి అతనికి ఆషేరు అని పేరు పెట్టెను\"", "A mother rejoicing in blessedness and divine favor.", "దేవుని దయవలన తాను ధన్యురాలనైతినని లేయా ఆనందించెను."]
  ];

  return data.map((item, idx) => ({
    easyQ: `What profound scripture fact is revealed regarding ${item[0]}?`,
    easyQTe: `${item[1]} గూర్చి లేఖనములో బయలుపరచబడిన లోతైన సత్యమేమి?`,
    medQ: `In ${item[2]}, what specific detail explains the spiritual impact of this maternal legacy?`,
    medQTe: `${item[2]} లో ఈ మాతృమూర్తి ఆత్మీయ వారసత్వమును గూర్చి వివరించబడిన వివరమేమి?`,
    hardQ: `What canonical and Christological fulfillment connects to the truth in ${item[2]}?`,
    hardQTe: `${item[2]} లోని సత్యము మెస్సీయ రక్షణ ప్రణాళికతో ఏ విధముగా ముడిపడియున్నది?`,
    options: [item[3], "She established seven pagan groves in Samaria", "She gathered three hundred bronze shields", "She retreated to the valley of Salt"],
    optionsTelugu: [item[4], "షమ్రోనులో ఏడు విగ్రహ తోపులను స్థాపించెను", "మూడు వందల ఇత్తడి డాలులను సమకూర్చెను", "ఉప్పు లోయలోనికి పారిపోయెను"],
    correctAnswer: item[3],
    bibleReference: item[2],
    explanation: item[5],
    explanationTelugu: item[6]
  }));
}

const fFacts = foundationFacts;
const gFacts = buildMotherGrowth();
const mFacts = buildMotherMastery();

console.log(`Mother Foundation facts count: ${fFacts.length}`);
console.log(`Mother Growth facts count: ${gFacts.length}`);
console.log(`Mother Mastery facts count: ${mFacts.length}`);

buildBank('Mother', 'mth', fFacts, gFacts, mFacts);
