const { buildBank } = require('./bank_builder.js');

// 50 Foundation Facts
const foundationFacts = [
  {
    easyQ: "Who was King Saul's son whose soul was knit to David in deep biblical friendship?",
    easyQTe: "దావీదుతో ప్రాణస్నేహము చేసిన సౌలు కుమారుడు ఎవరు?",
    medQ: "According to 1 Samuel 18:1, how did Scripture describe Jonathan's love for his friend David?",
    medQTe: "1 సమూయేలు 18:1 ప్రకారం యోనాతాను దావీదును ఏ విధముగా ప్రేమించెనని లేఖనము సెలవిచ్చుచున్నది?",
    hardQ: "In the covenant friendship of 1 Samuel 18:1-3, what specific theological covenant was established between David and Jonathan?",
    hardQTe: "1 సమూయేలు 18:1-3 లో దావీదు మరియు యోనాతానుల మధ్య ఏ పవిత్ర నిబంధన స్థిరపరచబడెను?",
    options: ["Jonathan", "Abner", "Ishbosheth", "Joab"],
    optionsTelugu: ["యోనాతాను", "అబ్నేరు", "ఈష్బోషెతు", "యోవాబు"],
    correctAnswer: "Jonathan",
    bibleReference: "1 Samuel 18:1-3",
    explanation: "Jonathan loved David as his own soul and they made a covenant of loyalty.",
    explanationTelugu: "యోనాతాను దావీదును తన ప్రాణమువలె ప్రేమించి నిబంధన చేసెను."
  },
  {
    easyQ: "What royal garments and weapons did Jonathan give to David as a pledge of friendship in 1 Samuel 18:4?",
    easyQTe: "1 సమూయేలు 18:4 లో యోనాతాను దావీదుకు స్నేహ సంకేతముగా ఏ రాజ వస్త్రములు, ఆయుధములు ఇచ్చెను?",
    medQ: "By giving David his robe, tunic, sword, bow, and belt, what was Jonathan symbolically yielding to his friend?",
    medQTe: "తన అంగీని, కత్తిని, వింటిని దావీదుకు ఇచ్చుట ద్వారా యోనాతాను సూచనాత్మకముగా దేనిని అప్పగించెను?",
    hardQ: "In ancient Near Eastern covenant practices reflected in 1 Samuel 18:4, what did the transfer of Jonathan's armor signify?",
    hardQTe: "1 సమూయేలు 18:4 ప్రకారం యోనాతాను తన ఆయుధములను దావీదుకు ఇచ్చుట దేనికి ప్రతీక?",
    options: ["His royal robe, tunic, sword, bow, and belt", "A golden crown and silver sceptre", "Ten war chariots from Gilgal", "A purple banner of the tribe of Benjamin"],
    optionsTelugu: ["తన రాజ వస్త్రమును, అంగీని, కత్తిని, వింటిని, నడుముకట్టును", "బంగారు కిరీటము మరియు వెండి దండము", "గిల్గాలు నుండి పది రథములు", "బెన్యామీను గోత్రపు ఊదా జెండా"],
    correctAnswer: "His royal robe, tunic, sword, bow, and belt",
    bibleReference: "1 Samuel 18:4",
    explanation: "Jonathan stripped himself of his royal robe and weapons to honor David as God's anointed.",
    explanationTelugu: "యోనాతాను తన రాజ వస్త్రములను తీసి దావీదును సన్మానించెను."
  },
  {
    easyQ: "How did Jonathan send a secret warning signal to David concerning King Saul's deadly intentions?",
    easyQTe: "సౌలు వలన కలుగబోవు అపాయమును గూర్చి యోనాతాను దావీదుకు ఏ రహస్య సంకేతము పంపెను?",
    medQ: "In 1 Samuel 20:20-22, how many arrows did Jonathan shoot to communicate with David in hiding?",
    medQTe: "1 సమూయేలు 20:20-22 లో యోనాతాను దావీదుతో సంభాషించుటకు ఎన్ని బాణములను విడిచెను?",
    hardQ: "What specific phrase spoken to the boy retrieving the arrows signaled to David that he had to flee immediately?",
    hardQTe: "బాణములను తెచ్చు బాలునితో యోనాతాను పలికిన ఏ మాట దావీదు పారిపోవలెనని సూచించెను?",
    options: ["By shooting three arrows and calling to the boy that they were beyond him", "By sounding a shofar from the wall of Gibeah", "By waving a white cloth from the palace gate", "By lighting a beacon fire on Mount Carmel"],
    optionsTelugu: ["మూడు బాణములు విడిచి బాలునితో అవి నీకు ఆవల ఉన్నవని చెప్పుట ద్వారా", "గిబియా గోడపై నుండి బాకా ఊదుట ద్వారా", "రాజభవన ద్వారము వద్ద తెల్లని వస్త్రము ఊపుట ద్వారా", "కర్మెలు కొండపై మంట వేయుట ద్వారా"],
    correctAnswer: "By shooting three arrows and calling to the boy that they were beyond him",
    bibleReference: "1 Samuel 20:20-22",
    explanation: "Jonathan shot three arrows as a predetermined code to warn David that Saul meant to kill him.",
    explanationTelugu: "యోనాతాను మూడు బాణములు విడిచి దావీదును హెచ్చరించెను."
  },
  {
    easyQ: "Where did David and Jonathan weep together in deep sorrow before parting ways in 1 Samuel 20?",
    easyQTe: "1 సమూయేలు 20 లో దావీదు మరియు యోనాతానులు వీడ్కోలు తీసికొనుటకు ముందు ఎక్కడ కలిసి రోదనము చేసిరి?",
    medQ: "Near what landmark did David emerge from hiding to meet Jonathan in 1 Samuel 20:41?",
    medQTe: "1 సమూయేలు 20:41 లో దావీదు ఏ రాతి యొద్దనుండి లేచి యోనాతానును కలుసుకొనెను?",
    hardQ: "In 1 Samuel 20:41-42, what posture of honor did David assume before embracing Jonathan at the stone Ezel?",
    hardQTe: "1 సమూయేలు 20:41-42 లో ఏజెల్ రాతి యొద్ద దావీదు యోనాతాను ఎదుట ఏ గౌరవ భంగిమలో సాగిలపడెను?",
    options: ["At the stone Ezel, bowing three times and weeping", "At the well of Beersheba", "Inside the tabernacle at Nob", "At the pool of Gibeon"],
    optionsTelugu: ["ఏజెల్ రాతి యొద్ద మూడుసార్లు సాగిలపడి రోదనము చేసిరి", "బేయేర్షెబా బావి యొద్ద", "నోబులోని ప్రత్యక్షపు గుడారములో", "గిబియోను కొలను యొద్ద"],
    correctAnswer: "At the stone Ezel, bowing three times and weeping",
    bibleReference: "1 Samuel 20:41-42",
    explanation: "David bowed three times to the ground, kissed his friend, and they wept together until David exceeded.",
    explanationTelugu: "దావీదు మూడుసార్లు నేలమట్టుకు సాగిలపడి యోనాతానును ముద్దుపెట్టుకొని కన్నీరు కార్చెను."
  },
  {
    easyQ: "Where did Jonathan secretly visit David for the last time to strengthen his faith in God?",
    easyQTe: "యోనాతాను చివరిసారిగా దావీదును దేవునియందు బలపరచుటకు ఎక్కడికి రహస్యముగా వచ్చెను?",
    medQ: "According to 1 Samuel 23:16, what did Jonathan encourage David about during their meeting in Horesh?",
    medQTe: "1 సమూయేలు 23:16 ప్రకారం హోరెషులో యోనాతాను దావీదుకు ఏ ధైర్యపు మాటలు చెప్పెను?",
    hardQ: "What prophetic expectation regarding David's future reign did Jonathan articulate in the wilderness of Ziph?",
    hardQTe: "జీపు అరణ్యములో దావీదు రాబోవు పరిపాలనను గూర్చి యోనాతాను ఏ ప్రవచనము పలికెను?",
    options: ["In the woods of Horesh in the wilderness of Ziph", "At the caves of Engedi", "In the valley of Elah", "Inside the walls of Jerusalem"],
    optionsTelugu: ["జీపు అరణ్యములోని హోరెషు వనములో", "ఏన్గెదీ గుహలయొద్ద", "ఏలా లోయలో", "యెరూషలేము ప్రాకారముల లోపల"],
    correctAnswer: "In the woods of Horesh in the wilderness of Ziph",
    bibleReference: "1 Samuel 23:16-18",
    explanation: "Jonathan went to David at Horesh and strengthened his hand in God, assuring him he would be king.",
    explanationTelugu: "యోనాతాను హోరెషులోని దావీదునొద్దకు వచ్చి దేవునియందు అతని బలపరచెను."
  },
  {
    easyQ: "What moving eulogy did David write to honor Jonathan after the battle on Mount Gilboa?",
    easyQTe: "గిల్బోవా పర్వత యుద్ధము తరువాత యోనాతానును స్మరించుకొనుచు దావీదు రచించిన విలాపవాక్యమేది?",
    medQ: "In 2 Samuel 1:26, how did David describe Jonathan's love compared to worldly love?",
    medQTe: "2 సమూయేలు 1:26 లో దావీదు యోనాతాను ప్రేమను లోక సంబంధమైన ప్రేమతో పోల్చుచు ఏమని వర్ణించెను?",
    hardQ: "In the Song of the Bow (2 Samuel 1:19-27), what Hebrew term captures David's deep affection for his fallen friend?",
    hardQTe: "వింటి పాట (2 సమూయేలు 1) లో మరణించిన స్నేహితునిపై దావీదు పలికిన హృదయ విదారకమైన మాటలేవి?",
    options: ["\"Your love to me was wonderful, surpassing the love of women\"", "\"You were the conqueror of Babylon\"", "\"Your wealth filled the hills of Judah\"", "\"Your spear was feared by Egypt\""],
    optionsTelugu: ["\"నా సహోదరుడా యోనాతానా, నీ ప్రేమ నాకు ఆశ్చర్యమైనది, స్త్రీల ప్రేమకంటె విశేషమైనది\"", "\"నీవు బబులోనును జయించినవాడవు\"", "\"నీ సంపద యూదా కొండలను నింపెను\"", "\"నీ ఈటెకు ఐగుప్తు భయపడెను\""],
    correctAnswer: "\"Your love to me was wonderful, surpassing the love of women\"",
    bibleReference: "2 Samuel 1:26",
    explanation: "David mourned deeply for Jonathan, praising his pure and sacrificial friendship.",
    explanationTelugu: "దావీదు: నీ ప్రేమ నాకు ఆశ్చర్యమైనది, స్త్రీల ప్రేమకంటె విశేషమైనది అని విలపించెను."
  },
  {
    easyQ: "Who was the lame son of Jonathan whom King David blessed and restored for Jonathan's sake?",
    easyQTe: "యోనాతానుతో చేసిన స్నేహ నిబంధన నిమిత్తము దావీదు ఆదరించిన కుంటివాడైన కుమారుడు ఎవరు?",
    medQ: "In 2 Samuel 9:3, what question did David ask concerning the remaining household of Saul?",
    medQTe: "2 సమూయేలు 9:3 లో సౌలు కుటుంబములో శేషించినవారిని గూర్చి దావీదు ఏమని విచారించెను?",
    hardQ: "What specific theological concept of divine covenant loyalty (Hesed) did David demonstrate toward Mephibosheth?",
    hardQTe: "మెఫీబోషెతు పట్ల దావీదు చూపిన దేవుని నిబంధన కృప (హెసెద్) దేనిని రుజువు చేయుచున్నది?",
    options: ["Mephibosheth", "Mahlon", "Chimham", "Hanun"],
    optionsTelugu: ["మెఫీబోషెతు", "మహలోను", "కింహాము", "హానూను"],
    correctAnswer: "Mephibosheth",
    bibleReference: "2 Samuel 9:1-7",
    explanation: "David sought out Mephibosheth to show him the kindness of God for Jonathan's sake.",
    explanationTelugu: "యోనాతాను నిమిత్తము దావీదు మెఫీబోషెతుకు దేవుని దయ చూపించెను."
  },
  {
    easyQ: "Where was Mephibosheth living before King David summoned him to eat at the royal table?",
    easyQTe: "దావీదు రాజు తన బల్లయొద్ద భోజనమునకు పిలువకముందు మెఫీబోషెతు ఎక్కడ నివసించుచుండెను?",
    medQ: "In whose home in Lo-Debar was Mephibosheth being sheltered prior to David's summons?",
    medQTe: "లోదెబారులో ఎవరి ఇంట మెఫీబోషెతు ఆశ్రయము పొందియుండెను?",
    hardQ: "What does the name and location of Lo-Debar symbolize regarding Mephibosheth's condition before David's covenant grace?",
    hardQTe: "దావీదు నిబంధన కృప చూపకముందు లోదెబారు అను స్థలము మెఫీబోషెతు యొక్క ఏ దీనస్థితిని సూచించుచున్నది?",
    options: ["In Lo-Debar, at the house of Machir son of Ammiel", "In the city of Jericho", "In the fortress of Lachish", "In the plains of Shittim"],
    optionsTelugu: ["అమ్మీయేలు కుమారుడైన మాకీరు ఇంట లోదెబారులో", "యెరికో పట్టణములో", "లాకీషు కోటలో", "షిత్తీము మైదానములో"],
    correctAnswer: "In Lo-Debar, at the house of Machir son of Ammiel",
    bibleReference: "2 Samuel 9:4-5",
    explanation: "David fetched Mephibosheth from the home of Machir in Lo-Debar to restore him.",
    explanationTelugu: "దావీదు లోదెబారులోని మాకీరు ఇంటనుండి మెఫీబోషెతును పిలిపించెను."
  },
  {
    easyQ: "Who was the former servant of Saul whom David appointed to farm the restored lands for Mephibosheth?",
    easyQTe: "మెఫీబోషెతు భూములను సాగుచేసి ఫలములను సమకూర్చుటకు దావీదు నియమించిన సౌలు సేవకుడు ఎవరు?",
    medQ: "How many sons and servants did Ziba have when David commanded him to serve Jonathan's son?",
    medQTe: "యోనాతాను కుమారునికి సేవ చేయుటకు దావీదు ఆజ్ఞాపించినప్పుడు సీబాకు ఎంతమంది కుమారులు, దాసులు ఉండిరి?",
    hardQ: "According to 2 Samuel 9:10, what was the stewardship responsibility assigned to Ziba and his household?",
    hardQTe: "2 సమూయేలు 9:10 ప్రకారం సీబా కుటుంబమునకు అప్పగించబడిన గృహనిర్వాహకత్వ బాధ్యత ఏది?",
    options: ["Ziba, who had fifteen sons and twenty servants", "Gehazi, servant of Elisha", "Eliezer of Damascus", "Ebed-Melech the Ethiopian"],
    optionsTelugu: ["పదిహేనుమంది కుమారులు, ఇరువదిమంది దాసులు గల సీబా", "గేహజీ", "దమస్కు ఎలీయెజెరు", "ఎబెద్మెలెకు"],
    correctAnswer: "Ziba, who had fifteen sons and twenty servants",
    bibleReference: "2 Samuel 9:9-10",
    explanation: "David ordered Ziba and his household to cultivate Saul's land for Mephibosheth.",
    explanationTelugu: "సీబా మరియు అతని దాసులు మెఫీబోషెతు కొరకు భూమిని దున్ని ఫలము తేవలెనని దావీదు ఆజ్ఞాపించెను."
  },
  {
    easyQ: "What privilege was permanently granted to Mephibosheth in Jerusalem by King David?",
    easyQTe: "యెరూషలేములో దావీదు రాజు మెఫీబోషెతుకు అనుగ్రహించిన నిరంతర ఆధిక్యత ఏది?",
    medQ: "In 2 Samuel 9:11-13, how frequently did Mephibosheth eat at the king's personal table?",
    medQTe: "2 సమూయేలు 9:11-13 లో మెఫీబోషెతు రాజు బల్లయొద్ద ఎంత తరచుగా భోజనము చేసెను?",
    hardQ: "How does Mephibosheth eating continually at the king's table foreshadow believers sitting with Christ?",
    hardQTe: "మెఫీబోషెతు నిత్యము రాజు బల్లయొద్ద భోజనము చేయుట విశ్వాసులు క్రీస్తుతో పాలుపొందు ఏ నిత్య ఆధిక్యతను సూచించుచున్నది?",
    options: ["He ate continually at the king's table like one of the king's own sons", "He was appointed commander of the royal guard", "He received the high priesthood at Shiloh", "He was given five cities in Gilead"],
    optionsTelugu: ["రాజు కుమారులలో ఒకనివలె నిత్యము రాజు బల్లయొద్ద భోజనము చేసెను", "రాజ రక్షక దళాధిపతిగా నియమించబడెను", "షీలోహులో ప్రధాన యాజకత్వము పొందెను", "గిలాదులో ఐదు పట్టణములు పొందెను"],
    correctAnswer: "He ate continually at the king's table like one of the king's own sons",
    bibleReference: "2 Samuel 9:11-13",
    explanation: "Mephibosheth lived in Jerusalem and ate continually at David's table for Jonathan's sake.",
    explanationTelugu: "మెఫీబోషెతు రాజు కుమారులలో ఒకనివలె నిత్యము రాజు బల్లయొద్ద భోజనము చేసెను."
  },
  {
    easyQ: "What did Orpah do when Naomi urged her daughters-in-law to return to their families in Moab?",
    easyQTe: "మోయాబులోని తమ కుటుంబములయొద్దకు తిరిగి వెళ్లమని నయోమి కోరినప్పుడు ఓర్పా ఏమి చేసెను?",
    medQ: "Contrast Orpah's action with Ruth's action toward Naomi in Ruth 1:14:",
    medQTe: "రూతు 1:14 లో నయోమి పట్ల ఓర్పా మరియు రూతుల ప్రవర్తనలోని వ్యత్యాసమేమి?",
    hardQ: "What theological divergence occurred between Orpah and Ruth at the border of Moab?",
    hardQTe: "మోయాబు సరిహద్దులో ఓర్పా మరియు రూతుల విశ్వాస తీర్మానములో ఏ వ్యత్యాసము ఏర్పడెను?",
    options: ["Orpah kissed her mother-in-law goodbye and returned to her gods, but Ruth clung to Naomi", "Orpah built an altar to God in Moab", "Orpah traveled to Egypt alone", "Orpah married a prince of Ammon"],
    optionsTelugu: ["ఓర్పా తన అత్తను ముద్దుపెట్టుకొని వెళ్ళిపోయెను, కానీ రూతు ఆమెను హత్తుకొనెను", "ఓర్పా మోయాబులో బలిపీఠము కట్టెను", "ఓర్పా ఐగుప్తునకు ఒంటరిగా వెళ్ళెను", "అమ్మోను రాజకుమారుని పెండ్లి చేసుకొనెను"],
    correctAnswer: "Orpah kissed her mother-in-law goodbye and returned to her gods, but Ruth clung to Naomi",
    bibleReference: "Ruth 1:14-15",
    explanation: "Orpah departed, but Ruth remained steadfast in friendship and covenant devotion.",
    explanationTelugu: "ఓర్పా తన అత్తను ముద్దుపెట్టుకొని వెళ్ళిపోయెను, కానీ రూతు ఆమెను హత్తుకొని నిలిచెను."
  },
  {
    easyQ: "What words of covenant allegiance did Ruth speak to Naomi in Ruth 1:16-17?",
    easyQTe: "రూతు 1:16-17 లో రూతు నయోమితో పలికిన అద్భుతమైన నిబంధన మాటలేవి?",
    medQ: "In Ruth 1:17, what severe oath did Ruth take to ensure only death would separate her from Naomi?",
    medQTe: "రూతు 1:17 లో మరణము తప్ప మరి ఏదియు వేరుచేయదని రూతు ఏ ప్రమాణము చేసెను?",
    hardQ: "How does Ruth's phrase \"Your God will be my God\" represent total conversion through faithful companionship?",
    hardQTe: "\"నీ దేవుడే నా దేవుడు\" అని రూతు పలికిన మాట ఆమె ఆత్మీయ పరివర్తనను ఎలా చాటుచున్నది?",
    options: ["\"Your people shall be my people, and your God my God; where you die I will die, and there will I be buried\"", "\"Give me my portion of silver and let me depart\"", "\"We shall return to Moab when the famine ends\"", "\"I will serve you until we cross the Jordan\""],
    optionsTelugu: ["\"నీ జనమే నా జనము, నీ దేవుడే నా దేవుడు; నీవు మరణించుచోటనే నేను మరణించెదను, అక్కడే పాతిపెట్టబడెదను\"", "\"నా వెండి భాగము నాకిచ్చి వెళ్ళనిమ్ము\"", "\"కరువు తీరిన తరువాత మోయాబునకు వెళ్లుదము\"", "\"యొర్దాను దాటువరకు నీకు సేవ చేసెదను\""],
    correctAnswer: "\"Your people shall be my people, and your God my God; where you die I will die, and there will I be buried\"",
    bibleReference: "Ruth 1:16-17",
    explanation: "Ruth's declaration is one of the highest biblical expressions of covenant loyalty.",
    explanationTelugu: "రూతు: నీ జనమే నా జనము, నీ దేవుడే నా దేవుడు అని నిష్కల్మషమైన విశ్వాసముతో పలికెను."
  },
  {
    easyQ: "At what agricultural season did Ruth and Naomi arrive in Bethlehem?",
    easyQTe: "రూతు మరియు నయోమి ఏ పంట కోత కాలములో బేత్లెహేమునకు వచ్చిరి?",
    medQ: "According to Ruth 1:22, what seasonal harvest provided divine provision for the two widows?",
    medQTe: "రూతు 1:22 ప్రకారం ఏ పంట కాలము ఆ ఇద్దరు విధవరాండ్రకు దైవిక సహాయమును సమకూర్చెను?",
    hardQ: "How does the timing of the barley harvest in Ruth 1:22 connect to the biblical Feast of Firstfruits?",
    hardQTe: "రూతు 1:22 లో యవల కోత కాలము ప్రారంభమగుట ప్రథమ ఫలముల పండుగతో ఏ సంబంధము కలిగియున్నది?",
    options: ["At the beginning of the barley harvest", "During the grape vintage in autumn", "At the wheat planting in winter", "During the olive shaking season"],
    optionsTelugu: ["యవల కోత ఆరంభమునందు", "ద్రాక్ష పండ్ల కోత కాలములో", "శీతాకాలపు గోధుమ విత్తు సమయములో", "ఒలీవ కాయలు రాల్చు సమయములో"],
    correctAnswer: "At the beginning of the barley harvest",
    bibleReference: "Ruth 1:22",
    explanation: "God's providence led Naomi and Ruth back to Bethlehem just as the barley harvest began.",
    explanationTelugu: "నయోమియు రూతును యవల కోత ఆరంభములో బేత్లెహేమునకు వచ్చిరి."
  },
  {
    easyQ: "Whose field did Ruth happen to glean in to gather grain for her friend and mother-in-law Naomi?",
    easyQTe: "తన అత్త నయోమి పోషణ కొరకు రూతు అనుకోకుండా ఎవరి పొలములో పరిగె ఏరుకొనెను?",
    medQ: "In Ruth 2:1-3, what was Boaz's relationship to Naomi's late husband Elimelech?",
    medQTe: "రూతు 2:1-3 ప్రకారం నయోమి భర్తయైన ఎలీమెలెకునకు బోయజు ఏ విధమైన బంధువు?",
    hardQ: "What legal rights under the Mosaic Law (Lev 19:9-10) did Ruth utilize to care for Naomi?",
    hardQTe: "ధర్మశాస్త్రము ప్రకారం (లేవీ 19:9-10) పేదలు పరిగె ఏరుకొను ఏ హక్కును రూతు ఉపయోగించెను?",
    options: ["Boaz, a prominent and wealthy relative of Elimelech", "Nabal the Carmelite", "Uriah the Hittite", "Barzillai the Gileadite"],
    optionsTelugu: ["ఎలీమెలెకు బంధువుడును బహు ధనవంతుడునైన బోయజు పొలము", "కర్మెలీయుడైన నాబాలు పొలము", "హిత్తీయుడైన ఊరియా పొలము", "గిలాదీయుడైన బర్జిల్లయి పొలము"],
    correctAnswer: "Boaz, a prominent and wealthy relative of Elimelech",
    bibleReference: "Ruth 2:1-3",
    explanation: "Providence led Ruth to the field belonging to Boaz, who was of the family of Elimelech.",
    explanationTelugu: "రూతు ఎలీమెలెకు వంశస్థుడైన బోయజునకు కలిగిన పొలములో పరిగె ఏరుకొనెను."
  },
  {
    easyQ: "What special favor did Boaz instruct his reapers to show toward Ruth in the field?",
    easyQTe: "పొలములో రూతు పట్ల ఏ విశేషమైన దయ చూపవలెనని బోయజు తన పనివారికి ఆజ్ఞాపించెను?",
    medQ: "In Ruth 2:15-16, what did Boaz command his harvesters to pull out from the bundles for Ruth?",
    medQTe: "రూతు 2:15-16 లో పనివారు ఓపులలోనుండి రూతు కొరకు దేనిని విడిచిపెట్టవలెనని బోయజు ఆజ్ఞాపించెను?",
    hardQ: "How did Boaz's instructions in Ruth 2:16 exceed the minimum legal requirements of the Law of Moses?",
    hardQTe: "రూతు 2:16 లో బోయజు చూపిన ఔదార్యము ధర్మశాస్త్రపు కనీసపు ఆజ్ఞలను ఎలా మించిపోయెను?",
    options: ["To pull out handfuls of grain from the bundles on purpose and leave them for her", "To give her a chariot of wheat", "To appoint her overseer of the harvesters", "To send her to glean in another village"],
    optionsTelugu: ["కట్టలలోనుండి కొన్ని పనలను ఆమెకొరకు కావాలని క్రింద పడవేసి విడిచిపెట్టవలెనని", "రథమునిండా గోధుమలు ఇవ్వవలెనని", "పనివారిపై అధికారిణిగా నియమించవలెనని", "వేరొక ఊరికి వెళ్ళి ఏరుకొనవలెనని"],
    correctAnswer: "To pull out handfuls of grain from the bundles on purpose and leave them for her",
    bibleReference: "Ruth 2:15-16",
    explanation: "Boaz commanded his men to let her glean even among the sheaves and drop grain intentionally for her.",
    explanationTelugu: "బోయజు: కట్టలమధ్యకూడ ఆమెను ఏరుకొననియ్యుడి, ఆమెకొరకు కొన్ని పనలు క్రింద పడవేయుడని ఆజ్ఞాపించెను."
  },
  {
    easyQ: "How much barley did Ruth bring home to Naomi after beating out what she gathered on day one?",
    easyQTe: "మొదటి దినమున ఏరుకొనిన పంటను నూర్చిన తరువాత రూతు నయోమియొద్దకు ఎంత యవలను తెచ్చెను?",
    medQ: "In Ruth 2:17, what biblical unit of dry measure was the barley Ruth beat out?",
    medQTe: "రూతు 2:17 లో రూతు నూర్చిన యవల పరిమాణము ఎంతని లేఖనములో చెప్పబడెను?",
    hardQ: "Approximately how many pounds/kilograms of barley does an ephah represent in ancient Israelite measures?",
    hardQTe: "ప్రాచీన ఇశ్రాయేలు కొలతల ప్రకారం ఒక తూము (ఏఫా) సుమారు ఎన్ని కిలోల ధాన్యముతో సమానము?",
    options: ["About an ephah of barley (approximately 30 to 40 pounds)", "One small handful only", "A single Omer", "Ten wagon loads"],
    optionsTelugu: ["సుమారు ఒక తూము (ఏఫా) యవలు", "ఒక దోసెడు మాత్రమే", "ఒక ఓమెరు మాత్రమే", "పది బండ్ల ధాన్యము"],
    correctAnswer: "About an ephah of barley (approximately 30 to 40 pounds)",
    bibleReference: "Ruth 2:17",
    explanation: "Ruth beat out what she gleaned and it was about an ephah of barley, an enormous harvest for a single day.",
    explanationTelugu: "రూతు తాను ఏరుకొనినదానిని నూర్చగా సుమారు ఒక తూము యవలాయెను."
  },
  {
    easyQ: "What did the women of Bethlehem say about Ruth when she gave birth to Obed?",
    easyQTe: "రూతు ఓబేదును కనినప్పుడు బేత్లెహేములోని స్త్రీలు నయోమితో రూతును గూర్చి ఏమనిరి?",
    medQ: "In Ruth 4:15, how did the neighbors describe Ruth's sacrificial value to Naomi?",
    medQTe: "రూతు 4:15 లో పొరుగు స్త్రీలు నయోమికి రూతుతో గల అనుబంధమును ఏమని కొనియాడిరి?",
    hardQ: "Why was the declaration \"better to you than seven sons\" an extraordinary biblical compliment in ancient Israel?",
    hardQTe: "ప్రాచీన ఇశ్రాయేలులో \"ఏడుగురు కుమారులకంటె శ్రేష్ఠురాలు\" అని పిలువబడుట ఏ విశిష్టమైన గౌరవమును చాటుచున్నది?",
    options: ["\"She is better to you than seven sons\"", "\"She will build great palaces in Moab\"", "\"She will lead Israel's armies into battle\"", "\"She will acquire all the gold of Gilead\""],
    optionsTelugu: ["\"ఏడుగురు కుమారులకంటె ఆమె నీకు శ్రేష్ఠురాలు\"", "\"ఆమె మోయాబులో రాజభవనములు కట్టును\"", "\"ఇశ్రాయేలు సైన్యములను నడిపించును\"", "\"గిలాదు బంగారమునంతటిని సంపాదించును\""],
    correctAnswer: "\"She is better to you than seven sons\"",
    bibleReference: "Ruth 4:15",
    explanation: "The women affirmed that Ruth's loving loyalty to Naomi exceeded the blessing of seven sons.",
    explanationTelugu: "నిన్ను ప్రేమించుచు ఏడుగురు కుమారులకంటె నీకు శ్రేష్ఠురాలైన నీ కోడలు ఆమెను కనెనని స్త్రీలు నయోమితో అనిరి."
  },
  {
    easyQ: "Who was the child born to Ruth and Boaz whom Naomi nursed and cared for?",
    easyQTe: "నయోమి తన ఒడిలో ఉంచుకొని పెంచిన రూతు మరియు బోయజుల కుమారుడు ఎవరు?",
    medQ: "In the royal genealogy of Ruth 4:17, Obed became the grandfather of which great king of Israel?",
    medQTe: "రూతు 4:17 లోని వంశావళి ప్రకారం ఓబేదు ఇశ్రాయేలులోని ఏ గొప్ప రాజునకు పితామహుడాయెను?",
    hardQ: "How did the lineage of Ruth the faithful friend lead directly into the Messianic genealogy of Matthew 1?",
    hardQTe: "మత్తయి 1 లోని మెస్సీయ వంశావళిలో నమ్మకమైన స్నేహితురాలైన రూతు స్థానము దేనిని స్పష్టము చేయుచున్నది?",
    options: ["Obed, the father of Jesse, who was the father of King David", "Solomon, builder of the temple", "Jonathan, son of Saul", "Samuel the prophet"],
    optionsTelugu: ["దావీదు తండ్రియైన యెష్షయిని కనిన ఓబేదు", "సొలొమోను", "యోనాతాను", "సమూయేలు ప్రవక్త"],
    correctAnswer: "Obed, the father of Jesse, who was the father of King David",
    bibleReference: "Ruth 4:17",
    explanation: "Obed was the father of Jesse, the father of King David, from whose line Jesus Christ was born.",
    explanationTelugu: "ఓబేదు దావీదు తండ్రియైన యెష్షయిని కనెను."
  },
  {
    easyQ: "What did Jesus say to His disciples in John 15:14 regarding how to be His friends?",
    easyQTe: "యోహాను 15:14 లో తనకు స్నేహితులై యుండుటకు ఏమి చేయవలెనని యేసు సెలవిచ్చెను?",
    medQ: "What is the spiritual condition of friendship with Christ according to John 15:14?",
    medQTe: "యోహాను 15:14 ప్రకారం క్రీస్తుతో స్నేహమునకు ఉండవలసిన ఆత్మీయ నిబంధన ఏది?",
    hardQ: "How does obedience to Christ's commandments establish covenant friendship rather than legalistic bondage?",
    hardQTe: "క్రీస్తు ఆజ్ఞలను గైకొనుట దాసత్వము కాక నిబంధన స్నేహముగా ఎలా పరిణమించును?",
    options: ["\"You are My friends if you do whatever I command you\"", "\"You are My friends if you memorize the law\"", "\"You are My friends if you give ten talents of gold\"", "\"You are My friends if you conquer cities\""],
    optionsTelugu: ["\"నేను మీకు ఆజ్ఞాపించువాటిని చేసినయెడల మీరు నా స్నేహితులై యుందురు\"", "\"ధర్మశాస్త్రమును కంఠస్థము చేసినయెడల\"", "\"పది తలాంతుల బంగారమిచ్చినయెడల\"", "\"పట్టణములను జయించినయెడల\""],
    correctAnswer: "\"You are My friends if you do whatever I command you\"",
    bibleReference: "John 15:14",
    explanation: "Jesus stated that loving obedience to His commandments is the hallmark of being His friend.",
    explanationTelugu: "నేను మీకు ఆజ్ఞాపించువాటిని చేసినయెడల మీరు నా స్నేహితులై యుందురని యేసు పలికెను."
  },
  {
    easyQ: "What message did Mary and Martha send to Jesus when their brother Lazarus fell sick in Bethany?",
    easyQTe: "బేతనియలో లాజరు రోగియైనప్పుడు మరియ మార్తలు యేసునకు ఏమని వర్తమానము పంపిరి?",
    medQ: "How did the sisters appeal to Jesus' personal friendship in John 11:3?",
    medQTe: "యోహాను 11:3 లో సహోదరీలు యేసుతో గల స్నేహమును బట్టి ఏమని విజ్ఞాపన చేసిరి?",
    hardQ: "Why did the sisters say \"he whom You love is sick\" rather than demanding an immediate miracle?",
    hardQTe: "అద్భుతము చేయుమని బలవంతము చేయక \"నీవు ప్రేమించువాడు రోగియై యున్నాడు\" అని వారు ఎందుకు పలికిరి?",
    options: ["\"Lord, behold, he whom You love is sick\"", "\"Lord, send fire from heaven\"", "\"Lord, make us wealthy in Bethany\"", "\"Lord, appoint Lazarus as ruler\""],
    optionsTelugu: ["\"ప్రభువా, ఇదిగో నీవు ప్రేమించువాడు రోగియై యున్నాడు\"", "\"పరలోకమునుండి అగ్నిని కురిపించుము\"", "\"మమ్మును ధనవంతులుగా చేయుము\"", "\"లాజరును అధిపతిగా నియమించుము\""],
    correctAnswer: "\"Lord, behold, he whom You love is sick\"",
    bibleReference: "John 11:3",
    explanation: "Mary and Martha appealed directly to Jesus' intimate, loving friendship with Lazarus.",
    explanationTelugu: "ప్రభువా, ఇదిగో నీవు ప్రేమించువాడు రోగియై యున్నాడని వారు యేసునకు కబురు పంపిరి."
  },
  {
    easyQ: "What did Jesus say in John 15:13 is the greatest proof of love for one's friends?",
    easyQTe: "యోహాను 15:13 లో స్నేహితులకొరకు చూపగల గొప్ప ప్రేమ ఏదని యేసు సెలవిచ్చెను?",
    medQ: "In John 15:13, how does laying down one's life define the ultimate standard of Christian friendship?",
    medQTe: "యోహాను 15:13 ప్రకారం స్నేహితులకొరకు ప్రాణము పెట్టుట క్రైస్తవ స్నేహమునకు ఏ అత్యున్నత ప్రమాణమును నిర్ణయించుచున్నది?",
    hardQ: "How does Jesus' declaration in John 15:13 foreshadow His substitutionary atonement on the cross?",
    hardQTe: "యోహాను 15:13 లో యేసు పలికిన మాట సిలువపై ఆయన చేసిన ప్రాయశ్చిత్త బలియాగమును ఎలా సూచించుచున్నది?",
    options: ["To lay down one's life for one's friends", "To build a memorial tower in Jerusalem", "To fast for forty consecutive days", "To bestow royal silver and gold"],
    optionsTelugu: ["తన స్నేహితులకొరకు తన ప్రాణము పెట్టుట", "యెరూషలేములో జ్ఞాపకార్థ గోపురము కట్టుట", "వరుసగా నలభై దినములు ఉపవాసముండుట", "వెండి బంగారములను బహుమతిగా ఇచ్చుట"],
    correctAnswer: "To lay down one's life for one's friends",
    bibleReference: "John 15:13",
    explanation: "Jesus declared that laying down one's life for friends is the supreme manifestation of love.",
    explanationTelugu: "తన స్నేహితులకొరకు తన ప్రాణము పెట్టువానికంటె ఎక్కువైన ప్రేమగలవాడెవడును లేడు."
  },
  {
    easyQ: "What short and powerful verse records Jesus weeping outside the tomb of His friend Lazarus?",
    easyQTe: "తన స్నేహితుడైన లాజరు సమాధి యొద్ద యేసు కన్నీరు కార్చెనని తెలుపు చిన్న వచనమేది?",
    medQ: "What is the theological significance of John 11:35 in demonstrating Christ's true human empathy?",
    medQTe: "యోహాను 11:35 లో యేసు కన్నీరు కార్చుట ఆయన మానవతాపూర్వక సహానుభూతిని ఎలా తెలియజేయుచున్నది?",
    hardQ: "How does Jesus' grief in John 11:35-38 reveal His emotional solidarity with grieving friends?",
    hardQTe: "యోహాను 11:35-38 లో యేసు దుఃఖపడుట దుఃఖించుచున్న స్నేహితులతో ఆయన ఏకాత్మతను ఎలా ప్రదర్శించుచున్నది?",
    options: ["\"Jesus wept\" (John 11:35)", "\"Pray without ceasing\"", "\"Rejoice always\"", "\"The Lord is my shepherd\""],
    optionsTelugu: ["\"యేసు కన్నీళ్లు విడిచెను\" (యోహాను 11:35)", "\"ఎడతెగక ప్రార్థన చేయుడి\"", "\"ఎల్లప్పుడును సంతోషముగా ఉండుడి\"", "\"యెహోవా నా కాపరి\""],
    correctAnswer: "\"Jesus wept\" (John 11:35)",
    bibleReference: "John 11:35",
    explanation: "Jesus wept at Lazarus' tomb, showing His deep emotional love and friendship.",
    explanationTelugu: "యేసు కన్నీళ్లు విడిచెను; తన స్నేహితునియెడల ఆయనకున్న గాఢమైన ప్రేమను ఇది చూపుచున్నది."
  },
  {
    easyQ: "What did the Jewish onlookers say when they saw Jesus weeping at Lazarus' tomb?",
    easyQTe: "లాజరు సమాధి యొద్ద యేసు కన్నీరు కార్చుట చూచిన యూదులు ఏమనిరి?",
    medQ: "In John 11:36, how did the surrounding crowd evaluate Jesus' affection for Lazarus?",
    medQTe: "యోహాను 11:36 లో గుమిగూడిన ప్రజలు లాజరుపై యేసుకున్న ప్రేమను ఎలా కొనియాడిరి?",
    hardQ: "What contrast existed between the crowd saying \"See how He loved him\" and those who questioned His power?",
    hardQTe: "\"ఇతనిని ఎంతగా ప్రేమించెనో చూడుడి\" అన్నవారికి మరియు ఆయన శక్తిని శంకించినవారికి గల వైరుధ్యమేమి?",
    options: ["\"See how He loved him!\"", "\"He has no authority here\"", "\"Let us return to Galilee\"", "\"He fears the Roman guards\""],
    optionsTelugu: ["\"చూడుడి, ఇతనిని ఎంతగా ప్రేమించెనో!\"", "\"ఇక్కడ ఈయనకు అధికారము లేదు\"", "\"గలీలయకు తిరిగి వెళ్లుదము\"", "\"ఈయన రోమా సైనికులకు భయపడుచున్నాడు\""],
    correctAnswer: "\"See how He loved him!\"",
    bibleReference: "John 11:36",
    explanation: "The onlookers recognized Jesus' profound love and personal grief for Lazarus.",
    explanationTelugu: "యూదులు: చూడుడి, ఇతనిని ఎంతగా ప్రేమించెనో అని చెప్పుకొనిరి."
  },
  {
    easyQ: "What did Mary do when Jesus arrived at their home in Bethany in Luke 10:39?",
    easyQTe: "లూకా 10:39 లో యేసు బేతనియలోని తమ ఇంటికి వచ్చినప్పుడు మరియ ఏమి చేసెను?",
    medQ: "How did Jesus commend Mary's posture of sitting at His feet over Martha's anxious distractions?",
    medQTe: "మార్త యొక్క ఆందోళనతో కూడిన సేవలకంటె తన పాదములయొద్ద కూర్చున్న మరియను యేసు ఎలా ప్రశంసించెను?",
    hardQ: "Why did Jesus call Mary's choice of sitting at His feet \"the good part which will not be taken away\"?",
    hardQTe: "యేసు పాదములయొద్ద కూర్చుని బోధ వినుటను \"ఉత్తమమైన భాగము\" అని ప్రభువు ఎందుకు పిలిచెను?",
    options: ["She sat at Jesus' feet and listened to His word", "She fled to the garden in fear", "She argued with the disciples", "She prepared twenty loaves of barley bread"],
    optionsTelugu: ["యేసు పాదములయొద్ద కూర్చుండి ఆయన బోధ వినుచుండెను", "భయముతో తోటలోనికి పారిపోయెను", "శిష్యులతో వాదించెను", "ఇరువది యవల రొట్టెలను సిద్ధపరచెను"],
    correctAnswer: "She sat at Jesus' feet and listened to His word",
    bibleReference: "Luke 10:39-42",
    explanation: "Mary chose the good part by sitting at Jesus' feet in intimate spiritual fellowship.",
    explanationTelugu: "మరియ యేసు పాదములయొద్ద కూర్చుండి ఆయన బోధ వినుచు ఉత్తమమైన భాగమును ఏర్పరచుకొనెను."
  },
  {
    easyQ: "How did four loyal friends bring a paralyzed man to Jesus in Capernaum when the doorway was blocked?",
    easyQTe: "కపెర్నహూములో ద్వారమునొద్ద సందులేనప్పుడు నలుగురు స్నేహితులు పక్షవాతపు రోగిని యేసునొద్దకు ఎలా తెచ్చిరి?",
    medQ: "In Mark 2:4, what structural barrier did the four friends dismantle to reach Jesus?",
    medQTe: "మార్కు 2:4 లో ఆ నలుగురు స్నేహితులు యేసునొద్దకు చేరుటకు ఏ పైకప్పును విప్పిరి?",
    hardQ: "What theological connection did Jesus make in Mark 2:5 between the friends' corporate faith and healing?",
    hardQTe: "మార్కు 2:5 లో స్నేహితుల విశ్వాసమునకు మరియు పాపక్షమాపణ స్వస్థతలకు యేసు ఏ సంబంధమును చూపెను?",
    options: ["By uncovering the roof and letting down the bed through the tiles", "By digging a tunnel under the house foundations", "By waiting three weeks outside the city gate", "By shouting through a trumpet from the rooftop"],
    optionsTelugu: ["ఇంటి పైకప్పు విప్పి, పక్షవాతపు రోగి పండుకొనియున్న మంచమును క్రిందికి దించిరి", "ఇంటి పునాదుల క్రింద సొరంగము తవ్వి", "పట్టణ ద్వారము వద్ద మూడు వారములు వేచియుండి", "మేడపైనుండి బాకా ఊది కేకలు వేసి"],
    correctAnswer: "By uncovering the roof and letting down the bed through the tiles",
    bibleReference: "Mark 2:4-5, Luke 5:19",
    explanation: "The four faithful friends removed the roof tiles to lower their paralyzed friend right before Jesus.",
    explanationTelugu: "వారు పైకప్పు విప్పి పక్షవాతపు రోగి పండుకొనియున్న మంచమును యేసు ఎదుట దించిరి."
  },
  {
    easyQ: "What did Jesus notice in Mark 2:5 before forgiving the sins of the paralyzed man?",
    easyQTe: "మార్కు 2:5 లో పక్షవాతపు రోగి పాపములను క్షమించుటకు ముందు యేసు దేనిని చూచెను?",
    medQ: "Whose faith prompted Jesus to speak words of pardon and restoration in Mark 2:5?",
    medQTe: "మార్కు 2:5 లో ఎవరి విశ్వాసమును చూచి యేసు పాపక్షమాపణ మరియు స్వస్థత మాటలు పలికెను?",
    hardQ: "How does the phrase \"When Jesus saw their faith\" highlight intercessory covenant friendship?",
    hardQTe: "\"యేసు వారి విశ్వాసమును చూచి\" అను మాట ఇతరులకొరకు చేయు విజ్ఞాపన విశ్వాసమును ఎలా వెల్లడించుచున్నది?",
    options: ["\"When Jesus saw their faith\"", "\"When Jesus saw their silver offerings\"", "\"When Jesus heard their loud singing\"", "\"When Jesus inspected their phylacteries\""],
    optionsTelugu: ["\"యేసు వారి విశ్వాసమును చూచి\"", "\"వారి వెండి కానుకలను చూచి\"", "\"వారి బిగ్గరగా పాడు పాటలను చూచి\"", "\"వారి ప్రార్థనా పట్టీలను పరీక్షించి\""],
    correctAnswer: "\"When Jesus saw their faith\"",
    bibleReference: "Mark 2:5",
    explanation: "Jesus was moved by the persistent, united faith of the four friends.",
    explanationTelugu: "యేసు వారి స్నేహితుల విశ్వాసమును చూచి: కుమారుడా, నీ పాపములు క్షమింపబడియున్నవని పలికెను."
  },
  {
    easyQ: "Who did the Roman centurion in Capernaum send to Jesus to say he was unworthy to have Christ under his roof?",
    easyQTe: "కపెర్నహూములోని రోమా శతాధిపతి తాను యేసును తన యింటిలోనికి చేర్చుకొనుటకు పాత్రుడను కానని చెప్పుటకు ఎవరిని పంపెను?",
    medQ: "In Luke 7:6, what message of humility did the centurion entrust to his close friends?",
    medQTe: "లూకా 7:6 లో శతాధిపతి తన స్నేహితుల ద్వారా యేసునకు ఏ వినయపూర్వకమైన సందేశమును పంపెను?",
    hardQ: "Why did the Roman centurion rely on trusted friends to communicate his faith to Jesus?",
    hardQTe: "రోమా శతాధిపతి తన విశ్వాస సందేశమును యేసునకు తెలియజేయుటకు నమ్మకమైన స్నేహితులను ఎందుకు ఆశ్రయించెను?",
    options: ["His trusted friends", "A detachment of legionary cavalry", "The high priest from Jerusalem", "Two Phoenician merchants"],
    optionsTelugu: ["తన ప్రియ స్నేహితులను", "సైనిక అశ్వదళమును", "యెరూషలేము ప్రధాన యాజకుని", "ఇద్దరు ఫెనీకేయ వర్తకులను"],
    correctAnswer: "His trusted friends",
    bibleReference: "Luke 7:6",
    explanation: "The centurion sent his friends to express his deep humility and extraordinary faith.",
    explanationTelugu: "శతాధిపతి స్నేహితులను పంపి: ప్రభువా, శ్రమపడవద్దు, నీవు నా యింటిలోనికి వచ్చుటకు నేను పాత్రుడను కానని చెప్పెను."
  },
  {
    easyQ: "In Jesus' parable in Luke 11:5-8, at what hour did a man go to his friend's house asking for three loaves?",
    easyQTe: "లూకా 11:5-8 లోని ఉపమానములో ఒక మనుష్యుడు మూడు రొట్టెల కొరకు తన స్నేహితుని యొద్దకు ఏ వేళలో వెళ్లెను?",
    medQ: "Why did the man need three loaves of bread from his friend in Luke 11:6?",
    medQTe: "లూకా 11:6 లో ఆ మనుష్యునికి మూడు రొట్టెలు ఎందుకు అవసరమయ్యెను?",
    hardQ: "What principle of persistent, shameless audacity (anaideia) in prayer did Jesus teach through this parable of friends?",
    hardQTe: "లూకా 11:8 లో స్నేహితుని ఉపమానము ద్వారా ప్రార్థనలో మానక వేడుకొను ఏ ప్రాముఖ్యమైన సత్యమును యేసు బోధించెను?",
    options: ["At midnight", "At the third hour in the morning", "At high noon", "At sunset"],
    optionsTelugu: ["అర్ధరాత్రివేళ", "ఉదయము మూడవ గంటకు", "మధ్యాహ్న సమయమున", "సూర్యాస్తమయమున"],
    correctAnswer: "At midnight",
    bibleReference: "Luke 11:5-8",
    explanation: "The man visited his friend at midnight to provide hospitality for a traveling guest.",
    explanationTelugu: "ఒకడు అర్ధరాత్రివేళ తన స్నేహితునియొద్దకు వెళ్లి: స్నేహితుడా, నాకు మూడు రొట్టెలు బదులిమ్మని అడిగెను."
  },
  {
    easyQ: "What symbolic action did Elijah perform when he called Elisha to follow him as disciple and companion?",
    easyQTe: "ఎలీషాను తన శిష్యునిగా, తోడుగా పిలిచినప్పుడు ఏలీయా ఏ సూచనాత్మకమైన క్రియ చేసెను?",
    medQ: "In 1 Kings 19:19, what was Elisha doing when Elijah threw his mantle upon him?",
    medQTe: "1 రాజులు 19:19 లో ఏలీయా తన దుప్పటిని ఎలీషాపై వేసినప్పుడు ఎలీషా ఏమి చేయుచుండెను?",
    hardQ: "What did the casting of Elijah's mantle signify regarding succession and prophetic companionship?",
    hardQTe: "ఏలీయా తన దుప్పటిని ఎలీషాపై వేయుట ప్రవచన పరిచర్యలో ఏ సంపూర్ణ వారసత్వమును సూచించెను?",
    options: ["He threw his mantle (cloak) upon him", "He poured sacred oil on his feet", "He handed him a golden staff", "He wrote his name on a scroll"],
    optionsTelugu: ["తన దుప్పటిని అతనిపై వేసెను", "అతని పాదములపై పరిమళ తైలము పోసెను", "బంగారు దండమును చేతికిచ్చెను", "గ్రంథపు సుట్టపై అతని పేరు రాసెను"],
    correctAnswer: "He threw his mantle (cloak) upon him",
    bibleReference: "1 Kings 19:19",
    explanation: "Elijah threw his mantle over Elisha, calling him into prophetic partnership and lifelong friendship.",
    explanationTelugu: "ఏలీయా అతని దాటిపోవుచు తన దుప్పటిని అతనిపై వేసి పరిచర్యలోనికి పిలిచెను."
  },
  {
    easyQ: "What solemn vow did Elisha make three times refusing to leave Elijah at Bethel, Jericho, and Jordan?",
    easyQTe: "బేతేలు, యెరికో, యొర్దానుల యొద్ద ఏలీయాను విడిచిపెట్టనని ఎలీషా మూడుసార్లు చేసిన ప్రమాణమేది?",
    medQ: "In 2 Kings 2:2, 4, 6, what exact phrase did Elisha repeat to demonstrate unbreakable loyalty to Elijah?",
    medQTe: "2 రాజులు 2:2, 4, 6 లో ఏలీయా పట్ల తన అచంచలమైన నమ్మకత్వమును చాటుచు ఎలీషా పదేపదే పలికిన మాటలేవి?",
    hardQ: "How does Elisha's refusal to part from Elijah parallel Ruth's devotion to Naomi?",
    hardQTe: "ఏలీయాను విడిచిపెట్టనని ఎలీషా చేసిన ప్రతిజ్ఞ నయోమి పట్ల రూతు చూపిన భక్తితో ఎలా సరిపోలుచున్నది?",
    options: ["\"As the Lord lives, and as your soul lives, I will not leave you!\"", "\"I will return to my plow in Abel-meholah\"", "\"Give me ten talents of silver before you depart\"", "\"Let us build an altar here at Gilgal\""],
    optionsTelugu: ["\"యెహోవా జీవముతోడు, నీ జీవముతోడు, నేను నిన్ను విడువను!\"", "\"ఆబేల్మెహోలాలోని నా నాగలియొద్దకు వెళ్ళెదను\"", "\"నీవు వెళ్ళుటకు ముందు పది తలాంతుల వెండినిమ్ము\"", "\"గిల్గాలులో బలిపీఠము కట్టుదము\""],
    correctAnswer: "\"As the Lord lives, and as your soul lives, I will not leave you!\"",
    bibleReference: "2 Kings 2:2, 4, 6",
    explanation: "Elisha swore by the living Lord that he would never abandon his master and friend Elijah.",
    explanationTelugu: "ఎలీషా: యెహోవా జీవముతోడు నీ జీవముతోడు నేను నిన్ను విడువనని ప్రమాణము చేసెను."
  }
];

// Helper to fill remaining facts up to 50 for foundation, growth, mastery
function createRichBank(startFacts, topicSeed, prefix) {
  const result = [...startFacts];
  const bibData = [
    // 31-50 Foundation
    ["Elisha asking for a double portion of Elijah's spirit", "ఎలీషా ఏలీయా ఆత్మలో రెండు పాళ్ళు కోరుట", "2 Kings 2:9", "A double portion of your spirit", "నీ ఆత్మలో రెండు పాళ్ళు", "Elisha requested the spiritual inheritance of a firstborn son from his mentor and companion.", "ఎలీషా తన ఆత్మీయ తండ్రి మరియు స్నేహితుడైన ఏలీయానుండి ఆత్మలో రెండు పాళ్ళు కోరెను."],
    ["Elisha crying out as Elijah was taken up in a whirlwind", "ఏలీయా సుడిగాలిలో కొనిపోబడినప్పుడు ఎలీషా కేకలు వేయుట", "2 Kings 2:12", "\"My father, my father! The chariots of Israel and its horsemen!\"", "\"నా తండ్రీ, నా తండ్రీ, ఇశ్రాయేలు రథమును రౌతులును!\"", "Elisha mourned the departure of his beloved prophetic father and friend.", "ఎలీషా: నా తండ్రీ నా తండ్రీ అని కేకలు వేసి ఏలీయా ఎడబాటునకు విలపించెను."],
    ["Barnabas introducing newly converted Saul to the apostles in Jerusalem", "యెరూషలేములో మారుమనస్సు పొందిన సౌలును అపొస్తలులకు బర్నబా పరిచయము చేయుట", "Acts 9:27", "Barnabas, who vouched for Saul's genuine conversion", "సౌలు నిజమైన విశ్వాసమును గూర్చి సాక్ష్యమిచ్చిన బర్నబా", "Barnabas befriended Saul when others feared him and brought him to the apostles.", "సౌలును చూచి అందరు భయపడుచుండగా బర్నబా అతనిని చేరదీసి అపొస్తలులయొద్దకు తెచ్చెను."],
    ["Barnabas traveling to Tarsus to bring Saul to Antioch", "సౌలును పిలుచుకొని వచ్చుటకు బర్నబా తార్సునకు వెళ్ళుట", "Acts 11:25-26", "To seek Saul and bring him to Antioch for ministry", "సౌలును వెదకి పరిచర్య కొరకు అంతియొకయకు తోడుకొని వచ్చుటకు", "Barnabas sought out Saul to partner together in teaching the church in Antioch.", "బర్నబా తార్సునకు వెళ్లి సౌలును కనుగొని అంతియొకయకు పిలుచుకొని వచ్చెను."],
    ["Paul and Silas praying and singing hymns in the Philippian jail", "ఫిలిప్పీ చెరసాలలో పౌలు సీలలు ప్రార్థించుచు కీర్తనలు పాడుట", "Acts 16:25", "At midnight, praying and singing hymns to God", "అర్ధరాత్రివేళ ప్రార్థించుచు దేవుని స్తుతించుచుండిరి", "The two friends worshiped together in prison, encouraging fellow prisoners.", "పౌలు సీలలు బంధకములలో కూడ కలిసి ప్రార్థించి దేవుని స్తుతించిరి."],
    ["The great earthquake shaking the foundations of the prison in Philippi", "ఫిలిప్పీ చెరసాల పునాదులు కదులునట్లు గొప్ప భూకంపము కలుగుట", "Acts 16:26", "All prison doors opened and everyone's bonds unfastened", "చెరసాల ద్వారములన్నియు తెరచుకొని బంధకములు ఊడెను", "God miraculously freed the faithful missionary companions in Philippi.", "దేవుడు ఆ నమ్మకమైన సహచరుల పక్షమున గొప్ప విడుదల కలుగజేసెను."],
    ["The Philippian jailer washing Paul and Silas' wounds and rejoicing", "ఫిలిప్పీ చెరసాల నాయకుడు పౌలు సీలల గాయములను కడిగి ఆనందించుట", "Acts 16:33-34", "He washed their wounds and set food before them", "వారి గాయములను కడిగి వారికి భోజనము పెట్టెను", "The jailer cared tenderly for the apostles after coming to faith.", "చెరసాల నాయకుడు రక్షణ పొంది ఆ రాత్రివేళనే వారి గాయములను కడిగి ఆదరించెను."],
    ["Priscilla and Aquila risking their lives for Paul", "పౌలు ప్రాణముకొరకు ప్రిస్కిల్ల అకుల్ల తమ ప్రాణములను ఒడ్డుట", "Romans 16:3-4", "They risked their own necks for Paul's life", "పౌలు ప్రాణముకొరకు తమ మెడలను ఒడ్డిరి", "Paul praised this married couple who were his loyal co-workers and friends.", "ప్రిస్కిల్ల అకుల్ల అను సహచరులు పౌలు నిమిత్తము తమ ప్రాణములను పణముగా పెట్టిరి."],
    ["Timothy serving with Paul in the Gospel like a son with his father", "కుమారుడు తండ్రికి సేవ చేయునట్లు తిమోతి పౌలుతో కలిసి సువార్త సేవ చేయుట", "Philippians 2:22", "Like a son with his father, he has served with me", "కుమారుడు తండ్రికి చేసినట్లు నాతో కలిసి సువార్త పరిచర్య చేసెను", "Paul commended Timothy's genuine care and unmatched loyalty.", "తిమోతి పౌలుతో తండ్రీకొడుకులవలె కలిసి నమ్మకముగా సేవ చేసెను."],
    ["Epaphroditus risking his life to minister to Paul's needs", "పౌలు కొరతను తీర్చుటకు ఎపఫ్రొదితు తన ప్రాణమును లెక్కచేయక సేవ చేయుట", "Philippians 2:25-30", "He nearly died for the work of Christ to assist Paul", "పౌలునకు పరిచర్య చేయుటకు క్రీస్తు పని నిమిత్తము ప్రాణమునకు తెగించెను", "Epaphroditus was Paul's brother, co-worker, and faithful companion.", "ఎపఫ్రొదితు పౌలు యొక్క సహోదరుడును జతపనివాడును నమ్మకమైన స్నేహితుడునై యుండెను."],
    ["Luke remaining with Paul in his final Roman imprisonment", "పౌలు చివరి రోమా చెరసాలలో లూకా మాత్రమే అతనితో ఉండుట", "2 Timothy 4:11", "\"Only Luke is with me\"", "\"లూకా మాత్రమే నాయొద్ద ఉన్నాడు\"", "Luke the beloved physician stayed faithfully by Paul's side until the end.", "అందరు విడిచిపోయినను ప్రియ వైద్యుడైన లూకా మాత్రమే పౌలుతో నమ్మకముగా నిలిచెను."],
    ["Onesiphorus searching eagerly for Paul in Rome without shame of his chains", "రోమా బంధకములలో ఉన్న పౌలును గూర్చి సిగ్గుపడక ఒనేసిఫోరు వెదకి ఆదరించుట", "2 Timothy 1:16-17", "He often refreshed Paul and was not ashamed of his chain", "పౌలు సంకెళ్లను గూర్చి సిగ్గుపడక అనేకసార్లు ఆదరించెను", "Onesiphorus proved his unwavering friendship in Paul's darkest hour.", "ఒనేసిఫోరు పౌలు బంధకములలో ఉన్నప్పుడు సిగ్గుపడక అతనిని ఆదరించి బలపరచెను."],
    ["Paul asking Philemon to receive runaway slave Onesimus as a beloved brother", "పారిపోయిన దాసుడైన ఒనేసిమును ప్రియ సహోదరునిగా చేర్చుకొనుమని పౌలు ఫిలేమోనును కోరుట", "Philemon 1:16-17", "\"Receive him as you would receive me\"", "\"నన్ను చేర్చుకొనినట్లు అతనిని చేర్చుకొనుము\"", "Paul appealed to Philemon's friendship to forgive and elevate Onesimus.", "పౌలు ఫిలేమోనుతో గల స్నేహమును బట్టి ఒనేసిమును సహోదరునిగా చేర్చుకొనుమనెను."],
    ["Daniel urging Hananiah, Mishael, and Azariah to plead for God's mercy", "దైవిక దయకొరకు ప్రార్థించుమని దానియేలు తన ముగ్గురు స్నేహితులను కోరుట", "Daniel 2:17-18", "To seek mercies from the God of heaven concerning this secret", "ఆ మర్మము విషయములో పరలోకపు దేవుని కనికరమును వేడుకొనుటకు", "Daniel and his companions united in crisis prayer in Babylon.", "దానియేలు హనన్యా మీషాయేలు అజర్యా అను స్నేహితులు కలిసి దేవుని కనికరము కొరకు ప్రార్థించిరి."],
    ["Shadrach, Meshach, and Abednego refusing to bow to Nebuchadnezzar's golden image", "నెబుకద్నెజరు బంగారు ప్రతిమకు సాగిలపడుటకు షద్రకు మేషకు అబేద్నెగోలు నిరాకరించుట", "Daniel 3:16-18", "\"Our God whom we serve is able to deliver us\"", "\"మేము సేవించుచున్న దేవుడు మమ్మును రక్షించుటకు సమర్థుడు\"", "The three Hebrew friends stood boldly together against idolatry.", "ఆ ముగ్గురు స్నేహితులు ప్రాణభయమునకు వెరవక దేవుని పట్ల నమ్మకముగా నిలిచిరి."],
    ["The fourth person walking with the three friends in the fiery furnace", "అగ్నిగుండములో ఆ ముగ్గురు స్నేహితులతో నడచుచున్న నాల్గవ వ్యక్తి", "Daniel 3:25", "\"Like the Son of God\"", "\"దేవపుత్రుని పోలినవాడు\"", "The Son of God joined the three companions in the midst of their trial.", "దేవుని కుమారుడు అగ్నిగుండములో ఆ ముగ్గురు స్నేహితులకు తోడుగా నడచెను."],
    ["Jethro offering wise counsel to his son-in-law Moses in the wilderness", "అరణ్యములో మోషేకు మామయైన యిత్రో చక్కని జ్ఞానోపదేశము చేయుట", "Exodus 18:17-24", "To appoint capable men as judges over thousands and hundreds", "వేలమీదను నూర్లమీదను న్యాయాధిపతులను నియమించుమని", "Jethro's loving counsel relieved Moses of an unbearable burden.", "యిత్రో మోషేపై గల భారమును తగ్గించుటకు న్యాయాధిపతులను నియమించుమనెను."],
    ["Aaron and Hur holding up Moses' hands until sunset at Rephidim", "రెఫీదీములో సూర్యాస్తమయము వరకు అహరోను హూరులు మోషే చేతులను పైకెత్తి పట్టుకొనుట", "Exodus 17:12", "Aaron and Hur supported his hands, one on one side and one on the other", "అహరోను హూరులు ఒకరు ఒకవైపున ఒకరు మరియొకవైపున మోషే చేతులను ఆదుకొనిరి", "Victory over Amalek came through faithful, united companionship.", "అహరోను హూరుల ఐక్యతతో కూడిన ఆసరా ద్వారా ఇశ్రాయేలు అమాలేకీయులపై జయము పొందెను."],
    ["The Lord speaking to Moses face to face as a friend speaks to his friend", "ఒకడు తన స్నేహితునితో మాటలాడునట్లు యెహోవా మోషేతో ముఖాముఖిగా మాటలాడుట", "Exodus 33:11", "\"Face to face, as a man speaks to his friend\"", "\"మనుష్యుడు తన స్నేహితునితో మాటలాడునట్లు ముఖాముఖిగా\"", "God granted Moses the intimacy of divine covenant friendship.", "దేవుడు మోషేతో తన స్నేహితునితోవలె ముఖాముఖిగా మాటలాడెను."],
    ["Abraham called the friend of God through trusting faith", "విశ్వాసము ద్వారా అబ్రాహాము దేవుని స్నేహితుడని పిలువబడుట", "James 2:23, Isaiah 41:8", "\"He was called God's friend\"", "\"దేవుని స్నేహితుడని పిలువబడెను\"", "Abraham's unwavering faith in God earned him the eternal title of God's friend.", "అబ్రాహాము దేవుని నమ్మినందున అతడు దేవుని స్నేహితుడని పిలువబడెను."]
  ];

  for (let i = 0; i < bibData.length && result.length < 50; i++) {
    const item = bibData[i];
    result.push({
      easyQ: `What biblical event occurred regarding ${item[0]}?`,
      easyQTe: `${item[1]} గూర్చి బైబిలులో జరిగిన ప్రధాన సంఘటన ఏది?`,
      medQ: `According to ${item[2]}, what specific detail is recorded about this faithful companionship?`,
      medQTe: `${item[2]} లేఖనము ప్రకారం ఈ విశ్వాస సహవాసమును గూర్చి వ్రాయబడిన వివరమేమి?`,
      hardQ: `What theological lesson does ${item[2]} teach believers regarding divine covenant friendship?`,
      hardQTe: `${item[2]} ప్రకారం దేవుని నిబంధన స్నేహమును గూర్చి విశ్వాసులు నేర్చుకొనవలసిన ఆత్మీయ సత్యమేమి?`,
      options: [item[3], "An altar of stones in Moab", "A royal army from Damascus", "A decree of forty days fasting"],
      optionsTelugu: [item[4], "మోయాబులోని రాతి బలిపీఠము", "దమస్కు సైన్యము", "నలభై దినముల ఉపవాస ఆజ్ఞ"],
      correctAnswer: item[3],
      bibleReference: item[2],
      explanation: item[5],
      explanationTelugu: item[6]
    });
  }

  return result;
}

// 50 Growth Facts (Proverbs, Psalms, and Gospel Friendship)
function buildGrowthFacts() {
  const data = [
    ["Proverbs 17:17 on the loyalty of a true friend", "సామెతలు 17:17 నిజమైన స్నేహితుని నమ్మకత్వము", "Proverbs 17:17", "\"A friend loves at all times, and a brother is born for adversity\"", "\"నిజమైన స్నేహితుడు ఎల్లప్పుడును ప్రేమించును, ఆపత్కాలమునందు సహోదరుడుగా ఉండును\"", "Solomon teaches that genuine friendship endures through every storm.", "నిజమైన స్నేహితుడు ఎల్లప్పుడు ప్రేమించును, శ్రమలలో సహోదరునిగా నిలుచును."],
    ["Proverbs 18:24 on the friend who sticks closer than a brother", "సామెతలు 18:24 సహోదరునికంటె ఎక్కువగా హత్తుకొను స్నేహితుడు", "Proverbs 18:24", "\"There is a friend who sticks closer than a brother\"", "\"సహోదరునికంటెను ఎక్కువగా హత్తుకొను స్నేహితుడు కలడు\"", "Christ ultimately fulfills this proverb as the faithful friend who never leaves.", "సహోదరునికంటె ఎక్కువగా హత్తుకొను స్నేహితుడు ప్రభువైన యేసే."],
    ["Proverbs 27:6 on the wounds of a friend", "సామెతలు 27:6 మేలుచేయు స్నేహితుని గాయములు", "Proverbs 27:6", "\"Faithful are the wounds of a friend; deceitful are the kisses of an enemy\"", "\"స్నేహితుడు గాయములు రేపినను అవి నమ్మకమైనవి; శత్రువు ముద్దులు పెట్టుకొన్నను అవి మోసకరమైనవి\"", "Loving rebuke from a godly friend brings life and correction.", "స్నేహితుడు చేయు గద్దింపు మేలుకొరకేయని సామెతలు సెలవిచ్చుచున్నది."],
    ["Proverbs 27:9 on the sweetness of earnest counsel", "సామెతలు 27:9 స్నేహితుని మధురమైన ఆలోచన", "Proverbs 27:9", "\"The sweetness of a friend comes from his earnest counsel\"", "\"స్నేహితుని హృదయపూర్వకమైన ఆలోచన మధురమైనది\"", "Heartfelt counsel from a wise friend gladdens the inner soul.", "స్నేహితుని హితవచనములు హృదయమునకు అమృతమువలె ఆనందమునిచ్చును."],
    ["Proverbs 27:10 on not forsaking family friends", "సామెతలు 27:10 స్నేహితుని విడిచిపెట్టకూడదను ఆజ్ఞ", "Proverbs 27:10", "\"Do not forsake your friend and your father's friend\"", "\"నీ స్నేహితునినైనను నీ తండ్రి స్నేహితునినైనను విడిచిపెట్టవద్దు\"", "Generational loyalty in friendship reflects divine faithfulness.", "తరతరముల స్నేహసంబంధములను కాపాడుకొనవలెనని లేఖనము ఆజ్ఞాపించుచున్నది."],
    ["Proverbs 27:17 on iron sharpening iron", "సామెతలు 27:17 ఇనుము ఇనుమునకు పదునుపెట్టు విధము", "Proverbs 27:17", "\"As iron sharpens iron, so one person sharpens another\"", "\"ఇనుముచేత ఇనుము పదునగును, అట్లు ఒకడు తన చెలికానికి పదునుపెట్టును\"", "Spiritual companions sharpen one another's character and wisdom.", "క్రైస్తవ స్నేహితులు ఒకరినొకరు ఆత్మీయముగా బలపరచుకొనవలెను."],
    ["Proverbs 13:20 on walking with the wise", "సామెతలు 13:20 జ్ఞానులతో సహవాసము చేయుట", "Proverbs 13:20", "\"Whoever walks with the wise becomes wise, but the companion of fools suffers harm\"", "\"జ్ఞానుల సహవాసము చేయువాడు జ్ఞానము గలవాడగును; మూర్ఖుల సహవాసము చేయువాడు చెడిపోవును\"", "Our close companions directly shape our character and destiny.", "మనం చేసే సహవాసమే మన భవిష్యత్తును నిర్ణయించును."],
    ["Proverbs 16:28 on the destructive whisperer", "సామెతలు 16:28 స్నేహితులను వేరుపరచు కొండెగాడు", "Proverbs 16:28", "\"A dishonest man spreads strife, and a whisperer separates close friends\"", "\"కొండెగాడు ప్రాణస్నేహితులను వేరుపరచును\"", "Gossip and slander tear apart the most precious friendships.", "చాడీలు చెప్పువాడు అత్యంత సన్నిహిత స్నేహితులను విడదీయును."],
    ["Proverbs 19:4 on wealth and false companions", "సామెతలు 19:4 సిరిసంపదలు మరియు స్నేహితులు", "Proverbs 19:4", "\"Wealth brings many friends, but poverty drives them away\"", "\"ధనము స్నేహితులను పెంచును, బీదవాడు తన స్నేహితునిచేత విడువబడును\"", "Worldly friends gather around money, but godly friends love unconditionally.", "లోక స్నేహితులు ధనమును చూచి వత్తురు, నిజమైన స్నేహితుడు నిస్వార్థముగా ప్రేమించును."],
    ["Proverbs 22:11 on gracious speech winning royal friends", "సామెతలు 22:11 మనోహరముగా మాటలాడువానికి రాజు స్నేహితుడగుట", "Proverbs 22:11", "\"One who loves a pure heart and who speaks with grace will have the king for a friend\"", "\"హృదయశుద్ధిని కోరుచు దయగా మాటలాడువానికి రాజు స్నేహితుడగును\"", "Pure hearts and gracious words open doors of honorable companionship.", "హృదయశుద్ధిగలవానికి ఉన్నతమైన స్నేహములు లభించును."],
    ["Proverbs 22:24 warning against friendship with the angry", "సామెతలు 22:24 కోపచిత్తునితో స్నేహము చేయవద్దను హెచ్చరిక", "Proverbs 22:24-25", "\"Do not make friends with a hot-tempered man, do not associate with one easily angered\"", "\"కోపచిత్తునితో సాంగత్యము చేయకుము, క్రోధముగల మనుష్యునితో సహవాసము చేయకుము\"", "Anger is contagious and traps the unwary companion.", "కోపిష్టితో స్నేహము చేసినయెడల మనమును ఆ ఉరిలో పడెదము."],
    ["Ecclesiastes 4:9-10 on two being better than one", "ప్రసంగి 4:9-10 ఒంటరిగా ఉండుటకంటె ఇద్దరు కూడియుండుట శ్రేష్ఠము", "Ecclesiastes 4:9-10", "\"Two are better than one, because they have a good return for their labor\"", "\"ఒంటరిగా ఉండుటకంటె ఇద్దరు కూడియుండుట మేలు; ఒకడు పడినను రెండవవాడు లేవనెత్తును\"", "God designed believers for mutual support and fellowship.", "ఒకడు బలహీనపడినప్పుడు మరియొకడు ఆదుకొనుటకు సహవాసము అవసరము."],
    ["Ecclesiastes 4:12 on the three-ply cord", "ప్రసంగి 4:12 ముప్పిరి త్రాడు త్వరగా తెగిపోదను ఉపమానము", "Ecclesiastes 4:12", "\"A cord of three strands is not quickly broken\"", "\"ముప్పిరి త్రాడు త్వరగా తెగిపోదు\"", "When Christ is the third strand in a friendship, it cannot be broken.", "క్రీస్తు కేంద్రముగా గల సహవాసము ఎన్నటికిని విడిపోదు."],
    ["Job's three friends coming from afar to comfort him", "యోబును ఓదార్చుటకు దూరమునుండి వచ్చిన ముగ్గురు స్నేహితులు", "Job 2:11", "Eliphaz the Temanite, Bildad the Shuhite, and Zophar the Naamathite", "తేమానీయుడైన ఎలీఫజు, షూహీయుడైన బిల్దదు, నయమాతీయుడైన జోఫరు", "Job's friends came together by appointment to mourn with him.", "యోబు శ్రమలలో పాలుపంచుకొనుటకు ఆ ముగ్గురు స్నేహితులు కూడివచ్చిరి."],
    ["Job's friends sitting in silent sympathy for seven days", "యోబు స్నేహితులు ఏడు దినములు మౌనముగా కూర్చుండుట", "Job 2:13", "They sat on the ground with him seven days and seven nights in silence", "ఏడు రాత్రింబగళ్లు నేలమీద అతనితోకూడ కూర్చుండి ఒక్క మాటయైన పలుకలేదు", "True sympathy often begins with silent presence in deep grief.", "తీవ్రమైన దుఃఖములో మౌనముగా తోడుగా ఉండుటయే గొప్ప ఓదార్పు."],
    ["Job 6:14 on withholding kindness from a suffering friend", "యోబు 6:14 శ్రమలలో ఉన్న స్నేహితునికి దయ చూపకపోవుట", "Job 6:14", "\"Anyone who withholds kindness from a friend forsakes the fear of the Almighty\"", "\"శ్రమనొందినవాడు సర్వశక్తునియందలి భయభక్తులు విడిచినను వాని స్నేహితుడు వానికి దయచూపవలెను\"", "Job reminded his friends that compassion is owed to those in despair.", "శ్రమలో ఉన్న స్నేహితుని పట్ల కనికరము చూపుట దేవుని భయమునకు నిదర్శనము."],
    ["Job calling his three accusers miserable comforters", "తన స్నేహితులను వ్యర్థమైన ఓదార్పుదారులని యోబు పిలుచుట", "Job 16:2", "\"Miserable comforters are you all!\"", "\"మీరందరు వ్యర్థమైన ఓదార్పుదారులు!\"", "Harsh theological judgment fails to bring genuine comfort.", "కనికరము లేని ఖండనలు గాయపడిన హృదయమును ఓదార్చలేవు."],
    ["Job crying out that his close friends detest him", "తన ఆప్త స్నేహితులు తన్ను అసహ్యించుకొనుచున్నారని యోబు రోదించుట", "Job 19:19", "\"All my close friends detest me; those I love have turned against me\"", "\"నా ప్రాణస్నేహితులందరు నన్ను అసహ్యించుకొనుచున్నారు\"", "Job suffered the painful rejection of those he loved dearly.", "యోబు శ్రమలలో తన ఆప్తమిత్రుల నిరాకరణను అనుభవించెను."],
    ["God commanding Job's friends to offer sacrifices for their wrong words", "యోబు స్నేహితులు తమ తప్పు మాటలకొరకు బలులు అర్పించవలెనని దేవుడు ఆజ్ఞాపించుట", "Job 42:7-8", "To offer seven bulls and seven rams, and Job will pray for you", "ఏడు ఎడ్లను ఏడు పొట్టేళ్లను తీసికొని బలి అర్పింపవలెనని, యోబు ప్రార్థన చేయవలెనని", "God vindicated Job and demanded repentance from his three companions.", "దేవుడు యోబు స్నేహితుల అజ్ఞానపు మాటలను గద్దించి పశ్చాత్తాపపడమనెను."],
    ["The Lord restoring Job's fortunes when he prayed for his friends", "యోబు తన స్నేహితులకొరకు ప్రార్థించినప్పుడు దేవుడు అతనిని రెండంతలుగా దీవించుట", "Job 42:10", "\"The Lord restored Job's fortunes when he prayed for his friends\"", "\"యోబు తన స్నేహితులకొరకు ప్రార్థన చేసినప్పుడు యెహోవా అతని క్షేమస్థితిని మరల రప్పించెను\"", "Forgiving and praying for hurting friends unlocks divine restoration.", "స్నేహితులను క్షమించి ప్రార్థించినప్పుడు దేవుడు యోబునకు రెండంతల దీవెనలు ఇచ్చెను."],
    ["Hushai the Archite returning to Jerusalem as David's loyal friend", "దావీదు ఆప్తమిత్రుడైన హూషై యెరూషలేమునకు తిరిగి వెళ్ళుట", "2 Samuel 15:32-37", "Hushai the Archite, David's friend, agreed to defeat Absalom's counsel", "దావీదు స్నేహితుడైన హూషై అబ్షాలోము ఆలోచనను భంగపరచుటకు వెళ్లెను", "Hushai risked his life to serve as David's loyal ally during Absalom's rebellion.", "హూషై తన ప్రాణమును తెగించి దావీదు రక్షణ కొరకు నమ్మకముగా నిలిచెను."],
    ["Hushai defeating the wise counsel of traitor Ahithophel", "ద్రోహియైన అహీతోఫెలు ఆలోచనను హూషై భంగపరచుట", "2 Samuel 17:14", "The Lord had ordained to defeat the good counsel of Ahithophel", "అహీతోఫెలు చెప్పిన యుక్తిగల ఆలోచనను యెహోవా భంగపరచెను", "God used a faithful friend to dismantle treacherous counsel.", "దేవుడు ఒక నమ్మకమైన స్నేహితుని ద్వారా శత్రువుల కుతంత్రములను లయపరచెను."],
    ["Barzillai the Gileadite providing abundant food and bedding for David at Mahanaim", "మహనయీములో దావీదునకు బర్జిల్లయి భోజన వసతులను సమకూర్చుట", "2 Samuel 17:27-29", "He brought beds, basins, wheat, barley, honey, and sheep for the weary", "అలసిపోయిన దావీదు సైన్యమునకు పరుపులను, గోధుమలను, తేనెను, గొర్రెలను తెచ్చెను", "Barzillai showed generous hospitality to the fleeing king and his men.", "బర్జిల్లయి కష్టకాలములో దావీదునకు నిస్వార్థముగా సహాయము చేసెను."],
    ["King David inviting elderly Barzillai to reside at the royal palace", "వృద్ధుడైన బర్జిల్లయిని రాజభవనములో నివసించుమని దావీదు ఆహ్వానించుట", "2 Samuel 19:33", "\"Come over with me, and I will provide for you with me in Jerusalem\"", "\"నాతోకూడ రమ్ము, యెరూషలేములో నిన్ను పోషించెదను\"", "David sought to honor the friend who stood by him in adversity.", "ఆపత్కాలములో ఆదుకొన్న స్నేహితుని ఘనపరచుటకు దావీదు కోరెను."],
    ["Barzillai sending his son Chimham to receive David's royal favor", "తన కుమారుడైన కింహామును దావీదు వద్దకు బర్జిల్లయి పంపుట", "2 Samuel 19:37-38", "Chimham crossed over with the king to receive his blessing", "కింహాము రాజుతోకూడ నది దాటి రాజ దయను పొందెను", "Generational blessings followed the faithfulness of Barzillai's friendship.", "బర్జిల్లయి చూపిన నమ్మకత్వము అతని కుమారునికి ఆశీర్వాదకరమాయెను."],
    ["Hiram King of Tyre maintaining perpetual friendship with King David", "సోరు రాజైన హీరాము దావీదుతో నిత్య స్నేహము కలిగియుండుట", "1 Kings 5:1", "Hiram was always a lover (friend) of David", "హీరాము ఎల్లప్పుడును దావీదును ప్రేమించినవాడు (స్నేహితుడు)", "Hiram's diplomatic and personal friendship aided Israel's peace.", "హీరాము దావీదును మనసారా ప్రేమించిన నమ్మకమైన పొరుగు రాజై యుండెను."],
    ["Hiram supplying cedar logs from Lebanon for Solomon's temple", "సొలొమోను దేవాలయము కొరకు హీరాము దేవదారు మ్రానులను సరఫరా చేయుట", "1 Kings 5:8-10", "He supplied Solomon with all the timber of cedar and cypress he desired", "సొలొమోను కోరినట్లు దేవదారు మ్రానులను సరళపు మ్రానులను పంపెను", "Friendship between kings enabled the building of the house of the Lord.", "స్నేహ సంబంధముల ద్వారా దేవుని ఆలయ నిర్మాణమునకు కావలసిన సామాగ్రి సమకూరెను."],
    ["Amnon listening to the deceptive counsel of his shrewd friend Jonadab", "తన మోసకరమైన స్నేహితుడైన యోనాదాబు దురాలోచనను అమ్నోను వినుట", "2 Samuel 13:3-5", "Jonadab, son of Shimeah, was a very shrewd and crafty friend", "యోనాదాబు బహు యుక్తిపరుడైన స్నేహితుడు", "Evil companions entice souls into destructive, sinful paths.", "దుష్టులైన స్నేహితుల సహవాసము వినాశనమునకు దారితీయును."],
    ["Jonadab plotting the downfall of Tamar through deceit", "మోసముతో తామారును అణగద్రొక్కుటకు యోనాదాబు పన్నిన పన్నాగము", "2 Samuel 13:5", "To pretend to be sick and lure his sister into his chamber", "రోగివలె నటించి తన సహోదరిని లోనికి రప్పించుకొనుమని చెప్పెను", "False friends encourage wickedness rather than righteousness.", "చెడ్డ స్నేహితులు పాపము చేయుటకు ప్రోత్సహింతురు."],
    ["Psalm 41:9 prophesying betrayal by a trusted companion", "కీర్తన 41:9 నమ్మకమైన స్నేహితుడు మోసము చేయునను ప్రవచనము", "Psalm 41:9", "\"Even my close friend in whom I trusted, who ate my bread, has lifted his heel against me\"", "\"నేను నమ్ముకొనిన నా ప్రాణస్నేహితుడు నా యింట భోజనము చేసినవాడే నామీద మడమ యెత్తెను\"", "Jesus quoted this prophetic psalm regarding Judas' betrayal at the Last Supper.", "యేసు ఈ వచనమును యూదా యొక్క ద్రోహమును గూర్చి స్వయముగా ఉదహరించెను."],
    ["Psalm 55:13 mourning the agonizing wound of companion betrayal", "కీర్తన 55:13 ప్రాణస్నేహితుని నమ్మకద్రోహమునకు రోదించుట", "Psalm 55:13-14", "\"It is you, a man my equal, my companion, my familiar friend\"", "\"నా సమస్నేహితుడవు, నా చెలికాడవు, నా ప్రాణమిత్రుడవునైన నీవే!\"", "Betrayal by an intimate friend cuts deeper than attacks from sworn enemies.", "శత్రువు చేయు నిందకంటె స్నేహితుడు చేయు ద్రోహము మిక్కిలి వేదనకరమైనది."],
    ["Judas Iscariot identifying Jesus with the deceptive sign of a kiss", "యూదా ఇస్కరియోతు ముద్దుతో ప్రభువైన యేసును పట్టియిచ్చుట", "Matthew 26:48-49", "\"Whomever I kiss, He is the One; seize Him\"", "\"నేనెవరిని ముద్దుపెట్టుకొందునో ఆయనే, ఆయనను పట్టుకొనుడి\"", "The most sacred gesture of friendship was twisted into betrayal.", "స్నేహ చిహ్నమైన ముద్దు ద్రోహపు సంకేతముగా మార్చబడెను."],
    ["Jesus answering Judas with grace in the Garden of Gethsemane", "గెత్సేమనే తోటలో యూదాతో యేసు దయతో మాటలాడుట", "Matthew 26:50", "\"Friend, why have you come?\"", "\"స్నేహితుడా, నీవు చేయవచ్చినది చేయుము\"", "Even facing betrayal, Christ addressed Judas with dignified sorrow.", "ద్రోహము చేయవచ్చిన యూదాను కూడ యేసు \"స్నేహితుడా\" అని పిలిచెను."],
    ["The disciples arguing over who was greatest at the Passover table", "పస్కా భోజన బల్లయొద్ద శిష్యులు తమలో ఎవరు గొప్ప అని వాదించుకొనుట", "Luke 22:24", "A dispute arose among them as to which of them was considered greatest", "తమలో ఎవడు గొప్పవాడుగా ఎంచబడవలెనో అను వివాదము వారిలో పుట్టెను", "Selfish ambition threatens the unity of spiritual brotherhood.", "స్వార్థపూరితమైన ఆధిక్యత సహవాసములో విభేదములను తెచ్చును."],
    ["Jesus washing His disciples' feet as a masterclass in loving service", "యేసు శిష్యుల పాదములను కడుగుట ద్వారా చూపిన దాసత్వపు ప్రేమ", "John 13:14-15", "\"You also ought to wash one another's feet\"", "\"మీరును ఒకరి పాదములను ఒకరు కడుగవలసినదే\"", "True Christian friendship is proven through humble, sacrificial service.", "ఒకరికొకరు పాదములు కడుగుకొనుటయే నిజమైన క్రైస్తవ స్నేహ లక్షణము."],
    ["The disciple whom Jesus loved reclining next to Him at supper", "యేసు ప్రేమించిన ప్రియ శిష్యుడు భోజన పంక్తిలో ఆయన రొమ్మున ఆనుకొనుట", "John 13:23", "Reclining on Jesus' bosom, one of His disciples whom Jesus loved", "యేసు ప్రేమించిన శిష్యులలో ఒకడు ఆయన రొమ్మున ఆనుకొనుచుండెను", "John enjoyed an intimate, trusted friendship with the Lord.", "యోహాను యేసునకు అత్యంత ప్రియమైన స్నేహితునిగా ఆయన రొమ్మున ఆనుకొనెను."],
    ["Peter and John running together toward the empty garden tomb", "పేతురు యోహానులు కలిసి ఖాళీ సమాధి వైపు పరుగెత్తుట", "John 20:3-4", "\"So they both ran together, but the other disciple outran Peter\"", "\"వారిద్దరు కలిసి పరుగెత్తుచుండిరి, ఆ రెండవ శిష్యుడు పేతురుకంటె త్వరగా పరుగెత్తెను\"", "The two apostolic companions shared the revelation of the resurrection.", "ఆ ఇద్దరు శిష్యులు కలిసి పరుగెత్తి పునరుత్థాన సాక్ష్యమును కనుగొనిరి."],
    ["John waiting outside and Peter entering the tomb first", "యోహాను బయట నిలువగా పేతురు మొదట సమాధిలోనికి వెళ్ళుట", "John 20:5-6", "Simon Peter came following him, and went into the tomb", "సీమోను పేతురు ఆయనను వెంబడించి వచ్చి సమాధిలో ప్రవేశించెను", "Different temperaments complement one another in Christian companionship.", "విభిన్న స్వభావములు గల స్నేహితులు ఒకరికొకరు తోడుగా నిలిచిరి."],
    ["Jesus restoring Peter with threefold questions of love by Galilee", "గలీలయ సముద్ర తీరమున పేతురును ప్రేమ ప్రశ్నలతో యేసు పునరుద్ధరించుట", "John 21:15-17", "\"Simon, son of Jonah, do you love Me? Feed My lambs\"", "\"సీమోనూ, నీవు నన్ను ప్రేమించుచున్నావా? నా గొర్రెపిల్లలను మేపుము\"", "Christ heals broken fellowship through tender reconciliation.", "యేసు పేతురు యొక్క ద్రోహమును క్షమించి తన ప్రేమతో పునరుద్ధరించెను."],
    ["Peter inquiring about the future of his fellow disciple John", "తన తోటి శిష్యుడైన యోహాను భవిష్యత్తును గూర్చి పేతురు విచారించుట", "John 21:21", "\"Lord, what about this man?\"", "\"ప్రభువా, ఇతని సంగతి ఏమగును?\"", "Jesus told Peter to focus on following Him rather than comparing paths.", "ఇతరులతో పోల్చుకొనక తనను మాత్రమే వెంబడించుమని యేసు పేతురుతో అనెను."],
    ["The Holy Spirit calling Barnabas and Saul to be missionary companions", "బర్నబా సౌలులను మిషనరీ సహచరులుగా పరిశుద్ధాత్మ వేరుపరచుట", "Acts 13:2", "\"Set apart for Me Barnabas and Saul for the work to which I have called them\"", "\"నేను బర్నబాను సౌలును పిలిచిన పనికొరకు వారిని నాకు ప్రత్యేకపరచుడి\"", "The Holy Spirit commissions pairs of believers for fruitful ministry.", "దేవుడు జంటగా సేవ చేయుటకు బర్నబా సౌలులను ప్రత్యేకపరచెను."],
    ["Paul and Barnabas tearing their robes at Lystra to refuse pagan worship", "లుస్త్రలో తమకు పూజ చేయబోగా పౌలు బర్నబాలు బట్టలు చింపుకొనుట", "Acts 14:14", "They tore their clothes and ran in among the multitude", "తమ వస్త్రములు చింపుకొని సమూహములోనికి పరుగెత్తిరి", "True ministry partners safeguard God's glory together.", "దేవుని మహిమను దొంగిలించక ఆ ఇద్దరు సహచరులు విగ్రహారాధనను తిరస్కరించిరి."],
    ["The sharp disagreement between Paul and Barnabas over John Mark", "మార్కు విషయములో పౌలు బర్నబాల మధ్య కలిగిన తీవ్ర వాదము", "Acts 15:37-39", "A sharp disagreement arose so that they parted company", "వారిలో తీవ్ర వివాదము కలిగి ఒకరినొకరు విడిచిపోయిరి", "Even mature believers can face strong relational differences in mission.", "పరిచర్యలో అభిప్రాయ భేదములు వచ్చినను దేవుని సువార్త ఆగలేదు."],
    ["Barnabas taking John Mark to Cyprus to encourage him", "మార్కును వెంటబెట్టుకొని బర్నబా కుప్రకు ఓడ ఎక్కి వెళ్ళుట", "Acts 15:39", "Barnabas took Mark with him and sailed away to Cyprus", "బర్నబా మార్కును వెంటబెట్టుకొని కుప్రకు ఓడ ఎక్కి పోయెను", "Barnabas believed in restoring young ministers when others doubted.", "ఓడిపోయిన యవ్వనస్తుని ఆదుకొని బలపరచిన ఓదార్పు కుమారుడు బర్నబా."],
    ["Paul later commanding Timothy to bring Mark because he is useful", "మార్కు పరిచర్యకు ప్రయోజనకరమని పౌలు తరువాత పిలిపించుట", "2 Timothy 4:11", "\"Get Mark and bring him with you, for he is useful to me for ministry\"", "\"మార్కును వెంటబెట్టుకొని రమ్ము, అతడు పరిచర్య నిమిత్తము నాకు ప్రయోజనకరమై యున్నాడు\"", "Restored friendship bore lasting fruit in the writing of the Gospel.", "ఒకప్పుడు విడిపోయిన మార్కు పౌలుకు బహు ప్రియమైన జతపనివాడాయెను."],
    ["Tychicus described as a beloved brother and faithful minister", "తుకికు అను నమ్మకమైన సేవకుని పౌలు ప్రశంసించుట", "Ephesians 6:21-22", "A beloved brother and faithful minister in the Lord", "ప్రభువునందు ప్రియ సహోదరుడును నమ్మకమైన పరిచారకుడునైన తుకికు", "Paul trusted faithful companions to communicate his apostolic heart.", "పౌలు తన ఆత్మీయ క్షేమసమాచారములను తెలుపుటకు తుకికును పంపెను."],
    ["Aristarchus sharing Paul's dangerous voyage and Roman chains", "అరిస్తార్కు పౌలుతోపాటు సముద్ర ప్రయాణములోను బంధకములలోను పాలుపొందుట", "Acts 27:2, Colossians 4:10", "Aristarchus my fellow prisoner greets you", "నాతోకూడ చెరసాలలో ఉన్న అరిస్తార్కు మీకు వందనములు చెప్పుచున్నాడు", "Loyal friends endure persecution and prison alongside their leaders.", "అరిస్తార్కు పౌలు శ్రమలలోను సంకెళ్లలోను తోడుగా నిలిచిన ధైర్యశాలి."],
    ["Epaphras agonizing in prayer for the spiritual maturity of the church", "ఎపఫ్రా తన సంఘ విశ్వాసుల ఆత్మీయ ఎదుగుదల కొరకు ప్రార్థనలో పోరాడుట", "Colossians 4:12", "Always laboring earnestly for you in his prayers", "ఎల్లప్పుడును తన ప్రార్థనలలో మీకొరకు పోరాడుచున్నాడు", "The deepest friendship is expressed through persistent intercession.", "విశ్వాసుల సంపూర్ణత కొరకు ప్రార్థనలో పోరాడుటయే నిజమైన ఆత్మీయ స్నేహము."],
    ["Gaius commended by the apostle John for showing hospitable care to traveling brothers", "ప్రయాణికులైన సహోదరులకు ఆతిథ్యమిచ్చినందుకు గాయును యోహాను ప్రశంసించుట", "3 John 1:5-8", "\"You do faithfully whatever you do for the brethren and for strangers\"", "\"సహోదరులకును పరదేశులకును నీవు చేయుచున్నదంతయు నమ్మకముగా చేయుచున్నావు\"", "Hospitality toward strangers displays Christian friendship in action.", "పరదేశులైన విశ్వాసులకు ఆతిథ్యమిచ్చుట దేవుని స్నేహమును ప్రకటించుటయే."],
    ["Demetrios having a good testimony from all believers and the truth itself", "దేమేత్రి అను సహోదరునికి సత్యమువలనను అందరివలనను మంచి సాక్ష్యము కలుగుట", "3 John 1:12", "\"Demetrius has a good testimony from all, and from the truth itself\"", "\"దేమేత్రి అందరివలనను సత్యమువలనను మంచి సాక్ష్యము పొందినవాడు\"", "Consistent integrity builds an unshakeable reputation in fellowship.", "యథార్థ ప్రవర్తన సహవాసములో గొప్ప నమ్మకత్వమును తెచ్చును."]
  ];

  return data.map((item, idx) => ({
    easyQ: `What teaching or example is recorded regarding ${item[0]}?`,
    easyQTe: `${item[1]} గూర్చి బైబిలులో ఇవ్వబడిన బోధ లేదా మాదిరి ఏది?`,
    medQ: `In ${item[2]}, what specific instruction is given concerning Christian friendship?`,
    medQTe: `${item[2]} లో క్రైస్తవ స్నేహమును గూర్చి ఏ స్పష్టమైన ఆజ్ఞ ఇవ్వబడెను?`,
    hardQ: `What theological truth does ${item[2]} reveal about walking in biblical community?`,
    hardQTe: `${item[2]} లేఖనము ప్రకారం ఆత్మీయ సహవాసములో జీవించుటకు గల దైవిక ఉద్దేశ్యమేమి?`,
    options: [item[3], "To live in isolated mountain fortresses", "To accumulate ten wagons of silver", "To observe three years of silent contemplation"],
    optionsTelugu: [item[4], "కొండ కోటలలో ఏకాంతముగా జీవించుట", "పది బండ్ల వెండిని సమకూర్చుకొనుట", "మూడు సంవత్సరములు మౌనదీక్ష పూనుట"],
    correctAnswer: item[3],
    bibleReference: item[2],
    explanation: item[5],
    explanationTelugu: item[6]
  }));
}

// 50 Mastery Facts (Epistles, Advanced Exegesis, Canonical Unity)
function buildMasteryFacts() {
  const data = [
    ["3 John 1:14 on greeting close friends personally by name", "3 యోహాను 1:14 స్నేహితులను పేరుపేరున పలకరించుట", "3 John 1:14", "\"Greet the friends by name\"", "\"స్నేహితులను పేరుపేరున వందనములు చెప్పుము\"", "True Christian pastoral friendship values each individual soul personally.", "క్రైస్తవ స్నేహములో ప్రతి ఒక్కరిని వ్యక్తిగతముగా ప్రేమించి పలకరించవలెను."],
    ["James 4:4 declaring friendship with the world is hostility toward God", "యాకోబు 4:4 లోకస్నేహము దేవునితో శత్రుత్వమను హెచ్చరిక", "James 4:4", "\"Friendship with the world is enmity with God\"", "\"ఈ లోకస్నేహము దేవునితో శత్రుత్వమని మీరు ఎరుగరా?\"", "Believers cannot divide loyalty between worldly corruption and God.", "లోకముతో స్నేహము చేయువాడు దేవునికి శత్రువగునని యాకోబు హెచ్చరించుచున్నాడు."],
    ["Galatians 6:2 on fulfilling the law of Christ through bearing burdens", "గలతీయులకు 6:2 ఒకరి భారములను ఒకరు భరించి క్రీస్తు ధర్మశాస్త్రమును నెరవేర్చుట", "Galatians 6:2", "\"Bear one another's burdens, and so fulfill the law of Christ\"", "\"ఒకరి భారముల నొకరు భరించి, ఈలాగు క్రీస్తు నియమమును సంపూర్ణముగా నెరవేర్చుడి\"", "Mutual burden-bearing is the practical fulfillment of Christ's love.", "ఒకరికొకరు భారములలో తోడుపడుటయే క్రీస్తు ప్రేమను నెరవేర్చుట."],
    ["Hebrews 10:24-25 on encouraging one another in assembling together", "హెబ్రీ 10:24-25 ఒకరినొకరు హెచ్చరించుకొనుచు సమాజముగా కూడుకొనుట", "Hebrews 10:24-25", "\"Not forsaking the assembling of ourselves together... but encouraging one another\"", "\"సమాజముగా కూడుట మానక, ఒకరినొకరు హెచ్చరించుకొనుచు ప్రేమకు పురికొల్పుదము\"", "Fellowship protects believers from drifting into spiritual apathy.", "సహవాసము విశ్వాసులను ఆత్మీయ పతనమునుండి కాపాడును."],
    ["1 Thessalonians 5:11 on building each other up", "1 థెస్సలొనీకయులకు 5:11 ఒకరినొకరు ఆదరించి క్షేమాభివృద్ధి కలుగజేయుట", "1 Thessalonians 5:11", "\"Therefore comfort each other and edify one another, just as you also are doing\"", "\"కాబట్టి మీరు ఒకరినొకరు ఆదరించి, ఒకనికొకడు క్షేమాభివృద్ధి కలుగజేయుడి\"", "Daily encouragement strengthens faith in the midst of trials.", "నిత్యము ఒకరినొకరు ఆదరించుకొనుట సంఘమునకు క్షేమకరము."],
    ["Romans 12:10 on brotherly devotion and honoring companions", "రోమీయులకు 12:10 సహోదరప్రేమ విషయములో ఒకరినొకరు గౌరవించుకొనుట", "Romans 12:10", "\"Be kindly affectionate to one another with brotherly love, in honor giving preference to one another\"", "\"సహోదరప్రేమ విషయములో ఒకనియందొకడు అనురాగము గలవారై, ఘనతవిషయములో ఒకనినొకడు గొప్పగా ఎంచుకొనుడి\"", "Christians compete not for personal praise, but in honoring others.", "ఒకరినొకరు ఘనపరచుకొనుటలో క్రైస్తవ స్నేహము వెలుగుచున్నది."],
    ["Romans 12:15 on empathetic sharing of joys and sorrows", "రోమీయులకు 12:15 సంతోషించువారితో సంతోషించి ఏడ్చువారితో ఏడ్చుట", "Romans 12:15", "\"Rejoice with those who rejoice, and weep with those who weep\"", "\"సంతోషించువారితో సంతోషించుడి; ఏడ్చువారితో ఏడువుడి\"", "True fellowship enters deeply into both the triumphs and heartbreaks of companions.", "స్నేహితుల సంతోషములోను దుఃఖములోను పాలుపంచుకొనుటయే నిజమైన అనురాగము."],
    ["Romans 16:7 commending Andronicus and Junia as fellow prisoners", "రోమీయులకు 16:7 ఆత్మీయ బంధువులును తోటి ఖైదీలైన అంద్రొనీకు యూనియాలను పొగడుట", "Romans 16:7", "\"My fellow prisoners, who are of note among the apostles\"", "\"నాతోకూడ చెరసాలలో ఉండిన నా బంధువులైన అంద్రొనీకునకును యూనియాకును వందనములు\"", "Paul honored companions who stood with him in gospel persecution.", "సువార్త నిమిత్తము తనతోపాటు చెరసాల పాలైన స్నేహితులను పౌలు స్మరించుకొనెను."],
    ["Romans 16:13 greeting Rufus and his mother who mothered Paul", "రోమీయులకు 16:13 రూఫును మరియు పౌలుకు తల్లియైన అతని తల్లిని వందనము చేయుట", "Romans 16:13", "\"Greet Rufus, chosen in the Lord, and his mother and mine\"", "\"ప్రభువునందు ఏర్పరచబడిన రూఫునకును, నాకును తల్లియైన అతని తల్లికిని వందనములు\"", "The family of God expands to provide mothers and brothers in the faith.", "విశ్వాసములో ఇతరులను తల్లివలె కుమారునివలె ప్రేమించు ఆత్మీయ కుటుంబము."],
    ["1 Corinthians 15:33 warning that bad company corrupts good morals", "1 కొరింథీయులకు 15:33 దుష్టసాంగత్యము మంచి నడవడిని చెరుపునను సత్యము", "1 Corinthians 15:33", "\"Do not be deceived: Evil company corrupts good habits\"", "\"మోసపోకుడి; దుష్టసాంగత్యము మంచి నడవడిని చెరుపును\"", "Spiritual discernment must govern our closest associations.", "చెడ్డ స్నేహములు మన మంచి విశ్వాస జీవితమును పాడుచేయును."],
    ["1 Corinthians 16:17-18 on refreshing the spirit of apostolic workers", "1 కొరింథీయులకు 16:17-18 అపొస్తలుని ఆత్మను తేటపరచిన సహోదరులు", "1 Corinthians 16:17-18", "\"They supplied what was lacking on your part; for they refreshed my spirit and yours\"", "\"వారు నా ఆత్మకును మీ ఆత్మకును విశ్రాంతి కలుగజేసిరి\"", "Visiting faithful companions revives exhausted leaders.", "విశ్వాసుల రాకడ దైవజనుల ఆత్మకు విశ్రాంతిని బలమును తెచ్చును."],
    ["2 Corinthians 2:13 on Paul having no rest because brother Titus was absent", "2 కొరింథీయులకు 2:13 తీతు కనబడనందున పౌలునకు మనశ్శాంతి లేకపోవుట", "2 Corinthians 2:13", "\"I had no rest in my spirit, because I did not find Titus my brother\"", "\"నా సహోదరుడైన తీతు నాకు కనబడనందున నా మనస్సునకు విశ్రాంతి లేకపోయెను\"", "Even great apostles experience deep emotional longing for their co-workers.", "పౌలు తన జతపనివాడైన తీతు సహవాసము కొరకు ఎంతగానో పరితపించెను."],
    ["2 Corinthians 7:6 on God comforting the downcast through a friend's arrival", "2 కొరింథీయులకు 7:6 తీతు రాకడ ద్వారా కృంగినవారిని దేవుడు ఆదరించుట", "2 Corinthians 7:6", "\"God, who comforts the downcast, comforted us by the coming of Titus\"", "\"కృంగినవారిని ఆదరించు దేవుడు తీతు రాకడవలన మమ్మును ఆదరించెను\"", "God often channels divine comfort through the presence of a loving friend.", "దేవుడు ఒక స్నేహితుని రాకడ ద్వారా మన కృంగిన హృదయములను లేవనెత్తును."],
    ["Philippians 1:7 on partners sharing God's grace in imprisonment and defense", "ఫిలిప్పీయులకు 1:7 బంధకములలోను సువార్త సమర్థనలోను కృపలో పాలుపొందుట", "Philippians 1:7", "\"You all are partakers with me of grace, both in my chains and in defense\"", "\"నా బంధకములలోను సువార్త సమర్థనలోను మీరందరు నాతోకూడ కృపలో పాలివారై యున్నారు\"", "True Christian partnership shares both suffering and grace.", "క్రీస్తు సేవకులు శ్రమలలోను జయములోను సమానముగా పాలుపొందుదురు."],
    ["Philippians 4:3 urging the true yokefellow to reconcile Euodia and Syntyche", "ఫిలిప్పీయులకు 4:3 యువొదియ సుంటుకేలను సమాధానపరచుటకు తోడ్పడుట", "Philippians 4:3", "\"Help these women who labored with me in the gospel\"", "\"సువార్త పనిలో నాతోకూడ ప్రయాసపడిన ఆ స్త్రీలకు సహాయము చేయుము\"", "Peacemakers in the fellowship protect ministry co-workers from division.", "సహవాసములో వివాదములు వచ్చినప్పుడు సమాధానపరచు స్నేహితులు అవసరము."],
    ["Colossians 4:9 affirming Onesimus as a faithful and beloved brother", "కొలొస్సయులకు 4:9 ఒనేసిమును నమ్మకమైన ప్రియ సహోదరునిగా పరిచయము చేయుట", "Colossians 4:9", "\"Onesimus, a faithful and beloved brother, who is one of you\"", "\"మీలో ఒకడును నమ్మకమైన ప్రియ సహోదరుడునైన ఒనేసిము\"", "Grace elevates former runaway slaves into beloved equals in Christ.", "క్రీస్తు ప్రేమ ఒకనాటి బానిసను ప్రియ సహోదరునిగా మార్చివేసెను."],
    ["2 Timothy 4:10 on the grief of Demas loving the present world and deserting Paul", "2 తిమోతి 4:10 దేమా ఇహలోకమును ప్రేమించి పౌలును విడిచిపోవుట", "2 Timothy 4:10", "\"Demas has forsaken me, having loved this present world\"", "\"దేమా యీ లోకమును ప్రేమించి నన్ను విడిచి థెస్సలొనీకకు వెళ్లెను\"", "Worldly allurements can seduce companions away from holy callings.", "లోకాశలకు లోనైనప్పుడు కొందరు స్నేహితులు నమ్మకద్రోహము చేయుదురు."],
    ["2 Timothy 4:16 on human desertion at Paul's first defense in Caesar's court", "2 తిమోతి 4:16 కైసరు ఎదుట పౌలు మొదటి విచారణలో అందరు విడిచిపోవుట", "2 Timothy 4:16", "\"At my first defense no one stood with me, but all forsook me\"", "\"నేను మొదటిసారి సమాధానము చెప్పినప్పుడు ఎవడును నా పక్షమున నిలువలేదు, అందరును నన్ను విడిచిపోయిరి\"", "Human friends may fail in the fiery trial, but Christ remains faithful.", "మనుష్యులు భయపడి విడిచిపోయినను దేవుడు మన పక్షమున నిలుచును."],
    ["2 Timothy 4:17 on the Lord standing with Paul and granting strength", "2 తిమోతి 4:17 ప్రభువు పౌలు పక్కన నిలిచి అతనిని బలపరచుట", "2 Timothy 4:17", "\"But the Lord stood with me and strengthened me\"", "\"అయినను ప్రభువు నా పక్కన నిలిచి నన్ను బలపరచెను\"", "When all earthly companions flee, the Lord Himself stands by His servant.", "అందరు విడిచినను ప్రభువైన యేసు నమ్మకమైన స్నేహితునిగా తోడైయుండును."],
    ["Philemon 1:7 on refreshing the hearts of the saints through love", "ఫిలేమోను 1:7 ప్రేమ ద్వారా పరిశుద్ధుల హృదయములకు విశ్రాంతి కలుగుట", "Philemon 1:7", "\"The hearts of the saints have been refreshed by you, brother\"", "\"సహోదరుడా, నీ ప్రేమవలన పరిశుద్ధుల హృదయములు విశ్రాంతి పొందినవి\"", "Generous love brings profound refreshment to the weary family of faith.", "స్నేహితుని ఉదారమైన ప్రేమ విశ్వాసుల హృదయములకు ఓదార్పునిచ్చును."],
    ["Exodus 33:11 on Joshua not departing from the tent of meeting", "నిర్గమకాండము 33:11 యెహోషువ ప్రత్యక్షపు గుడారమును విడిచిపోకుండుట", "Exodus 33:11", "\"His servant Joshua the son of Nun, a young man, did not depart from the tabernacle\"", "\"నూను కుమారుడైన యెహోషువ అను యౌవనస్థుడైన అతని పరిచారకుడు గుడారములోనుండి వెలుపలికి రాలేదు\"", "Faithful companions linger in the secret place of divine glory.", "మోషేకు నమ్మకమైన పరిచారకుడైన యెహోషువ ప్రత్యక్షపు గుడారమును అంటిపెట్టుకొనియుండెను."],
    ["Numbers 14:6-9 on Joshua and Caleb standing together against ten fearful spies", "సంఖ్యాకాండము 14:6-9 పదిమంది అవిశ్వాస వేగులవారికి ఎదురుగా యెహోషువ కాలేబులు నిలుచుట", "Numbers 14:6-9", "\"The Lord is with us. Do not fear them!\"", "\"యెహోవా మనకు తోడైయున్నాడు, వారికి భయపడకుడి\"", "Two godly companions held fast to faith when an entire nation faltered.", "అందరూ భయపడినను ఆ ఇద్దరు స్నేహితులు దేవునియందు విశ్వాసముంచి నిలిచిరి."],
    ["Joshua 14:14 on Caleb receiving Hebron because he followed God wholeheartedly", "యెహోషువ 14:14 కాలేబు పూర్ణహృదయముతో దేవుని వెంబడించినందున హెబ్రోనును పొందుట", "Joshua 14:14", "\"Hebron became the inheritance of Caleb because he wholly followed the Lord\"", "\"అతడు పూర్ణహృదయముతో ఇశ్రాయేలీయుల దేవుడైన యెహోవాను వెంబడించెను\"", "Godly companions share the joy of fulfilled promises in their old age.", "యౌవనమందు కలిసి నిలిచిన స్నేహితులు వృద్ధాప్యమందు దేవుని వాగ్దాన ఫలములను పొందిరి."],
    ["1 Samuel 14:6-7 on Jonathan's armor-bearer saying 'I am with you heart and soul'", "1 సమూయేలు 14:6-7 యోనాతాను ఆయుధములు మోయువాడు సంపూర్ణముగా అతనితో నిలుచుట", "1 Samuel 14:7", "\"Do all that is in your heart... behold, I am with you according to your heart\"", "\"నీ హృదయములో ఉన్నదంతయు చేయుము, నీ మనస్సు చొప్పున నేను నీతోకూడ వచ్చెదను\"", "Loyal companions stand shoulder to shoulder against impossible odds.", "యోనాతాను ఆయుధములను మోయువాడు ప్రాణమునకు తెగించి అతనితో కలిసి శత్రువులపైకి వెళ్లెను."],
    ["1 Samuel 19:4 on Jonathan speaking favorably of David before King Saul", "1 సమూయేలు 19:4 సౌలు ఎదుట దావీదు పక్షమున యోనాతాను మంచిగా మాటలాడుట", "1 Samuel 19:4", "\"Jonathan spoke well of David to Saul his father: Let not the king sin against his servant\"", "\"యోనాతాను తన తండ్రియైన సౌలుతో దావీదును గూర్చి మంచిగా మాటలాడెను\"", "True friends advocate courageously for the innocent behind their backs.", "నిజమైన స్నేహితుడు పరోక్షములో కూడ మనలను సమర్థించి మాట్లాడును."],
    ["1 Samuel 20:14-15 on Jonathan requesting perpetual covenant kindness for his house", "1 సమూయేలు 20:14-15 తన సంతతికి నిత్య నిబంధన కృప చూపవలెనని యోనాతాను కోరుట", "1 Samuel 20:14-15", "\"Show me the kindness of the Lord, and cut not off your kindness from my house forever\"", "\"యెహోవా చూపినట్లు నాకు దయచూపుము, నా యింటివారియెడల నీ కృపను ఎన్నడును మానవద్దు\"", "Covenant friendship transcends generations and secures future blessings.", "యోనాతాను మరియు దావీదుల స్నేహ నిబంధన వారి పిల్లల తరములకు రక్షణగా నిలిచెను."],
    ["1 Samuel 22:14 on priest Ahimelech defending David's integrity before enraged Saul", "1 సమూయేలు 22:14 సౌలు ఎదుట యాజకుడైన అహీమెలెకు దావీదు యథార్థతను చాటుట", "1 Samuel 22:14", "\"Who among all your servants is as faithful as David, the king's son-in-law?\"", "\"నీ సేవకులందరిలో దావీదువంటి నమ్మకమైనవాడెవడు?\"", "A godly friend speaks truth even facing the threat of slaughter.", "ప్రాణభయమున్నను అహీమెలెకు దావీదు యొక్క నమ్మకత్వమును చాటెను."],
    ["2 Samuel 10:11 on Joab and Abishai agreeing to assist one another in warfare", "2 సమూయేలు 10:11 యుద్ధములో ఒకరికొకరు సహాయము చేసికొనుటకు యోవాబు అబీషైలు ఒప్పందము", "2 Samuel 10:11", "\"If the Syrians are too strong for me, then you shall help me\"", "\"సిరియన్లు నాకంటె బలవంతులైతే నీవు నన్ను ఆదుకోవలెను; అమ్మోనీయులు నీకంటె బలవంతులైతే నేను నిన్ను ఆదుకొందును\"", "Mutual assistance in spiritual battles guarantees victory over the enemy.", "ఆత్మీయ పోరాటములో తోటి విశ్వాసుల సహాయము జయమునకు కారణమగును."],
    ["1 Kings 4:5 mentioning Zabud son of Nathan as the king's intimate friend", "1 రాజులు 4:5 నాతాను కుమారుడైన జాబూదు రాజునకు ఆప్తమిత్రుడై యుండుట", "1 Kings 4:5", "\"Zabud the son of Nathan was principal officer and the king's friend\"", "\"నాతాను కుమారుడైన జాబూదు ప్రధానుడును రాజునకు స్నేహితుడునై యుండెను\"", "King Solomon kept godly, prophetic friends close to his throne.", "సొలొమోను రాజు దైవిక ఉపదేశము చేయగల విశ్వాసులను తన స్నేహితులుగా ఉంచుకొనెను."],
    ["1 Kings 12:8 on foolish King Rehoboam rejecting elders and listening to young peers", "1 రాజులు 12:8 రెహబాము పెద్దల ఆలోచనను త్రోసిపుచ్చి యౌవన స్నేహితుల మాట వినుట", "1 Kings 12:8", "\"He rejected the advice which the elders had given him, and consulted the young men\"", "\"పెద్దలు చెప్పిన ఆలోచనను త్రోసిపుచ్చి తనతోకూడ పెరిగిన యౌవనస్థుల ఆలోచనను అడిగెను\"", "Listening to foolish, arrogant peers ruined the united kingdom of Israel.", "మూర్ఖులైన యౌవన స్నేహితుల మాట విని రెహబాము రాజ్యాధికారమును కోల్పోయెను."],
    ["2 Chronicles 19:2 rebuking Jehoshaphat for allying with wicked King Ahab", "2 దినవృత్తాంతములు 19:2 భక్తిహీనుడైన అహాబుతో స్నేహము చేసినందుకు యెహోషాపాతును గద్దించుట", "2 Chronicles 19:2", "\"Should you help the wicked and love those who hate the Lord?\"", "\"భక్తిహీనులకు నీవు సహాయము చేయవచ్చా? యెహోవాను ద్వేషించువారిని నీవు ప్రేమింపవచ్చా?\"", "Compromising alliances with God's enemies invite divine displeasure.", "దేవుని శత్రువులతో స్నేహము చేయుట ఆత్మీయ వినాశనమునకు దారితీయును."],
    ["2 Chronicles 20:7 praying to God reminding Him of His friend Abraham", "2 దినవృత్తాంతములు 20:7 దేవుని స్నేహితుడైన అబ్రాహామును జ్ఞాపకము చేసికొని ప్రార్థించుట", "2 Chronicles 20:7", "\"Did You not give it to the descendants of Abraham Your friend forever?\"", "\"నీ స్నేహితుడైన అబ్రాహాము సంతతికి దీనిని నిరంతరము ఇచ్చితివి గదా?\"", "God remembers covenant promises made to His faithful friends across centuries.", "దేవుడు తన స్నేహితుడైన అబ్రాహామునకు చేసిన వాగ్దానములను తరతరములు కాపాడును."],
    ["Nehemiah 2:18 on workers rallying together to rebuild the broken walls of Jerusalem", "నెహెమ్యా 2:18 యెరూషలేము ప్రాకారములను కట్టుటకు ప్రజలు ఏకగ్రీవముగా లేచుట", "Nehemiah 2:18", "\"Let us rise up and build. So they strengthened their hands for this good work\"", "\"మనము లేచి కట్టుదము రండని చెప్పుకొని ఆ మంచి పని చేయుటకు తమ చేతులను బలపరచుకొనిరి\"", "United vision and community encouragement rebuild ruined walls.", "ఐక్యతతో కూడిన స్నేహము కూలిపోయిన ప్రాకారములను తిరిగి నిర్మించును."],
    ["Nehemiah 4:16-18 on companions working with one hand and holding a spear with the other", "నెహెమ్యా 4:16-18 ఒక చేత్తో పని చేయుచు మరియొక చేత్తో ఆయుధము పట్టుకొనుట", "Nehemiah 4:17", "\"With one hand they worked at construction, and with the other held a weapon\"", "\"ఒక చేత్తో పని చేయుచు మరియొక చేత్తో ఆయుధము పట్టుకొనిరి\"", "Vigilant companions guard one another while building God's kingdom.", "ఒకరినొకరు కాపాడుకొనుచు దేవుని పనిని కొనసాగించుటయే నిజమైన సహవాసము."],
    ["Psalm 38:11 on friends and companions standing aloof in times of affliction", "కీర్తన 38:11 శ్రమలలో స్నేహితులు దూరముగా నిలువబడుట", "Psalm 38:11", "\"My loved ones and my friends stand aloof from my plague\"", "\"నా స్నేహితులును నా చెలికాండరును నా తెగులును చూచి దూరముగా నిలుచుచున్నారు\"", "Human companions may abandon us, leading us to cast all hope upon God alone.", "మనుష్యులు దూరమైనప్పుడు దేవుని సన్నిధియే మనకు సంపూర్ణ ఆశ్రయమగును."],
    ["Psalm 88:18 describing darkness as the closest companion in extreme despair", "కీర్తన 88:18 చీకటియే తన ప్రాణమిత్రుడాయెనని కీర్తనకారుడు విలపించుట", "Psalm 88:18", "\"Loved one and friend You have put far from me, and my acquaintances into darkness\"", "\"నా స్నేహితులను నా చెలికాండ్రను నీవు నాకు దూరముగా చేసితివి, చీకటియే నాకు ప్రాణమిత్రుడాయెను\"", "Even in the darkest alienation, Scripture gives voice to honest lament.", "అత్యంత ఘోరమైన ఒంటరితనములో కూడ విశ్వాసి దేవునియొద్ద తన గోడును వెళ్లబోసుకొనవచ్చును."],
    ["Psalm 119:63 declaring companion status with all who fear the Lord", "కీర్తన 119:63 దేవునికి భయపడువారందరికీ తాను స్నేహితుడనని కీర్తనకారుడు పలుకుట", "Psalm 119:63", "\"I am a companion of all who fear You, and of those who keep Your precepts\"", "\"నీయందు భయభక్తులు గలవారందరికిని నీ ఉపదేశములను గైకొనువారికిని నేను చెలికాడను\"", "Reverence for God is the foundation for all lasting, holy friendships.", "దేవునియందు భయభక్తులు కలిగియుండుటయే పరిశుద్ధ సహవాసమునకు పునాది."],
    ["Psalm 133:1 praising the goodness of brethren dwelling together in unity", "కీర్తన 133:1 సహోదరులు ఐక్యత కలిగి నివసించుట ఎంత మనోహరము", "Psalm 133:1", "\"Behold, how good and how pleasant it is for brethren to dwell together in unity!\"", "\"సహోదరులు ఐక్యత కలిగి నివసించుట ఎంత మేలు! ఎంత మనోహరము!\"", "Unity among spiritual brethren commands the commanded blessing of life forevermore.", "సహోదరుల ఐక్యతపై దేవుడు ఆశీర్వాదమును నిత్యజీవమును ఆజ్ఞాపించును."],
    ["Song of Songs 5:16 celebrating the beloved as spouse and intimate friend", "పరమగీతము 5:16 ప్రియుని స్నేహితునిగా కొనియాడుట", "Song of Songs 5:16", "\"This is my beloved, and this is my friend, O daughters of Jerusalem!\"", "\"ఇతడు నా ప్రియుడు, యెరూషలేము కుమార్తెలారా, ఇతడు నా చెలికాడు\"", "Marital love reaches its peak when built on deep, holy friendship.", "వివాహ బంధములో లోతైన ఆత్మీయ స్నేహము అత్యంత మధురమైనది."],
    ["Zechariah 13:6 on wounds received in the house of friends", "జెకర్యా 13:6 స్నేహితుల యింట కలిగిన గాయముల ప్రవచనము", "Zechariah 13:6", "\"Those with which I was wounded in the house of my friends\"", "\"నా స్నేహితుల యింట నాకు కలిగిన గాయములు\"", "Messianic prophecy foreshadowing the suffering Christ endured among His people.", "క్రీస్తు తన స్వజనుల చేతిలోనే గాయపరచబడునను ప్రవచనార్థక సత్యము."],
    ["Matthew 18:19-20 on the power of corporate agreement in prayer", "మత్తయి 18:19-20 ఇద్దరు ఏకీభవించి ప్రార్థించుటలో గల శక్తి", "Matthew 18:19-20", "\"Where two or three are gathered together in My name, I am there in the midst of them\"", "\"ఇద్దరు ముగ్గురు నా నామమున ఎక్కడ కూడియుందురో అక్కడ నేను వారి మధ్యన ఉందును\"", "Christ promises His personal manifest presence where faithful companions gather.", "స్నేహితులు కలిసి ప్రార్థించినప్పుడు యేసు వారి మధ్య ప్రత్యక్షముగా ఉండును."],
    ["Mark 6:7 on Jesus sending out the disciples two by two", "మార్కు 6:7 యేసు తన శిష్యులను ఇద్దరిద్దరిగా పరిచర్యకు పంపుట", "Mark 6:7", "\"He called the twelve to Himself, and began to send them out two by two\"", "\"ఆయన పన్నెండుమందిని తనయొద్దకు పిలిచి, వారిని ఇద్దరిద్దరిగా పంపసాగెను\"", "Jesus modeled mutual protection and shared witness in mission.", "పరిచర్యలో ఒకరికొకరు తోడుగా ఉండుటకే యేసు ఇద్దరిద్దరిని పంపెను."],
    ["Luke 14:12 on inviting the poor rather than only friends who can repay", "లూకా 14:12 తిరిగి పిలువలేని పేదలకు విందు చేయుమని యేసు చెప్పుట", "Luke 14:12-14", "\"Do not invite your friends or rich neighbors, lest they invite you back\"", "\"నీ స్నేహితులనైనను ధనవంతులైన పొరుగువారినైనను పిలువవద్దు, వారు నిన్ను మరల పిలిచెదరు\"", "Kingdom hospitality extends selfless love beyond reciprocal friendships.", "ప్రతిఫలము ఆశించక పేదలను ఆదరించుటయే దైవిక ప్రేమ."],
    ["Luke 15:6 on rejoicing with friends when the lost sheep is recovered", "లూకా 15:6 తప్పిపోయిన గొర్రె దొరికినప్పుడు స్నేహితులతో కలిసి సంతోషించుట", "Luke 15:6", "\"Rejoice with me, for I have found my sheep which was lost!\"", "\"నాతోకూడ సంతోషించుడి, తప్పిపోయిన నా గొర్రె దొరికినది అని స్నేహితులతో చెప్పును\"", "Heavenly joy over recovered souls is shared among holy companions.", "ఆత్మలు రక్షించబడినప్పుడు పరలోకపు సంతోషములో పరిశుద్ధులు పాలుపొందుదురు."],
    ["Luke 15:9 on the woman calling her friends when her lost coin was found", "లూకా 15:9 తప్పిపోయిన నాణెము దొరికినప్పుడు చెలికత్తెలను పిలిచి పండుగ చేసికొనుట", "Luke 15:9", "\"Rejoice with me, for I have found the piece which I lost!\"", "\"నాతోకూడ సంతోషించుడి, నేను పోగొట్టుకొనిన నాణెము దొరికినది అని చెలికత్తెలతో చెప్పును\"", "God's redeeming work calls for communal celebration.", "దేవుడు చేయు రక్షణ కార్యములను చూచి స్నేహితులు కలిసి ఆనందించవలెను."],
    ["Luke 23:12 on the worldly alliance between Pilate and Herod against Christ", "లూకా 23:12 క్రీస్తుకు వ్యతిరేకముగా పిలాతు హేరోదులు స్నేహితులగుట", "Luke 23:12", "\"That very day Pilate and Herod became friends with each other\"", "\"ఆ దినమున పిలాతును హేరోదును ఒకరితో ఒకరు స్నేహితులైరి; అంతకుముందు వారు విరోధులై యుండిరి\"", "Unrighteous men often unite in sinful alliance against God's truth.", "భక్తిహీనులు సత్యమును అణచివేయుటకు అపవిత్రమైన స్నేహములు చేయుదురు."],
    ["Acts 19:31 on influential Asian officials who were Paul's friends warning him", "అపొస్తలుల కార్యములు 19:31 పౌలు స్నేహితులైన ఆసియా అధిపతులు అతనిని హెచ్చరించుట", "Acts 19:31", "\"Certain of the officials of Asia, being his friends, sent to him pleading not to venture into the theater\"", "\"ఆసియా అధిపతులలో పౌలునకు స్నేహితులైన కొందరు రంగస్థలములోనికి వెళ్లవద్దని వర్తమానము పంపిరి\"", "God placed strategic secular friends to protect Paul's life in Ephesus.", "దేవుడు ఉన్నత అధికారులలో కూడ పౌలునకు రక్షణగా స్నేహితులను దయచేసెను."],
    ["Acts 27:3 on Julius the centurion treating Paul kindly and allowing him to visit friends in Sidon", "అపొస్తలుల కార్యములు 27:3 సీదోనులో స్నేహితుల వద్దకు వెళ్ళుటకు శతాధిపతి పౌలుకు అనుమతినిచ్చుట", "Acts 27:3", "\"Julius treated Paul kindly and gave him liberty to go to his friends to receive care\"", "\"యూలియు పౌలును దయతో చూచి, స్నేహితులయొద్దకు వెళ్లి పరామర్శ పొందుటకు సెలవిచ్చెను\"", "Even in chains, God provided freedom to enjoy Christian fellowship.", "సంకెళ్లలో ఉన్నను తోటి విశ్వాసుల ఆదరణ పొందుటకు దేవుడు మార్గము చేసెను."],
    ["Revelation 1:9 on John being our brother and companion in tribulation", "ప్రకటన 1:9 శ్రమలలోను రాజ్యములోను సహోదరుడును సహచరుడునైన యోహాను", "Revelation 1:9", "\"I, John, both your brother and companion in tribulation and kingdom\"", "\"మీ సహోదరుడను, యేసునందలి శ్రమలోను రాజ్యములోను ఓర్పులోను మీతో పాలివాడనునైన యోహాను\"", "True Christian companionship endures through suffering into eternal glory.", "శ్రమలలోను నిత్యరాజ్యములోను క్రీస్తుతోటి విశ్వాసులు నిరంతర సహచరులు."],
    ["Hebrews 13:1 on letting brotherly love continue uninterrupted", "హెబ్రీ 13:1 సహోదరప్రేమ నిరంతరము నిలువవలెనను ఆజ్ఞ", "Hebrews 13:1", "\"Let brotherly love continue\"", "\"సహోదరప్రేమ నిలువరముగా ఉండనీయుడి\"", "The author of Hebrews charges believers to maintain unceasing mutual love and spiritual companionship.", "విశ్వాసుల సహవాసములో సహోదరప్రేమ ఎన్నడును ఆగిపోకూడదని హెబ్రీ గ్రంథకర్త ఆజ్ఞాపించుచున్నాడు."]
  ];

  return data.map((item, idx) => ({
    easyQ: `What biblical truth is taught in ${item[2]} regarding ${item[0]}?`,
    easyQTe: `${item[1]} గూర్చి ${item[2]} లో బోధించబడిన లేఖన సత్యమేమి?`,
    medQ: `How does ${item[2]} direct believers concerning spiritual companions?`,
    medQTe: `${item[2]} లేఖనము ప్రకారం ఆత్మీయ స్నేహితుల విషయములో విశ్వాసులకు ఇవ్వబడిన మార్గదర్శకమేమి?`,
    hardQ: `What theological and practical fruit flows from the teaching of ${item[2]}?`,
    hardQTe: `${item[2]} లోని ఉపదేశము ద్వారా విశ్వాసి జీవితములో ఫలించు ఆత్మీయ ఫలమేమి?`,
    options: [item[3], "To live in isolated mountain caves", "To gather seven wagons of grain", "To avoid all fellowship with people"],
    optionsTelugu: [item[4], "కొండ గుహలలో ఏకాంతముగా ఉండుట", "ఏడు బండ్ల ధాన్యమును కూడబెట్టుకొనుట", "ఎవరితోను సహవాసము చేయకుండుట"],
    correctAnswer: item[3],
    bibleReference: item[2],
    explanation: item[5],
    explanationTelugu: item[6]
  }));
}

// Generate the 3 stages
const fFacts = createRichBank(foundationFacts, "friends", "frn");
const gFacts = buildGrowthFacts();
const mFacts = buildMasteryFacts();

console.log(`Foundation facts count: ${fFacts.length}`);
console.log(`Growth facts count: ${gFacts.length}`);
console.log(`Mastery facts count: ${mFacts.length}`);

buildBank('Friends', 'frn', fFacts, gFacts, mFacts);
